(function(g){var window=this;'use strict';var RR=function(r){r.publish("cardstatechange",r.Y_()&&r.Fc()?1:0)},t9=function(r,V){var I=g.rP(V),d=I?V:arguments;
for(I=I?0:1;I<d.length;I++){if(r==null)return;r=r[d[I]]}return r},ZrK=function(r){var V=g.pj(r);
r=g.Pe(r);return new g.JV(V.x,V.y,r.width,r.height)},Xo6=function(r,V,I){var d=d===void 0?{}:d;
var a;return a=g.Ko(r,V,function(){g.Rx(a);I.apply(r,arguments)},d)},G7=function(r){r=g.dP(r);
delete yy[r];g.ho(yy)&&A9&&A9.stop()},gq9=function(){A9||(A9=new g.hz(function(){BqP()},20));
var r=A9;r.isActive()||r.start()},BqP=function(){var r=g.Yf();
g.i$(yy,function(V){SDK(V,r)});
g.ho(yy)||gq9()},Fv=function(r,V,I,d){g.s8.call(this);
if(!Array.isArray(r)||!Array.isArray(V))throw Error("Start and end parameters must be arrays");if(r.length!=V.length)throw Error("Start and end points must be the same length");this.X=r;this.L=V;this.duration=I;this.W=d;this.coords=[];this.progress=this.C=0;this.Y=null},SDK=function(r,V){V<r.startTime&&(r.endTime=V+r.endTime-r.startTime,r.startTime=V);
r.progress=(V-r.startTime)/(r.endTime-r.startTime);r.progress>1&&(r.progress=1);r.C=1E3/(V-r.Y);r.Y=V;irp(r,r.progress);r.progress==1?(r.G=0,G7(r),r.onFinish(),r.uj()):r.isPlaying()&&r.nI()},irp=function(r,V){typeof r.W==="function"&&(V=r.W(V));
r.coords=Array(r.X.length);for(var I=0;I<r.X.length;I++)r.coords[I]=(r.L[I]-r.X[I])*V+r.X[I]},UsK=function(r,V){g.kI.call(this,r);
this.coords=V.coords;this.x=V.coords[0];this.y=V.coords[1];this.z=V.coords[2];this.duration=V.duration;this.progress=V.progress;this.fps=V.C;this.state=V.G},lq=function(r,V,I,d,a){Fv.call(this,V,I,d,a);
this.element=r},Q3m=function(r,V,I,d,a){if(V.length!=2||I.length!=2)throw Error("Start and end points must be 2D");
lq.call(this,r,V,I,d,a)},ms9=function(r){return Math.pow(r,3)},uOf=function(r){return 3*r*r-2*r*r*r},pom=function(r){g.X.call(this);
this.X=r||window;this.G=[]},LC=function(r){return r.baseUrl||null},J9=function(r,V){return g.Z_(g.uE(r,V),function(I){return!!I})},vqG=function(r,V,I){function d(fg){var rA=fg.hovercardButton;
if(!rA)return null;rA=rA.subscribeButtonRenderer;if(!rA)return null;var ji=f(rA.unsubscribedButtonText),k=f(rA.subscribedButtonText);if(rA.subscribed){var bX=f(rA.subscriberCountWithUnsubscribeText);var RX=f(rA.subscriberCountText)}else bX=f(rA.subscriberCountText),RX=f(rA.subscriberCountWithSubscribeText);var Ui=null;if(fg.signinEndpoint){Ui=t9(fg,"signinEndpoint","webNavigationEndpointData","url");if(!Ui){var $f,jp;Ui=(jp=g.U(($f=rA.signInEndpoint)==null?void 0:$f.commandMetadata,g.Hj))==null?void 0:
jp.url}if(!Ui)return null}return ji&&(k||Ui)?{subscribed:rA.subscribed,subscribeText:ji,subscribeCount:bX,unsubscribeText:k,unsubscribeCount:RX,enabled:rA.enabled,signinUrl:Ui,classic:fg.useClassicSubscribeButton}:null}
function a(fg){if(fg){var rA=[],ji=fg.videoId;ji&&rA.push("v="+ji);(ji=fg.playlistId)&&rA.push("list="+ji);(fg=fg.startTimeSeconds)&&rA.push("t="+fg);return"/watch?"+rA.join("&")}}
function f(fg){if(!fg)return null;var rA=fg.simpleText;return rA?rA:fg.runs?g.uE(fg.runs,function(ji){return ji.text}).join(""):null}
V=V.endscreenElementRenderer;if(!V)return null;var e=V.style,n=V.endpoint||{},D=null,x=null,E=!1,N=null,c=null,z=null,M=null,w=!1,b=null,W=null,K=null,F=null,l=null,B=null;if(e==="VIDEO")g.U(n,g.im)?D=g.U(n,g.im).url:(B=g.U(n,g.dt),D=a(B)),x=!1,N=r,V.thumbnailOverlays?(E=V.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,c=f(E.text),E=E.style==="LIVE"):c=f(V.videoDuration);else if(e==="PLAYLIST")g.U(n,g.im)?D=g.U(n,g.im).url:(B=g.U(n,g.dt),D=a(B)),x=!1,N=r,z=f(V.playlistLength);else if(e===
"CHANNEL"){if(w=t9(n,"browseEndpoint","browseId"))M=w,D="/channel/"+M;x=!1;N="new";(w=!!V.isSubscribe)?b=d(V):W=f(V.subscribersText)}else e==="WEBSITE"?((K=t9(n,"urlEndpoint","url"))&&(D=K),x=!0,N="new",K=V.icon.thumbnails[0].url):e==="CREATOR_MERCHANDISE"&&(V.productPrice&&(F=f(V.productPrice)),V.additionalFeesText&&(l=f(V.additionalFeesText)),(x=t9(n,"urlEndpoint","url"))&&(D=x),x=!0,N="new");r=t9(V,"title","accessibility","accessibilityData","label");var P=V.endpoint?V.endpoint.clickTrackingParams:
null,p="";if(V.metadata){var dA=f(V.metadata);dA&&(p=dA)}return{id:"element-"+I,type:e,title:f(V.title),metadata:p,callToAction:f(V.callToAction),U5:V.image,iconUrl:K,left:Number(V.left),width:Number(V.width),top:Number(V.top),aspectRatio:Number(V.aspectRatio),startMs:Math.floor(Number(V.startMs)),endMs:Math.floor(Number(V.endMs)),videoDuration:c,Dc:E,playlistLength:z,channelId:M,subscribeButton:b,subscribersText:W,isSubscribe:w,targetUrl:D||null,CLk:x,sessionData:P?{itct:P}:null,sQ0:N,qz:r?r:null,
isPlaceholder:V.isPlaceholder,impressionUrls:J9(V.impressionUrls||[],LC),GQQ:J9(V.hovercardShowUrls||[],LC),clickUrls:J9(n.loggingUrls||[],LC),visualElement:g.R9(V.trackingParams),productPrice:F,additionalFeesText:l,watchEndpoint:B||null}},qDK=function(r,V){var I={startMs:Math.floor(Number(r.startMs)),
impressionUrls:J9(r.impressionUrls||[],LC),elements:J9(r.elements||[],function(d,a){return vqG(V,d,a)})};
r.trackingParams&&(I.visualElement=g.R9(r.trackingParams));return I},P0G=function(r){g.zu.call(this,r);
this.Y=this.endscreen=null;this.X={};this.C={};this.W=this.S=null;this.j=[];this.G=null;this.QH=!0;this.L=0;r=r.N();this.V=g.B8(r)||g.S4(r);this.events=new g.Su(this);g.S(this,this.events);this.events.K(this.player,g.nv("creatorendscreen"),this.onCueRangeEnter);this.events.K(this.player,g.jx("creatorendscreen"),this.onCueRangeExit);this.events.K(this.player,"resize",this.yy);this.events.K(window,"focus",this.pKs);this.load();var V=g.rX("STYLE");(g.mQ("HEAD")[0]||document.body).appendChild(V);this.addOnDisposeCallback(function(){g.fy(V)});
V.sheet&&(V.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),V.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},oqm=function(r){return r.player.getVideoData().Mm?"current":r.V?"new":"current"},ZN=function(r){return r.player.N().playerStyle==="creator-endscreen-editor"},kBe=function(r){var V=r.player.getVideoData(),I=V.videoId;
r.Y&&r.Y.abort();I={method:"POST",onFinish:function(a){var f=r.Y=null;a.status===200&&(a=a.responseText,a.substring(0,3)===")]}"&&(a=a.substring(3),f=JSON.parse(a),f=qDK(f,oqm(r))));Xv(r,f)},
urlParams:{v:I},withCredentials:!0};r.V&&(I.urlParams.ptype="embedded");var d=V.MO;d&&(I.postParams={ad_tracking:d});if(V=g.Elh(V))if(V=g.Pt(V),V=g.u_(V))r.Y=g.yr(V,I)},Xv=function(r,V,I){I=I===void 0?!0:I;
r.player.Zg("creatorendscreen");r.S&&(r.S.dispose(),r.S=null,r.W.dispose(),r.W=null);for(var d=g.H(Object.values(r.X)),a=d.next();!a.done;a=d.next())a.value.dispose();r.X={};r.C={};r.j.length>0&&(r.j.forEach(function(n){n.dispose()}),r.j.length=0);
r.G&&(g.xS(r.G,"ytp-ce-element-show"),r.G.setAttribute("aria-hidden","true"));r.L=0;if((r.endscreen=V)&&V.elements){I&&hFc(r);I=[];d=new g.ex(V.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});I.push(d);r.player.N().X||(r.S=new g.u({J:"div",Z:"ytp-ce-shadow"}),g.g1(r.player,r.S.element,4),r.W=new g.eO(r.S,200));for(d=0;d<V.elements.length;++d){a=V.elements[d];var f=reK(r,a);if(f){r.X[a.id]=f;r.C[a.id]=a;g.g1(r.player,f.element,4);var e=new g.ex(a.startMs,a.endMs,{id:"ytp-ce-element-"+
a.id,namespace:"creatorendscreen"});I.push(e);VzK(r,f,a)}else g.gj(new g.ox("buildEndscreenElement null",a))}r.player.Dg(I);r.yy()}},hFc=function(r){var V=g.yo(),I=g.A8();
I&&V&&r.endscreen.visualElement&&g.I6(g.kR)(void 0,I,V,r.endscreen.visualElement)},reK=function(r,V){var I=null;
switch(V.type){case "VIDEO":r={J:"div",Yc:["ytp-ce-element","ytp-ce-video"],D:{tabindex:"0","aria-label":V.qz||"","aria-hidden":"true"},B:[{J:"div",Z:"ytp-ce-element-shadow"},{J:"div",Z:"ytp-ce-covering-image",D:B0(V)},{J:"div",Z:"ytp-ce-covering-shadow-top"},{J:"a",Z:"ytp-ce-covering-overlay",D:{href:g9(r,V.targetUrl),tabindex:"-1"},B:[{J:"div",Yc:["ytp-ce-video-title","ytp-webkit-ellipsis"],D:{dir:g.Te(V.title||"")},OE:V.title},{J:"div",Z:V.Dc?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
OE:V.videoDuration||void 0}]}]};I=new g.u(r);break;case "PLAYLIST":r={J:"div",Yc:["ytp-ce-element","ytp-ce-playlist"],D:{tabindex:"0","aria-label":V.qz||"","aria-hidden":"true"},B:[{J:"div",Z:"ytp-ce-element-shadow"},{J:"div",Z:"ytp-ce-covering-image",D:B0(V)},{J:"div",Z:"ytp-ce-covering-shadow-top"},{J:"a",Z:"ytp-ce-covering-overlay",D:{href:g9(r,V.targetUrl),tabindex:"-1"},B:[{J:"div",Yc:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],D:{dir:g.Te(V.title||"")},OE:V.title},{J:"div",Z:"ytp-ce-playlist-count",
B:[{J:"div",Z:"ytp-ce-playlist-icon"},{J:"div",Z:"ytp-ce-playlist-count-text",OE:V.playlistLength||void 0}]}]}]};I=new g.u(r);break;case "CHANNEL":I={J:"div",Yc:["ytp-ce-element","ytp-ce-channel",V.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],D:{tabindex:"0","aria-label":V.qz||"","aria-hidden":"true"},B:[{J:"div",Z:"ytp-ce-element-shadow"},{J:"div",Z:"ytp-ce-expanding-overlay",B:[{J:"div",Z:"ytp-ce-expanding-overlay-hider"},{J:"div",Z:"ytp-ce-expanding-overlay-background"},{J:"div",Z:"ytp-ce-expanding-overlay-content",
B:[{J:"div",Z:"ytp-ce-expanding-overlay-body",B:[{J:"div",Z:"ytp-ce-expanding-overlay-body-padding",B:[{J:"a",Yc:["ytp-ce-channel-title","ytp-ce-link"],D:{href:g9(r,V.targetUrl),target:"_blank",tabindex:"-1",dir:g.Te(V.title||"")},OE:V.title},V.subscribeButton?{J:"div",Z:"ytp-ce-subscribe-container",B:[{J:"div",Z:"ytp-ce-channel-subscribe"}]}:"",V.subscribersText?{J:"div",Z:"ytp-ce-channel-subscribers-text",OE:V.subscribersText}:"",V.metadata?{J:"div",Yc:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],OE:V.metadata}:""]}]}]}]},{J:"div",Z:"ytp-ce-expanding-image",D:B0(V)}]};I=new g.u(I);var d=g.pJ(document,"div","ytp-ce-channel-subscribe",I.element)[0];if(V.subscribeButton&&V.channelId){g.jN(d,"ytp-ce-subscribe-button");if(r.player.N().X){var a=null;var f=V.sessionData.itct}else a="endscreen",f=null;a=new g.PD(V.subscribeButton.subscribeText,V.subscribeButton.subscribeCount,V.subscribeButton.unsubscribeText,V.subscribeButton.unsubscribeCount,!!V.subscribeButton.enabled,!!V.subscribeButton.classic,
V.channelId,!!V.subscribeButton.subscribed,a,f,r.player,!1);d.appendChild(a.element);r.j.push(a)}break;case "WEBSITE":r={J:"div",Yc:["ytp-ce-element","ytp-ce-website"],D:{tabindex:"0","aria-label":V.qz||"","aria-hidden":"true"},B:[{J:"div",Z:"ytp-ce-element-shadow"},{J:"div",Z:"ytp-ce-expanding-overlay",B:[{J:"div",Z:"ytp-ce-expanding-overlay-hider"},{J:"div",Z:"ytp-ce-expanding-overlay-background"},{J:"div",Z:"ytp-ce-expanding-overlay-content",B:[{J:"div",Z:"ytp-ce-expanding-overlay-body",B:[{J:"div",
Z:"ytp-ce-expanding-overlay-body-padding",B:[{J:"div",Z:"ytp-ce-website-title",D:{dir:g.Te(V.title||"")},OE:V.title},{J:"div",Z:"ytp-ce-website-metadata",OE:V.metadata},{J:"a",Yc:["ytp-ce-website-goto","ytp-ce-link"],D:{href:g9(r,V.targetUrl),target:"_blank",tabindex:"-1"},OE:V.callToAction}]}]}]}]},{J:"div",Z:"ytp-ce-expanding-image",D:B0(V)},{J:"div",Z:"ytp-ce-expanding-icon",D:I8c(V.iconUrl)}]};I=new g.u(r);break;case "CREATOR_MERCHANDISE":I="",V.productPrice&&(I={J:"div",Z:"ytp-ce-merchandise-price-container",
B:[{J:"div",Z:"ytp-ce-merchandise-price",OE:V.productPrice}]},V.additionalFeesText&&I.B.push({J:"div",Z:"ytp-ce-merchandise-additional-fees",OE:V.additionalFeesText})),r={J:"div",Yc:["ytp-ce-element","ytp-ce-merchandise"],D:{tabindex:"0","aria-label":V.qz||"","aria-hidden":"true"},B:[{J:"div",Z:"ytp-ce-element-shadow"},{J:"div",Z:"ytp-ce-expanding-overlay",B:[{J:"div",Z:"ytp-ce-expanding-overlay-hider"},{J:"div",Z:"ytp-ce-expanding-overlay-background"},{J:"div",Z:"ytp-ce-expanding-overlay-content",
B:[{J:"div",Z:"ytp-ce-expanding-overlay-body",B:[{J:"div",Z:"ytp-ce-expanding-overlay-body-padding",B:[{J:"div",Z:"ytp-ce-merchandise-title",D:{dir:g.Te(V.title||"")},OE:V.title},I,{J:"div",Z:"ytp-ce-merchandise-metadata",OE:V.metadata},{J:"a",Yc:["ytp-ce-merchandise-goto","ytp-ce-link"],D:{href:g9(r,V.targetUrl),target:"_blank",tabindex:"-1"},OE:V.callToAction}]}]}]}]},{J:"div",Z:"ytp-ce-expanding-image",D:B0(V)},{J:"div",Z:"ytp-ce-merchandise-invideo-cta-container",B:[{J:"div",Z:"ytp-ce-merchandise-invideo-cta",
OE:V.callToAction||void 0}]}]},I=new g.u(r)}V.isPlaceholder&&g.jN(I.element,"ytp-ce-placeholder");return I},B0=function(r){if(r.U5)var V=r.U5.thumbnails;
return I8c(V?V[V.length-1].url:null)},I8c=function(r){return r?{style:"background-image: url("+r+")"}:{}},VzK=function(r,V,I){function d(D){D&&(V.listen("blur",function(){D.style.display!="none"&&r.QH&&D.focus()}),V.K(D,"focus",f),V.K(D,"blur",e))}
function a(D){r.L+=D;r.L>0?(g.jN(V.element,"ytp-ce-force-expand"),Sh(r,I.id,!0)):(g.xS(V.element,"ytp-ce-force-expand"),g.xS(V.element,"ytp-ce-element-hover"),Sh(r,I.id,!1))}
function f(){a(1)}
function e(){a(-1)}
V.listen("mouseenter",function(){de$(r,V,I)});
V.listen("mouseleave",function(){a8f(r,V,I)});
r.player.N().X||V.listen("click",function(){g.jN(V.element,"ytp-ce-element-hover")});
V.listen("click",function(D){f8G(r,I,D)});
V.listen("keypress",function(D){f8G(r,I,D)});
V.listen("focus",function(){de$(r,V,I)});
V.listen("blur",function(){a8f(r,V,I)});
V.listen("touchstart",function(){de$(r,V,I)});
var n=g.vz("ytp-ce-expanding-overlay-hider",V.element);n&&V.K(n,"touchstart",function(D){D.stopPropagation();g.xS(V.element,"ytp-ce-element-hover");g.xS(V.element,"ytp-ce-force-expand")});
V.listen("keydown",function(D){r.QH=D.keyCode===9&&!D.shiftKey});
d(g.vz("ytp-sb-subscribe",V.element));d(g.vz("ytp-sb-unsubscribe",V.element));V.listen("focus",f);V.listen("blur",e)},f8G=function(r,V,I){if(V.targetUrl&&(!I||I.type!=="keypress"||I.keyCode===13)){for(var d=I.target;d&&!g.nL(d,"ytp-ce-element");){g.nL(d,"subscribe-label")&&elc(r,V);
if(g.nL(d,"ytp-ce-channel-subscribe"))return;d=d.parentElement||null}if(!d||g.nL(d,"ytp-ce-element-hover")){I.preventDefault();I.stopPropagation();if(d=r.X[V.id])a8f(r,d,V),d.element.blur();if(I.ctrlKey||I.metaKey||V.sQ0==="new")elc(r,V),r.player.sendVideoStatsEngageEvent(17,void 0),r.player.pauseVideo(),I=g.Pt(g9(r,V.targetUrl)),I=g.u_(I),g.vC(I,void 0,V.sessionData);else{var a=g.VO(r.player.N())||r.player.getVideoData().Mm,f=function(){var e=g9(r,V.targetUrl),n=V.sessionData,D=V.watchEndpoint,x=
g.n5(e);a&&x&&(x.v||x.list)?r.player.hO(x.v,n,x.list,!1,void 0,D||void 0):g.pW(e,n)};
elc(r,V,function(){r.player.sendVideoStatsEngageEvent(17,f)})}}}},g9=function(r,V){r=r.player.N();
if(V){if(V.startsWith("//"))return r.protocol+":"+V;if(V.startsWith("/"))return g.ni(r)+V}else return"";return V},de$=function(r,V,I){g.nL(V.element,"ytp-ce-element-hover")||(I.type==="VIDEO"||I.type==="PLAYLIST"?g.jN(V.element,"ytp-ce-element-hover"):r.player.N().X?(new g.hz(function(){g.jN(V.element,"ytp-ce-element-hover")},200)).start():g.jN(V.element,"ytp-ce-element-hover"),iq(r,I.GQQ),Sh(r,I.id,!0))},a8f=function(r,V,I){g.xS(V.element,"ytp-ce-element-hover");
g.xS(V.element,"ytp-ce-force-expand");Sh(r,I.id,!1)},Sh=function(r,V,I){r.S&&(I?r.W.show():r.W.hide());
for(var d=g.H(Object.keys(r.X)),a=d.next();!a.done;a=d.next())a=a.value,a!==V&&g.NA(r.X[a].element,"ytp-ce-element-shadow-show",I)},iq=function(r,V,I){function d(){f||(a++,a===V.length&&(e.stop(),I&&I()))}
if(!V||V.length===0||ZN(r))I&&I();else{V=Y$G(r,V);var a=0,f=!1,e=new g.hz(function(){f=!0;I&&I()},1E3,r);
e.start();for(r=0;r<V.length;r++)g.mn(V[r],d)}},elc=function(r,V,I){iq(r,V.clickUrls,I);
(r=g.A8())&&V.CLk&&g.Du(r,V.visualElement)},Y$G=function(r,V){var I=r.player.getVideoData().clientPlaybackNonce;
r=r.player.getCurrentTime().toFixed(2);I={CPN:I,AD_CPN:I,MT:r};r=[];for(var d=0;d<V.length;d++)r.push(nVP(V[d],I));return r},nVP=function(r,V){return r.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(I){var d=unescape(I);
d=d.substring(1,d.length-1);return V[d]?escape(V[d]):I})},jOo=function(r){return typeof r==="string"?r:""},UZ=function(r,V,I){for(var d in V)if(V[d]===r)return r;
return I},De6=function(r,V,I,d){this.value=r;
this.target=V;this.showLinkIcon=I;this.G=d},Qy=function(r){return r.value?r.value:null},mC=function(r){if(!r)return null;
var V=g.Pt(jOo(r.value));V=g.u_(V);if(!V)return null;var I=UZ(r.target,xeP,"current");if(I==null)r=null;else{var d=r.show_link_icon;r=new De6(V,I,d==="true"||d==="false"?d==="true":!0,r.pause_on_navigation!=null?r.pause_on_navigation:!0)}return r},EV6=function(r,V,I){this.type=r;
this.trigger=V;this.url=I},ce6=function(r){if(!r)return null;
var V=UZ(r.type,NJo),I=UZ(r.trigger,sOY);r=r.url;r=Array.isArray(r)&&r.length?r[0]:r;r=mC(r?r:null);return V?new EV6(V,I,r):null},zlP=function(r,V,I,d,a){this.id=r;
this.type=V;this.style=I;this.data=a;this.action=d||[]},Mzo=function(r,V){return g.z6(r.action,V)},CT_=function(r,V){this.context=r;
this.G=V},TJ6=function(r){return r.customMessage?uq("div","iv-card-message",r.customMessage):""},pC=function(r,V){r="background-image: url("+r+");";
var I=[];V&&I.push(V);return{J:"div",Z:"iv-card-image",D:{style:r},B:I}},H9G=function(r){if(!r.metaInfo||r.metaInfo.length===0)return"";
var V=[];r=g.H(r.metaInfo);for(var I=r.next();!I.done;I=r.next())V.push(uq("li","",I.value));return{J:"ul",Z:"iv-card-meta-info",B:V}},uq=function(r,V,I){V?typeof V==="string"?V={"class":V}:Array.isArray(V)&&(V={"class":V.join(" ")}):V={};
V.dir=g.Te(I);return{J:r,D:V,OE:I}},wve=function(r){if(!r.customMessage)return"";
var V=["iv-card-action","iv-card-primary-link"],I={};r.ox&&(V.push("iv-card-action-icon"),I.style="background-image: url("+r.ox+");");I.dir=g.Te(r.customMessage);var d=[{J:"span",OE:r.customMessage}];r.showLinkIcon&&(d.push("\u00a0"),d.push({J:"span",Z:"iv-card-link-icon"}));return{J:"div",Yc:V,D:I,B:d}},v0=function(r,V,I,d){if(d){V=g.H(V);
for(var a=V.next();!a.done;a=V.next())r.G(a.value,d,I.id,I.sessionData,I.JK.click,5)}},b9f=function(r,V){this.merchant=r;
this.price=V},O9c=function(r){var V;
(V=r)&&!(V=r.length>1?r.charAt(0)==="/"&&r.charAt(1)!=="/":r==="/")&&(V=r.replace(/^(https?:)?\/\//,"").split("/",1),V=!V||V.length<1||!V[0]?[]:V[0].toLowerCase().split(".").reverse(),V=V[0]==="com"&&V[1]==="youtube"||V[0]==="be"&&V[1]==="youtu");return V?r.indexOf("/redirect?")===-1:!1},WvP=function(r,V){return V?V:O9c(r)?"current":"new"},qt=function(r,V){g.X.call(this);
var I=this;this.element=r;this.context=V;this.DM=!1;this.L8=new Map;this.EE=new Map;this.context.T.addEventListener(g.nv("annotations_module"),function(d){(d=I.L8.get(d))&&d.apply(I)});
this.context.T.addEventListener(g.jx("annotations_module"),function(d){(d=I.EE.get(d))&&d.apply(I)})},P0=function(r,V,I,d,a,f,e){r.context.G.listen(V,"click",function(n){r.Sy(I,d,a,f||[],e||0,n)});
r.context.G.listen(V,"touchstart",function(){r.DM=!1});
r.context.G.listen(V,"touchmove",function(){r.DM=!0})},$ep=function(r){var V;
return((V=g.U(r,g.im))==null?0:V.url)?g.U(r,g.im).url:(r=g.U(r,g.dt))&&r.videoId?(V="/watch?v="+r.videoId,r.playlistId&&(V+="&list="+r.playlistId),r.index&&(V+="&index="+r.index),r.startTimeSeconds&&(V+="&t="+r.startTimeSeconds),V):null},oR=function(r,V,I){return{HM:(r.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(I.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(V.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
rO:(V.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
Ki:(V.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Kv$=function(r,V,I){qt.call(this,V,I);
var d=this;this.T=r;this.eventId=null;this.rH=this.p8=this.X_=this.S=this.isInitialized=!1;this.cards=[];this.ya=this.j=this.R7=this.W=this.Ws=this.G=null;this.QH=[];this.kc=this.L=this.lI=this.n8=null;this.C=0;this.GQ=new g.hz(function(){},I.yH.G6?4E3:3E3);
g.S(this,this.GQ);this.Mk=new g.hz(function(){});
g.S(this,this.Mk);this.bL=new CT_(I,function(a,f,e,n,D,x){P0(d,a,f,e,n,D,x)});
this.V=new g.u({J:"div",Z:"iv-drawer",D:{id:"iv-drawer"},B:[{J:"div",Z:"iv-drawer-header",D:{"aria-role":"heading"},B:[{J:"span",Z:"iv-drawer-header-text"},{J:"button",Yc:["iv-drawer-close-button","ytp-button"],D:{"aria-label":"Hide cards",tabindex:"0"}}]},{J:"div",Z:"iv-drawer-content"}]});g.S(this,this.V);this.Y=this.V.element;this.a7=new g.eO(this.V,330);g.S(this,this.a7);this.Qa=g.vz("iv-drawer-header-text",this.Y);this.X=g.vz("iv-drawer-content",this.Y);this.addCueRange(0,I.videoData.lengthSeconds*
1E3,"",function(){d.X_&&kF(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.X_=d.S)&&h9(d)});
this.TQ=new g.Su(this);g.S(this,this.TQ);this.T.addEventListener("videodatachange",this.xg.bind(this))},Rlo=function(r,V){V=V.data;
V.autoOpenMs&&r.addCueRange(V.autoOpenMs,0x8000000000000,"",function(){kF(r,"YOUTUBE_DRAWER_AUTO_OPEN")});
V.autoCloseMs&&r.addCueRange(V.autoCloseMs,0x8000000000000,"",function(){h9(r)});
var I=V.headerText;g.Yx(r.Qa,I);r.j&&r.j.setAttribute("title",I);V.eventId&&(r.eventId=V.eventId);r.n8=g.R9(V.trackingParams);r.L=g.R9(V.closeTrackingParams);r.lI=g.R9(V.iconTrackingParams)},tzG=function(r,V){var I=V.cardId?V.cardId:"cr:"+r.C,d=r.T.N().experiments.uL("enable_error_corrections_infocard_web_client");
if(!V.content&&V.teaser.simpleCardTeaserRenderer&&d){var a=V.teaser.simpleCardTeaserRenderer,f=V.icon?V.icon.infoCardIconRenderer:null;V={id:I,timestamp:r.C,type:"simple",teaserText:g.wF(a.message),teaserDurationMs:Number(V.cueRanges[0].teaserDurationMs),startMs:Number(V.cueRanges[0].startCardActiveMs),autoOpen:!!V.autoOpen,sessionData:{},sponsored:!1,JK:{},qR:null,HO:a.trackingParams?g.R9(a.trackingParams):null,lI:f&&f.trackingParams?g.R9(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
ox:null,title:"",customMessage:"",url:null,onClickCommand:a.onTapCommand||null};rO(r,V)}else{var e;if((e=V.content)==null?0:e.simpleCardContentRenderer){if(!V.cueRanges.length)return;f=(a=V.content)==null?void 0:a.simpleCardContentRenderer;a=V.teaser.simpleCardTeaserRenderer;var n=V.icon?V.icon.infoCardIconRenderer:null;V={id:I,timestamp:r.C,type:"simple",teaserText:g.wF(a.message),teaserDurationMs:Number(V.cueRanges[0].teaserDurationMs),startMs:Number(V.cueRanges[0].startCardActiveMs),autoOpen:!!V.autoOpen,
sessionData:Vl(r,I,V,f),sponsored:!1,JK:oR(f,a,f.command),qR:f.trackingParams?g.R9(f.trackingParams):null,HO:a.trackingParams?g.R9(a.trackingParams):null,lI:n&&n.trackingParams?g.R9(n.trackingParams):null,imageUrl:Ik(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.wF(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,ox:null,title:f.title?g.wF(f.title):"",customMessage:f.callToAction?g.wF(f.callToAction):"",url:g.U(f.command,g.im).url?mC({pause_on_navigation:!r.context.videoData.isLivePlayback,
target:"new",value:g.U(f.command,g.im).url}):null,onClickCommand:null};rO(r,V)}else{var D;if((D=V.content)==null?0:D.collaboratorInfoCardContentRenderer){if(!V.cueRanges.length)return;a=(f=V.content)==null?void 0:f.collaboratorInfoCardContentRenderer;f=V.teaser.simpleCardTeaserRenderer;n=V.icon?V.icon.infoCardIconRenderer:null;V={id:I,timestamp:r.C,type:"collaborator",teaserText:g.wF(f.message),teaserDurationMs:Number(V.cueRanges[0].teaserDurationMs),startMs:Number(V.cueRanges[0].startCardActiveMs),
autoOpen:!!V.autoOpen,sessionData:Vl(r,I,V,a),sponsored:!1,JK:oR(a,f,a.endpoint),qR:a.trackingParams?g.R9(a.trackingParams):null,HO:f.trackingParams?g.R9(f.trackingParams):null,lI:n&&n.trackingParams?g.R9(n.trackingParams):null,channelId:g.U(a.endpoint,g.yW).browseId,customMessage:a.customText?g.wF(a.customText):null,profileImageUrl:Ik(a.channelAvatar.thumbnails,290).url,title:a.channelName?g.wF(a.channelName):"",metaInfo:[a.subscriberCountText?g.wF(a.subscriberCountText):""],url:mC({pause_on_navigation:!r.context.videoData.isLivePlayback,
target:"new",value:g.U(a.endpoint,g.yW).canonicalBaseUrl?g.U(a.endpoint,g.yW).canonicalBaseUrl:"/channel/"+g.U(a.endpoint,g.yW).browseId}),onClickCommand:null};rO(r,V)}else{var x;if((x=V.content)==null?0:x.playlistInfoCardContentRenderer){if(!V.cueRanges.length)return;a=(n=V.content)==null?void 0:n.playlistInfoCardContentRenderer;f=V.teaser.simpleCardTeaserRenderer;n=V.icon?V.icon.infoCardIconRenderer:null;V={id:I,timestamp:r.C,type:"playlist",teaserText:g.wF(f.message),teaserDurationMs:Number(V.cueRanges[0].teaserDurationMs),
startMs:Number(V.cueRanges[0].startCardActiveMs),autoOpen:!!V.autoOpen,sessionData:Vl(r,I,V,a),sponsored:!1,JK:oR(a,f,a.action),qR:a.trackingParams?g.R9(a.trackingParams):null,HO:f.trackingParams?g.R9(f.trackingParams):null,lI:n&&n.trackingParams?g.R9(n.trackingParams):null,pE:Ik(a.playlistThumbnail.thumbnails,258).url,customMessage:a.customMessage?g.wF(a.customMessage):null,playlistVideoCount:g.wF(a.playlistVideoCount),title:a.playlistTitle?g.wF(a.playlistTitle):"",metaInfo:[a.channelName?g.wF(a.channelName):
"",a.videoCountText?g.wF(a.videoCountText):""],url:mC({pause_on_navigation:!r.context.videoData.isLivePlayback,target:"new",value:$ep(a.action)}),onClickCommand:null};rO(r,V)}else{var E;if((E=V.content)==null?0:E.videoInfoCardContentRenderer){if(!V.cueRanges.length)return;var N;a=(N=V.content)==null?void 0:N.videoInfoCardContentRenderer;f=V.teaser.simpleCardTeaserRenderer;n=V.icon?V.icon.infoCardIconRenderer:null;V={id:I,timestamp:r.C,type:"video",teaserText:g.wF(f.message),teaserDurationMs:Number(V.cueRanges[0].teaserDurationMs),
startMs:Number(V.cueRanges[0].startCardActiveMs),autoOpen:!!V.autoOpen,sessionData:Vl(r,I,V,a),sponsored:!1,JK:oR(a,f,a.action),qR:a.trackingParams?g.R9(a.trackingParams):null,HO:f.trackingParams?g.R9(f.trackingParams):null,lI:n&&n.trackingParams?g.R9(n.trackingParams):null,pE:Ik(a.videoThumbnail.thumbnails,258).url,videoDuration:a.lengthString?g.wF(a.lengthString):null,customMessage:a.customMessage?g.wF(a.customMessage):null,title:a.videoTitle?g.wF(a.videoTitle):"",metaInfo:[a.channelName?g.wF(a.channelName):
"",a.viewCountText?g.wF(a.viewCountText):""],isLiveNow:!!a.badge,url:mC({pause_on_navigation:!r.context.videoData.isLivePlayback,target:"new",value:$ep(a.action)}),onClickCommand:null};rO(r,V)}}}}}r.C++},Ik=function(r,V){for(var I=-1,d=-1,a=0;a<r.length;a++){if(r[a].height===V||r[a].width===290)return r[a];
((r[a].height||0)<V||(r[a].width||0)<290)&&(I<0||(r[I].height||0)<(r[a].height||0)||(r[I].width||0)<(r[a].width||0))?I=a:((r[a].height||0)>=V||(r[a].width||0)>=290)&&(d<0||(r[d].height||0)>(r[a].height||0)||(r[d].width||0)>(r[a].width||0))&&(d=a)}return r[d>=0?d:I]},Vl=function(r,V,I,d){return{feature:I.feature?I.feature:"cards",
src_vid:r.context.videoData.videoId,annotation_id:V,ei:r.context.videoData.eventId||"",itct:d.trackingParams||""}},AeG=function(r,V){if(V=yeo(r,V))V===r.G&&(r.G=null),r.T.removeCueRange(V.DQ.id),g.fy(V.K7),g.H9(r.cards,V),r.Dz(),dO(r)},kF=function(r,V,I){if(!r.S){r.a7.show();
r.Ws=new g.hz(function(){g.jN(r.context.T.getRootNode(),g.IC.IV_DRAWER_OPEN)},0);
r.Ws.start();r.TQ.K(r.X,"mousewheel",function(e){r.GQ.start();e.preventDefault();e=e||window.event;var n=0;e.type=="MozMousePixelScroll"?n=0==(e.axis==e.HORIZONTAL_AXIS)?e.detail:0:window.opera?n=e.detail:n=e.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?e.wheelDeltaY/-30:e.wheelDeltaY/-1.2:e.wheelDelta/-1.6:e.wheelDeltaY/-3;if(e=n)r.X.scrollTop+=e});
r.S=!0;var d=g.A8();d&&r.n8&&r.L&&g.nB(d,[r.n8,r.L]);V={TRIGGER_TYPE:V};for(var a=g.H(r.cards),f=a.next();!f.done;f=a.next())f=f.value,f.HP||(f.HP=!0,Gsp(r.context.logger,f.DQ.JK.HM,V)),d&&g.nB(d,[f.DQ.qR]);RR(r.T);I&&(r.W=new g.hz(function(){r.R7=r.j;r.ya.focus()},330),r.W.start())}},h9=function(r){r.S&&(r.a7.hide(),g.lQ(r.TQ),g.xS(r.context.T.getRootNode(),g.IC.IV_DRAWER_OPEN),r.S=!1,RR(r.T),r.W&&r.W.stop(),r.W=new g.hz(function(){r.R7&&(r.R7.focus(),r.R7=null)},330),r.W.start())},Fv$=function(r){g.DX(r.YN(),
[g.IC.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.g1(r.T,r.Y,5);r.Zz();r.j=g.vz("ytp-cards-button",r.T.getRootNode());r.ya=g.vz("iv-drawer-close-button",r.Y);r.isInitialized=!0},l8G=function(r){r.QH.push(g.jl("iv-teaser-shown",r.u1,r));
r.QH.push(g.jl("iv-teaser-hidden",r.gc8,r));r.QH.push(g.jl("iv-teaser-clicked",r.Ni,r));r.rH=!0},LvY=function(r,V){var I;
return V.onClickCommand&&((I=g.U(V.onClickCommand,g.Dyo))==null?void 0:I.targetId)==="engagement-panel-error-corrections"?(r.kc=V,!0):!1},Jem=function(r,V){r.kc=V;
var I=r.T.getVideoData();if(!I)return!1;I=g.Gp(I);if(I==null?0:I.markersMap)for(var d,a=0;((d=I)==null?void 0:d.markersMap.length)>a;a++){var f=void 0,e=(f=I)==null?void 0:f.markersMap[a];if(e.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(e=(f=e.value)==null?void 0:f.markers)&&e.length>0))return d=void 0,V.startMs=((d=g.U(e[0],g.gFU))==null?void 0:d.timeRangeStartMillis)||0,r.kc=null,!0}return!1},rO=function(r,V){if(!LvY(r,V)||Jem(r,V)){var I=Z9K(r,V);
if(I){var d={DQ:V,K7:I.element,HP:!1};if(V.onClickCommand)r.T.U("web_infocards_teaser_show_logging_fix")&&(r.rH||l8G(r),AeG(r,V.id),I=r.findLastIndex(d),g.to(r.cards,I,0,d));else{r.isInitialized||Fv$(r);AeG(r,V.id);var a=r.findLastIndex(d);g.to(r.cards,a,0,d);I.Xz(r.X,a);r.Dz()}V.autoOpen?r.addCueRange(V.startMs,0x8000000000000,V.id,function(){r.S||(r.G=d,dO(r),XvY(r,d),kF(r,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(I=r.context.T.getCurrentTime()*1E3,I<5E3&&I>V.startMs&&BJG(r,d),r.addCueRange(V.startMs,
V.startMs+1,V.id,function(){BJG(r,d)}),dO(r))}}},Z9K=function(r,V){switch(V.type){case "simple":r=r.bL;
var I=V.displayDomain?{J:"div",Z:"iv-card-image-text",OE:V.displayDomain}:void 0;var d=wve(V);I={J:"div",Yc:["iv-card"],B:[{J:"a",Z:"iv-click-target",D:{href:V.url?Qy(V.url)||"":""},B:[pC(V.imageUrl,I),{J:"div",Z:"iv-card-content",B:[uq("h2",void 0,V.title),d]}]}]};I=new g.u(I);v0(r,g.ub("iv-click-target",I.element),V,V.url);V=I;break;case "collaborator":r=r.bL;I={J:"div",Yc:["iv-card","iv-card-channel"],B:[{J:"a",Yc:["iv-click-target"],D:{href:Qy(V.url)||"","data-ytid":V.channelId},B:[pC(V.profileImageUrl),
{J:"div",Z:"iv-card-content",B:[TJ6(V),{J:"h2",Z:"iv-card-primary-link",OE:V.title},H9G(V)]}]}]};I=new g.u(I);v0(r,g.ub("iv-click-target",I.element),V,V.url);V=I;break;case "playlist":r=r.bL;I={J:"div",Yc:["iv-card","iv-card-playlist"],B:[{J:"a",Z:"iv-click-target",D:{href:Qy(V.url)||""},B:[pC(V.pE,{J:"div",Z:"iv-card-image-overlay",B:[{J:"span",Z:"iv-card-playlist-video-count",OE:V.playlistVideoCount}]}),{J:"div",Z:"iv-card-content",B:[TJ6(V),uq("h2","iv-card-primary-link",V.title),H9G(V)]}]}]};
I=new g.u(I);v0(r,g.ub("iv-click-target",I.element),V,V.url);V=I;break;case "productListing":r=r.bL;var a=V.offers.length!=0;I=["iv-card"];d="";var f=wve(V);a&&(I.push("iv-card-product-listing"),d="iv-card-primary-link",f=V.offers[0],a=[],f.price&&a.push({J:"div",Z:"iv-card-offer-price",OE:f.price}),f.merchant&&a.push({J:"div",Z:"iv-card-offer-merchant",OE:f.merchant}),f={J:"div",B:a});a=V.url?Qy(V.url)||"":"";I={J:"div",Yc:I,D:{tabindex:"0"},B:[{J:"a",Yc:["iv-card-image","iv-click-target"],D:{style:"background-image: url("+
V.imageUrl+");",href:a,"aria-hidden":"true",tabindex:"-1"}},{J:"div",Z:"iv-card-content",B:[V.sponsored?{J:"div",Z:"iv-card-sponsored",B:["Sponsored",{J:"div",Z:"iv-ad-info-container",B:[{J:"div",Z:"iv-ad-info",OE:"{{adInfo}}"},{J:"div",Z:"iv-ad-info-icon-container",B:[{J:"div",Z:"iv-ad-info-icon"},{J:"div",Z:"iv-ad-info-callout"}]}]}]}:"",{J:"a",Z:"iv-click-target",D:{href:a},B:[uq("h2",d,V.title),f]}]}]};I=new g.u(I);d=g.rX("span");g.Yx(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
I.ys(d,"adInfo");v0(r,g.ub("iv-click-target",I.element),V,V.url);V=I;break;case "video":r=r.bL;d=V.videoDuration?{J:"span",Z:"iv-card-video-duration",OE:V.videoDuration}:void 0;f=V.isLiveNow?{J:"span",Yc:["yt-badge","yt-badge-live"],OE:"LIVE NOW"}:null;a={J:"div",Yc:["iv-card","iv-card-video"],B:[{J:"a",Z:"iv-click-target",D:{href:((I=V.url)==null?void 0:Qy(I))||""},B:[pC(V.pE,d),{J:"div",Z:"iv-card-content",B:[TJ6(V),uq("h2","iv-card-primary-link",V.title),H9G(V),f]}]}]};I=new g.u(a);v0(r,g.ub("iv-click-target",
I.element),V,V.url);V=I;break;default:return null}return V},gVe=function(r){if(r.G)return r.G.DQ.type==="productListing";
if(r.T.U("enable_wn_infocards")){var V;return!((V=r.cards)==null||!V.length)&&g.py(r.cards,function(I){return I.DQ.type==="productListing"})}return g.py(r.cards,function(I){return I.DQ.type==="productListing"})},dO=function(r){g.NA(r.T.getRootNode(),"ytp-cards-shopping-active",gVe(r))},BJG=function(r,V){if(!g.nL(r.T.getRootNode(),"ytp-cards-teaser-shown")){if(r.G!==V){var I=g.A8(),d=r.G?r.G.DQ.lI:r.lI;
I&&d&&g.jA(I,[d]);r.G=V;dO(r)}if(I=r.isInitialized)I=r.YN().style.display=="none";I||(I=r.context.T.getPlayerState(),d=I===0&&r.context.T.getCurrentTime()===0,I=!(I===1||I===3||d));I||V.DQ.teaserDurationMs&&r.T.qF(!0,{teaserText:V.DQ.teaserText,durationMs:V.DQ.teaserDurationMs,onClickCommand:V.DQ.onClickCommand});r.Mk.isActive()||((!r.S||!r.GQ.isActive()&&r.p8)&&XvY(r,V),r.Mk.start(910+V.DQ.teaserDurationMs))}},XvY=function(r,V){r.V.Hp?(V=new Fv([0,
r.X.scrollTop],[0,V.K7.offsetTop],600,uOf),r.context.S.listen(V,"animate",function(I){r.X.scrollTop=I.y}),r.context.S.listen(V,"finish",function(I){r.X.scrollTop=I.y}),V.play()):(r.V.Ok(!0),r.X.scrollTop=V.K7.offsetTop,r.V.Ok(!1))},ak=function(r){return r.G&&r.G.DQ?r.G.DQ:r.cards[0]&&r.cards[0].DQ?r.cards[0].DQ:null},yeo=function(r,V){return g.z6(r.cards,function(I){return I.DQ.id===V})},f6=function(r,V,I){qt.call(this,r,V);
this.annotation=I;this.isActive=!1},S$e=function(r){var V=r.annotation.data;
"start_ms"in V&&"end_ms"in V&&r.addCueRange(Number(V.start_ms),Number(V.end_ms),r.annotation.id,function(){r.show()},function(){r.hide()})},eE=function(r,V,I){f6.call(this,r,V,I);
this.X=null;this.L=!1;this.S=null;this.Y=!1;this.G=this.C=this.W=null},i9$=function(r,V){var I=I===void 0?0:I;
var d=ZrK(V).width;g.mZ(V,d);I=new Q3m(V,[d,V.offsetTop],[d-d-I,V.offsetTop],200,ms9);g.S(r,I);r.context.S.listen(I,"begin",function(){g.oI(V,!0)});
I.play()},mep=function(r,V){if(V.channel_name){var I=r.createElement({J:"div",
Yc:["iv-branding-context-name"],OE:V.channel_name}),d=r.createElement({J:"div",Yc:["iv-branding-context-subscribe"]}),a=V.standalone_subscribe_button_data;a&&(r.G=new g.PD(a.subscribeText,a.subscribeCount,a.unsubscribeText,a.unsubscribeCount,!!a.enabled,!!a.classic,V.channel_id,!!a.subscribed,a.feature,V.session_data.itct,r.context.T,!1),r.G.Xz(d));var f=r.createElement({J:"div",Yc:["iv-branding-context-subscribe-caret"]}),e=r.createElement({J:"div",Yc:["branding-context-container-inner"]});e.appendChild(f);
e.appendChild(I);e.appendChild(d);g.oI(e,!1);var n=r.createElement({J:"div",Yc:["branding-context-container-outer"]});n.appendChild(e);g.Be(n,"right",V.image_width+"px");g.In(r.YN(),n);r.S=new g.hz(function(){Uec(r,e,n)},500);
g.S(r,r.S);r.context.G.listen(r.YN(),"mouseover",function(){QO$(r,e,n,f,V.image_height)});
r.context.G.listen(r.YN(),"mouseout",function(){r.S.start()})}},QO$=function(r,V,I,d,a){r.S.stop();
if(!r.Y){var f=g.Pe(V);r.G||(V.style.width=g.QH(f.width,!0),I.style.width=g.QH(f.width,!0));g.Be(d,"top",f.height-Math.max(Math.min(f.height,a)/2+10,20)+"px");g.Be(d,"right","1px");r.Y=!0;g.oI(V,!0);r.W=new g.hz(function(){g.jN(this.YN(),"iv-branding-active")},0,r);
r.W.start()}},Uec=function(r,V,I){g.xS(r.YN(),"iv-branding-active");
r.C=new g.hz(function(){g.oI(V,!1);r.G||(I.style.width=g.QH(0,!0))},250);
r.C.start();r.Y=!1},ugY=function(r,V,I,d,a,f,e){this.G=r;
this.S=V;this.yH=I;this.videoData=d;this.logger=a;this.T=f;this.X=e},pvm=function(r,V,I){f6.call(this,r,V,I);
var d=this;this.j=this.isCollapsed=this.V=!1;this.C=5E3;this.X=this.S=this.G=this.Y=null;this.L=this.createElement({J:"div",Yc:["iv-promo-contents"]});this.W=new g.hz(function(){d.G.setAttribute("aria-hidden","true");g.oI(d.S,!1);g.oI(d.X,!0)},700,this);
g.S(this,this.W)},q$f=function(r){var V=r.annotation.data;
if(r.annotation.style==="cta")var I=6;else if(r.annotation.style==="video"||r.annotation.style==="playlist")I=7;r.C=V.collapsedelay_ms||r.C;var d=["iv-promo","iv-promo-inactive"];r.YN().setAttribute("aria-hidden","true");r.YN().setAttribute("aria-label","Promotion");r.YN().tabIndex=0;var a=r.annotation.fq(),f=V.image_url;if(f){var e=r.createElement({J:"div",Yc:["iv-promo-img","iv-click-target"]});f=r.createElement({J:"img",D:{src:f,"aria-hidden":"true"}});e.appendChild(f);V.video_duration&&!V.is_live?
(f=r.createElement({J:"span",Z:"iv-promo-video-duration",OE:V.video_duration}),e.appendChild(f)):V.playlist_length&&(f=r.createElement({J:"span",Z:"iv-promo-playlist-length",OE:V.playlist_length.toString()}),e.appendChild(f));a&&P0(r,e,a,r.annotation.id,V.session_data,void 0,I)}a?(f=r.createElement({J:"a",Z:"iv-promo-txt"}),g.kr(f,Qy(a)),r.G=f):r.G=r.createElement({J:"div",Z:"iv-promo-txt"});switch(r.annotation.style){case "cta":case "website":var n=r.createElement({J:"p",B:[{J:"strong",OE:V.text_line_1}]});
var D=r.createElement({J:"p",B:[{J:"span",Z:"iv-promo-link",OE:V.text_line_2}]});if(f=V.text_line_3){d.push("iv-promo-website-card-cta-redesign");var x=r.createElement({J:"button",Yc:["iv-promo-round-expand-icon","ytp-button"]});f=r.createElement({J:"button",Yc:["iv-button","iv-promo-button"],B:[{J:"span",Z:"iv-button-content",OE:f}]});var E=r.createElement({J:"div",Z:"iv-promo-button-container"});E.appendChild(f);a&&P0(r,r.YN(),a,r.annotation.id,V.session_data,void 0,I)}g.jN(r.G,"iv-click-target");
a&&P0(r,r.G,a,r.annotation.id,V.session_data,void 0,I);break;case "playlist":case "video":n=r.createElement({J:"p",B:[{J:"span",OE:V.text_line_1}]}),D=r.createElement({J:"p",B:[{J:"strong",OE:V.text_line_2}]}),V.is_live&&(n=D,D=r.createElement({J:"span",Yc:["yt-badge","iv-promo-badge-live"],OE:"LIVE NOW"})),g.jN(r.G,"iv-click-target"),a&&P0(r,r.G,a,r.annotation.id,V.session_data,void 0,I),d.push("iv-promo-video")}n&&r.G.appendChild(n);D&&r.G.appendChild(D);r.L.appendChild(r.G);E&&r.L.appendChild(E);
I=r.createElement({J:"div",Z:"iv-promo-actions"});r.X=r.createElement({J:"button",Yc:["iv-promo-expand","ytp-button"]});r.X.title="Expand";r.context.G.listen(r.X,"click",function(N){vVf(r,5E3,N)});
I.appendChild(r.X);g.oI(r.X,!1);r.context.G.listen(r.YN(),"mouseover",r.ac,r);r.context.G.listen(r.YN(),"mouseout",r.EM,r);r.context.G.listen(r.YN(),"touchend",function(N){vVf(r,5E3,N)});
r.S=r.createElement({J:"button",Yc:["iv-promo-close","ytp-button"]});r.S.title="Close";r.context.G.listen(r.S,"click",r.annotation.style==="cta"&&V.text_line_3?r.d8:r.jZ,r);I.appendChild(r.S);g.DX(r.YN(),d);e&&(g.In(r.YN(),e),x&&e.appendChild(x));g.In(r.YN(),r.L);g.In(r.YN(),I)},vVf=function(r,V,I){I.stopPropagation();
PT$(r);oVf(r,V);r.G.focus()},ksm=function(r){r.isCollapsed||r.j||r.Y||(g.jN(r.YN(),"iv-promo-collapsed"),r.isCollapsed=!0,r.W.start())},PT$=function(r){r.W.stop();
r.isCollapsed&&(g.E8(r.YN(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),r.isCollapsed=!1,r.G&&r.G.removeAttribute("aria-hidden"),g.oI(r.X,!1),g.oI(r.S,!0))},oVf=function(r,V){r.Y||(r.Y=g.gS(function(){hlo(this);
ksm(this)},V,r))},hlo=function(r){r.Y&&(g.vr.clearTimeout(r.Y),r.Y=null)},rHo=function(r){this.T=r},Gsp=function(r,V,I){V&&(I?YK(r,V.map(function(d){return g.Lm(d,I)})):YK(r,V))},YK=function(r,V,I,d){var a=1,f=void 0,e=-1;
if(I){var n=!1;f=function(){a--;a||n||(clearTimeout(e),n=!0,I())};
e=setTimeout(function(){n=!0;I()},1E3)}V=g.H(V||[]);
for(var D=V.next();!D.done;D=V.next())D=D.value,a++,g.mn(D,f);d&&(a++,d!==0&&r.T.sendVideoStatsEngageEvent(d,f))},Va$=function(r){g.zu.call(this,r);
var V=this;this.QH=this.j=!1;this.loadNumber=0;this.C={};this.logger=new rHo(this.player);this.Y=new g.Su(this);this.W=this.L=null;this.events=new g.Su(this);this.qY=this.V=this.G=null;this.kc=[];g.S(this,this.Y);this.Y.K(this.player,"onVideoAreaChange",function(){V.publish("onVideoAreaChange")});
this.Y.K(this.player,"onHideControls",function(){V.publish("onHideControls")});
this.Y.K(this.player,"onShowControls",function(){V.publish("onShowControls")});
this.Y.K(this.player,"resize",function(d){V.publish("resize",d)});
this.Y.K(this.player,"presentingplayerstatechange",function(d){V.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.E7,this);this.subscribe("resize",this.QA,this);this.player.N().R7.subscribe("vast_info_card_add",this.hM,this);g.S(this,this.events);this.bL=this.createElement({J:"div",Z:"video-custom-annotations"});this.X=new g.u({J:"div",Yc:["ytp-player-content","ytp-iv-player-content"]});g.S(this,this.X);g.g1(this.player,this.X.element,4);this.X.hide();this.S=new g.u({J:"div",Yc:["ytp-iv-video-content"]});g.S(this,this.S);r=this.createElement({J:"div",Z:"video-annotations"});
r.appendChild(this.bL);this.S.element.appendChild(r);this.Tl()&&this.load();var I=this.createElement({J:"style"});(g.mQ("HEAD")[0]||document.body).appendChild(I);this.addOnDisposeCallback(function(){g.fy(I)});
if(r=I.sheet)r.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),r.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),r.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),r.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),r.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),r.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),r.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),r.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),r.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),r.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},ISf=function(r){r=r.createElement({J:"div",
Yc:["annotation","annotation-type-custom"]});g.oI(r,!1);return r},d6P=function(r,V){V=!V.isCued()&&!g.v(V,1024);
r.X.Ok(V);r.S.Ok(V)},aSY=function(r,V,I){r.j=!0;
r.W=g.yr(V,I)},fSm=function(r,V){for(var I={},d=g.H(V.attributes),a=d.next();!a.done;a=d.next())a=a.value,I[a.name]=a.nodeValue;
for(d=0;d<V.childNodes.length;d++)if(a=V.childNodes[d],g.Vc(a)&&a.nodeType==1){if(I[a.tagName])var f=I[a.tagName];else if(a.tagName==="data"){a.childNodes.length>0&&(f=a.childNodes[0].nodeValue,I[a.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],I[a.tagName]=f;a&&a.tagName==="TEXT"?a.childNodes.length===1&&a.childNodes[0].nodeType===3?f.push(a.childNodes[0].nodeValue):f.push(""):a&&f.push(fSm(r,a))}return I},jrf=function(r){var V=g.J(r.player.getVideoData());
if(V.Ws){var I=r.player.N().R7.get(V.videoId);if(I){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(a,f,e){a=r.loadNumber;f=V.videoId;r.loaded&&r.loadNumber===a&&r.player.getVideoData().videoId===f&&(e=g.C5(e)&&e.responseXML?e.responseXML:null)&&ecc(r,e)}};
g.fH()&&(d.onFinish=Y59(r,d.onFinish));d.postParams={ic_only:"1"};noP(d,I);r.j=!0;g.yr(V.Ws,d)}}},noP=function(r,V){r.method="POST";
r.postParams=r.postParams||{};V.HA&&(r.postParams.ic_coll=V.HA);V.jD&&(r.postParams.ic_xml=V.jD);V.sJ&&(r.postParams.ic_track=V.sJ)},D6$=function(r){var V=new g.u({J:"div"});
g.oI(V.element,!1);var I=new Kv$(r.player,V.element,n6(r));g.S(I,V);V.Xz(r.X.element);I.yk();return I},Eom=function(r,V){var I,d;
if(V=(I=V.getWatchNextResponse())==null?void 0:(d=I.cards)==null?void 0:d.cardCollectionRenderer)r.QH=!0,x6_(r,V),V.headerText&&r.qY&&(I=g.wF(V.headerText),r.qY.setAttribute("title",I))},n6=function(r){if(!r.V){var V=new pom(r);
g.S(r,V);var I=new g.T9(r);g.S(r,I);r.V=new ugY(V,I,r.player.N(),r.player.getVideoData(),r.logger,r.player,r.Ja)}return r.V},ecc=function(r,V){var I=!1,d=V.getElementsByTagName("annotations");
if(d&&!(d.length<1)&&(d=d[0].getAttribute("itct"))){var a=g.A8();if(a){var f=g.yo();f&&g.I6(g.o9)(void 0,a,f,[g.R9(d)])}}V=V.getElementsByTagName("annotation");for(d=0;d<V.length;d++){f=fSm(r,V[d]);a=null;try{if(f){var e=f.id,n=/.+/;var D=typeof e==="string"&&n!=null&&e!=null&&e.match(n)?e:"";var x=UZ(f.type,NZo),E=UZ(f.style,srf),N=jOo(f.data),c=N.length!==0?JSON.parse(N):{};var z=f.action;f=ce6;if(z==null)var M=null;else if(g.rP(z)){n=[];for(var w=g.H(z),b=w.next();!b.done;b=w.next()){var W=f(b.value);
W&&n.push(W)}M=n}else{var K=f(z);M=K?[K]:[]}a=D&&x?new zlP(D,x,E,M,c):null}else a=null}catch(dA){}if(a)if(a.type==="branding"||a.type==="promotion"){f=r;n=a;var F=ISf(f),l=null;switch(n.type){case "branding":if(f.player.N().NJ)break;f.X.element.appendChild(F);l=new eE(F,n6(f),n);break;case "promotion":g.g1(f.player,F,4),l=new pvm(F,n6(f),n)}l&&l.yk();if(f=l)g.S(r,f),r.C[a.id]=f}else if(a.type==="card"||a.type==="drawer"){r.G||(r.G=D6$(r),g.S(r,r.G));if(a.type==="card"){F=r.G;var B=(I=a)&&I.data&&
I.data.card_type;a=I.data;if(B)switch(f=a.tracking||{},f={HM:f.impression,click:f.click,close:f.close,rO:f.teaser_impression,Ki:f.teaser_click},n=a.tracking_params||{},l=null,B){case "collaborator":I={id:I.id,timestamp:a.timestamp||0,type:a.card_type,teaserText:a.teaser_text,teaserDurationMs:a.teaser_duration_ms,startMs:a.start_ms,autoOpen:a.auto_open||!1,sessionData:a.session_data||{},sponsored:a.sponsored||!1,JK:f,qR:n.card?g.R9(n.card):null,HO:n.teaser?g.R9(n.teaser):null,lI:n.icon?g.R9(n.icon):
null,channelId:a.channel_id,customMessage:a.custom_message?a.custom_message:null,profileImageUrl:a.image_url,title:a.title,metaInfo:a.meta_info,url:mC({pause_on_navigation:a.pause_on_navigation,target:a.target||"new",value:a.url}),onClickCommand:null};rO(F,I);break;case "playlist":I={id:I.id,timestamp:a.timestamp||0,type:a.card_type,teaserText:a.teaser_text,teaserDurationMs:a.teaser_duration_ms,startMs:a.start_ms,autoOpen:a.auto_open||!1,sessionData:a.session_data||{},sponsored:a.sponsored||!1,JK:f,
qR:n.card?g.R9(n.card):null,HO:n.teaser?g.R9(n.teaser):null,lI:n.icon?g.R9(n.icon):null,pE:a.image_url,playlistVideoCount:a.playlist_video_count,customMessage:a.custom_message?a.custom_message:null,title:a.title,metaInfo:a.meta_info,url:g.J(mC({pause_on_navigation:a.pause_on_navigation,target:a.target||"new",value:a.url})),onClickCommand:null};rO(F,I);break;case "productListing":a.signin_url&&(l=mC({target:"current",value:a.signin_url}));B=[];for(var P=a.offers||[],p=0;p<P.length;p++)B.push(new b9f(g.Hz(P[p].merchant),
g.Hz(P[p].price)));I={id:I.id,timestamp:a.timestamp||0,type:a.card_type,teaserText:a.teaser_text,teaserDurationMs:a.teaser_duration_ms,startMs:a.start_ms,autoOpen:a.auto_open||!1,sessionData:a.session_data||{},sponsored:a.sponsored||!1,JK:f,qR:n.card?g.R9(n.card):null,HO:n.teaser?g.R9(n.teaser):null,lI:n.icon?g.R9(n.icon):null,imageUrl:a.image_url,displayDomain:a.display_domain?a.display_domain:null,showLinkIcon:!!a.show_link_icon,ox:a.button_icon_url?a.button_icon_url:null,title:a.title,customMessage:a.custom_message?
a.custom_message:null,url:g.J(mC({pause_on_navigation:a.pause_on_navigation,target:a.target||"new",value:a.url})),cCM:l,ass:a.signin_title?a.signin_title:void 0,Ez0:a.signin_message?a.signin_message:void 0,offers:B,onClickCommand:null};rO(F,I);break;case "simple":I={id:I.id,timestamp:a.timestamp||0,type:a.card_type,teaserText:a.teaser_text,teaserDurationMs:a.teaser_duration_ms,startMs:a.start_ms,autoOpen:a.auto_open||!1,sessionData:a.session_data||{},sponsored:a.sponsored||!1,JK:f,qR:n.card?g.R9(n.card):
null,HO:n.teaser?g.R9(n.teaser):null,lI:n.icon?g.R9(n.icon):null,imageUrl:a.image_url,displayDomain:a.display_domain?a.display_domain:null,showLinkIcon:!!a.show_link_icon,ox:a.button_icon_url?a.button_icon_url:null,title:a.title,customMessage:a.custom_message?a.custom_message:null,url:g.J(mC({pause_on_navigation:a.pause_on_navigation,target:a.target||"new",value:a.url})),onClickCommand:null};rO(F,I);break;case "video":I={id:I.id,timestamp:a.timestamp||0,type:a.card_type,teaserText:a.teaser_text,teaserDurationMs:a.teaser_duration_ms,
startMs:a.start_ms,autoOpen:a.auto_open||!1,sessionData:a.session_data||{},sponsored:a.sponsored||!1,JK:f,qR:n.card?g.R9(n.card):null,HO:n.teaser?g.R9(n.teaser):null,lI:n.icon?g.R9(n.icon):null,pE:a.image_url,videoDuration:a.video_duration||null,customMessage:a.custom_message?a.custom_message:null,title:a.title,metaInfo:a.meta_info,isLiveNow:!!a.is_live_now,url:g.J(mC({pause_on_navigation:a.pause_on_navigation,target:a.target||"new",value:a.url})),onClickCommand:null},rO(F,I)}}else Rlo(r.G,a);I=!0}}I&&
(RR(r.player),r.QA())},x6_=function(r,V){var I=!1;
r.G||(r.G=D6$(r),g.S(r,r.G));for(var d=g.H(V.cards||[]),a=d.next();!a.done;a=d.next())a=a.value,a.cardRenderer&&(tzG(r.G,a.cardRenderer),I=!0);if(I){var f;(f=r.player.getVideoData())!=null&&g.Zd(f)||(I=r.G,d=V.headerText?g.wF(V.headerText):"",g.Yx(I.Qa,d),I.j&&I.j.setAttribute("title",d),I.context.videoData.eventId&&(I.eventId=I.context.videoData.eventId),I.n8=V.trackingParams?g.R9(V.trackingParams):null,I.L=V.closeButton.infoCardIconRenderer.trackingParams?g.R9(V.closeButton.infoCardIconRenderer.trackingParams):
null,I.lI=V.icon.infoCardIconRenderer.trackingParams?g.R9(V.icon.infoCardIconRenderer.trackingParams):null,r.QA());RR(r.player)}},cHc=function(r,V,I,d,a){if(!r.player.N().NJ){var f=[];
V.navigationEndpoint&&g.U(V.navigationEndpoint,g.yW)&&g.U(V.navigationEndpoint,g.yW).browseId&&f.push(new EV6("openUrl","click",new De6("/channel/"+g.U(V.navigationEndpoint,g.yW).browseId,"new",!0,!0)));var e=V.watermark.thumbnails[0];d={channel_name:V.channelName,end_ms:V.endTimeMs,image_height:e.height,image_type:1,image_url:e.url,image_width:e.width,is_mobile:!1,session_data:{annotation_id:I,ei:a,feature:"iv",itct:V.trackingParams,src_vid:d},start_ms:V.startTimeMs};if(V.subscribeButton&&g.U(V.subscribeButton,
g.AR)){d.channel_id=g.U(V.subscribeButton,g.AR).channelId;var n;V=g.U(V.subscribeButton,g.AR);e=a=null;V.subscribed?(V.subscriberCountWithUnsubscribeText&&(a=g.wF(V.subscriberCountWithUnsubscribeText)),V.subscriberCountText&&(e=g.wF(V.subscriberCountText))):(V.subscriberCountText&&(a=g.wF(V.subscriberCountText)),V.subscriberCountWithSubscribeText&&(e=g.wF(V.subscriberCountWithSubscribeText)));var D,x=((D=g.U((n=V.signInEndpoint)==null?void 0:n.commandMetadata,g.Hj))==null?void 0:D.url)||"";n={subscribeText:g.wF(V.unsubscribedButtonText),
subscribeCount:a||"",unsubscribeText:g.wF(V.subscribedButtonText),unsubscribeCount:e||"",enabled:V.enabled||!1,classic:!1,subscribed:V.subscribed||!1,feature:"iv",signInUrl:x};d.standalone_subscribe_button_data=n}f=new zlP(I,"branding","branding",f,d);n=ISf(r);r.X.element.appendChild(n);f=new eE(n,n6(r),f);f.yk();g.S(f,f);r.C[I]=f}},Y59=function(r,V){return function(){var I=g.ZU.apply(0,arguments);
r.h0()||r.kc.push(g.Qa.Dm(function(){V.apply(null,g.R(I))}))}},zcY=function(r){return r==="annotation-editor"||r==="live-dashboard"};
g.Gm.prototype.qF=g.ei(45,function(r,V){var I=g.AW(this.Gz());I&&I.qF(r,V)});
var yy={},A9=null;g.Dm(Fv,g.s8);g.C=Fv.prototype;g.C.getDuration=function(){return this.duration};
g.C.play=function(r){if(r||this.G==0)this.progress=0,this.coords=this.X;else if(this.isPlaying())return!1;G7(this);this.startTime=r=g.Yf();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.Y=this.startTime;this.progress||this.Ez();this.EX("play");this.isPaused()&&this.EX("resume");this.G=1;var V=g.dP(this);V in yy||(yy[V]=this);gq9();SDK(this,r);return!0};
g.C.stop=function(r){G7(this);this.G=0;r&&(this.progress=1);irp(this,this.progress);this.onStop();this.uj()};
g.C.pause=function(){this.isPlaying()&&(G7(this),this.G=-1,this.EX("pause"))};
g.C.eC=function(){this.G==0||this.stop(!1);this.EX("destroy");Fv.m9.eC.call(this)};
g.C.destroy=function(){this.dispose()};
g.C.nI=function(){this.EX("animate")};
g.C.EX=function(r){this.dispatchEvent(new UsK(r,this))};
g.Dm(UsK,g.kI);g.Dm(lq,Fv);lq.prototype.S=function(){};
lq.prototype.nI=function(){this.S();lq.m9.nI.call(this)};
lq.prototype.uj=function(){this.S();lq.m9.uj.call(this)};
lq.prototype.Ez=function(){this.S();lq.m9.Ez.call(this)};
g.Dm(Q3m,lq);Q3m.prototype.S=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.T(pom,g.X);g.C=pom.prototype;g.C.listen=function(r,V,I,d){I=(0,g.aG)(I,d||this.X);r=g.Ko(r,V,I);this.G.push(r);return r};
g.C.Su=function(r,V,I,d){I=(0,g.aG)(I,d||this.X);r=Xo6(r,V,I);this.G.push(r);return r};
g.C.pF=function(r){g.Rx(r);g.H9(this.G,r)};
g.C.removeAll=function(){g.Rx(this.G);this.G.length=0};
g.C.eC=function(){this.removeAll();g.X.prototype.eC.call(this)};g.T(P0G,g.zu);g.C=P0G.prototype;g.C.load=function(){g.zu.prototype.load.call(this);if(!ZN(this)){var r=g.N_j(this.player.getVideoData());r?(r=qDK(r,oqm(this)),Xv(this,r,!1)):kBe(this)}};
g.C.unload=function(){Xv(this,null);this.Y&&(this.Y.abort(),this.Y=null);g.zu.prototype.unload.call(this)};
g.C.Ha=function(r,V){return ZN(this)?r==="loadCustomEndscreenRenderer"?(r=qDK(V,"new"),Xv(this,r),!0):null:null};
g.C.getOptions=function(){return ZN(this)?["loadCustomEndscreenRenderer"]:[]};
g.C.yy=function(){if(this.endscreen&&this.endscreen.elements){var r=this.player.getVideoContentRect();if(r&&r.width!==0&&r.height!==0){var V=this.player.getPlayerSize();if(V&&V.width!==0&&V.height!==0){var I=r.width/r.height;var d=0;for(var a=-1,f=0;f<Ma_.length;f++){var e=Math.abs(V.width-Ma_[f]);if(a===-1||d>=e)a=f,d=e}d=Cr6[a];this.S&&g.Be(this.S.element,"outline-width",Math.max(V.width,V.height)+"px");for(V=0;V<this.endscreen.elements.length;++V)if(f=this.endscreen.elements[V].id,a=this.X[f],
e=this.C[f],a&&e){var n=e.width*I/e.aspectRatio,D=Math.round(e.width*r.width);f=Math.round(n*r.height);var x=r.left+Math.round(e.left*r.width),E=r.top+Math.round(e.top*r.height);g.qG(a.element,D,f);g.mZ(a.element,x,E);g.E8(a.element,TZc);D>256||f>256?g.jN(a.element,"ytp-ce-large-round"):D>96||f>96?g.jN(a.element,"ytp-ce-medium-round"):g.jN(a.element,"ytp-ce-small-round");g.E8(a.element,HEc);D=e.left+e.width/2;e=e.top+n/2;g.jN(a.element,D<=.5&&e<=.5?"ytp-ce-top-left-quad":D>.5&&e<=.5?"ytp-ce-top-right-quad":
D<=.5&&e>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.E8(a.element,Cr6);g.jN(a.element,d);(a=g.pJ(document,"div","ytp-ce-expanding-overlay-body",a.element)[0])&&g.Be(a,"height",f+"px")}}}}};
g.C.onCueRangeEnter=function(r){if(this.endscreen)if(r.getId()==="ytp-ce-in-endscreen")iq(this,this.endscreen.impressionUrls),(r=g.A8())&&this.endscreen.visualElement&&g.Y5(r,this.endscreen.visualElement),this.G&&(g.jN(this.G,"ytp-ce-element-show"),this.G.removeAttribute("aria-hidden"),this.player.Y_()?g.jN(this.G,"ytp-ce-hide-button-lower"):g.xS(this.G,"ytp-ce-hide-button-lower"));else{r=r.getId().substring(15);var V=this.X[r],I=this.C[r];g.jN(V.element,"ytp-ce-element-show");V.element.removeAttribute("aria-hidden");
V=this.player.getRootNode();g.jN(V,"ytp-ce-shown");iq(this,I.impressionUrls);(V=g.A8())&&g.Y5(V,I.visualElement);this.player.N().j&&this.player.Bs("endscreenelementshown",r)}};
g.C.onCueRangeExit=function(r){if(r.getId()==="ytp-ce-in-endscreen")this.G&&(g.xS(this.G,"ytp-ce-element-show"),this.G.setAttribute("aria-hidden","true"));else{r=r.getId().substring(15);var V=this.X[r];g.xS(V.element,"ytp-ce-element-show");V.element.setAttribute("aria-hidden","true");V=this.player.getRootNode();g.xS(V,"ytp-ce-shown");this.player.N().j&&this.player.Bs("endscreenelementhidden",r)}};
g.C.pKs=function(r){var V=this;r.target===window&&(new g.hz(function(){for(var I=g.H(Object.values(V.X)),d=I.next();!d.done;d=I.next())g.E8(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.C.Ok=function(r){for(var V=g.H(Object.values(this.X)),I=V.next();!I.done;I=V.next())I=I.value,r?I.element.setAttribute("hidden",""):I.element.removeAttribute("hidden")};
g.C.aDC=function(r){this.G&&this.player.getRootNode().removeChild(this.G);r&&(g.jN(r,"ytp-ce-hide-button-container"),this.G=r,g.g1(this.player,this.G,4))};
var Ma_=[346,426,470,506,570,640,853,1280,1920],Cr6="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),HEc=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],TZc=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var xeP={gQE:"current",WVs:"new"};var NJo={CLOSE:"close",jH0:"openUrl",SUBSCRIBE:"subscribe"},sOY={fa0:"click",CLOSE:"close",PhH:"hidden",tUz:"rollOut",hKs:"rollOver",KFs:"shown"};zlP.prototype.fq=function(){var r=Mzo(this,function(V){return V.type==="openUrl"&&V.url!=null});
return r?r.url:null};
var srf={ams:"anchored",tD:"branding",CHANNEL:"channel",iML:"cta",HeC:"highlightText",aqc:"label",PLAYLIST:"playlist",POPUP:"popup",cOE:"speech",SUBSCRIBE:"subscribe",l$C:"title",VIDEO:"video",d$M:"website"},NZo={tD:"branding",Yo7:"card",wOs:"drawer",lq8:"highlight",eYk:"marker",Q0M:"promotion",TEXT:"text",qiL:"widget"};g.T(qt,g.X);g.C=qt.prototype;g.C.addCueRange=function(r,V,I,d,a){r=new g.ex(r,V,{id:I,namespace:"annotations_module"});d&&this.L8.set(r,d);a&&this.EE.set(r,a);this.context.T.Dg([r],1)};
g.C.yk=function(){this.context.X.subscribe("resize",this.Dz,this)};
g.C.YN=function(){return this.element};
g.C.Sy=function(r,V,I,d,a,f){if(this.DM)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(r,I,d,a);return!1};
g.C.show=function(){};
g.C.hide=function(){};
g.C.destroy=function(){g.fy(this.YN())};
g.C.Dz=function(){};
g.C.navigate=function(r,V,I,d){var a=this,f=Qy(r);if(f){var e=WvP(f,r.target),n=function(){r.G&&a.context.T.pauseVideo();var D=a.context.videoData.Mm||!1,x=g.n5(f||"");D&&x&&(x.v||x.list)?a.context.T.hO(x.v,V,x.list,!1):g.vC(f||"",e==="current"?"_top":void 0,V)};
e==="new"&&(n(),n=null);YK(this.context.logger,I,n,d);O9c(f)||(I=g.A8(),d=V.itct,I&&d&&g.Du(I,g.R9(d)))}};
g.C.eC=function(){this.L8.clear();this.EE.clear();g.X.prototype.eC.call(this)};
g.C.createElement=function(r){r=new g.u(r);g.S(this,r);return r.element};g.T(Kv$,qt);g.C=Kv$.prototype;g.C.xg=function(){this.kc&&rO(this,this.kc)};
g.C.isAvailable=function(){var r;if(r=!!this.cards.length)(r=this.T.getRootNode())?(r=g.Pe(r),r=173<r.width&&173<r.height):r=!1;return r};
g.C.Dz=function(){var r=this.isAvailable();g.oI(this.YN(),r);g.NA(this.context.T.getRootNode(),g.IC.IV_DRAWER_ENABLED,r);RR(this.T)};
g.C.destroy=function(){this.T.qF(!1);try{this.T.getRootNode().removeChild(this.Y)}catch(r){}g.Dj(this.QH);g.lQ(this.TQ);this.Ws&&this.Ws.dispose();this.W&&this.W.dispose();qt.prototype.destroy.call(this)};
g.C.Zz=function(){var r=this;this.context.G.listen(g.vz("iv-drawer-close-button",this.Y),"click",this.sT,this);this.context.G.listen(this.X,"touchend",function(){r.GQ.start()});
this.context.G.listen(this.X,"scroll",this.He,this);this.context.X.subscribe("onHideControls",function(){r.p8=!0});
this.context.X.subscribe("onShowControls",function(){r.p8=!1});
this.context.X.subscribe("onVideoAreaChange",function(){r.p8=g.nL(r.T.getRootNode(),"ytp-autohide")});
this.QH.push(g.jl("iv-button-shown",this.i8C,this));this.QH.push(g.jl("iv-button-hidden",this.A0H,this));l8G(this)};
g.C.findLastIndex=function(r){if(this.cards.length===0)return 0;var V=g.Mm(this.cards,function(I){return r.DQ.startMs>I.DQ.startMs||r.DQ.startMs===I.DQ.startMs&&r.DQ.timestamp>=I.DQ.timestamp?!0:!1});
return V===-1?0:V+1};
g.C.sT=function(){if(this.S){YK(this.context.logger,ak(this).JK.close);var r=g.A8();r&&this.L&&g.Du(r,this.L);h9(this)}};
g.C.He=function(){g.NA(this.Y,"iv-drawer-scrolled",this.X.scrollTop>0)};
g.C.i8C=function(){var r=g.A8(),V=ak(this);V=V?V.lI:this.lI;r&&V&&g.nB(r,[V])};
g.C.A0H=function(){var r=g.A8(),V=ak(this);V=V?V.lI:this.lI;r&&V&&g.jA(r,[V])};
g.C.u1=function(){var r=ak(this);YK(this.context.logger,r.JK.rO);var V=g.A8();if(V&&r)if(this.T.U("web_infocards_teaser_show_logging_fix")){var I=[];r.HO&&I.push(r.HO);r.lI&&I.push(r.lI);I.length>0&&g.nB(V,I)}else g.nB(V,[r.HO,r.lI])};
g.C.gc8=function(){var r=g.A8(),V=ak(this);r&&V&&g.jA(r,[V.HO])};
g.C.Ni=function(r){var V=ak(this),I=g.A8();this.G?r?(r=this.context.logger,YK(r,V.JK.Ki),r.T.sendVideoStatsEngageEvent(4,void 0),I&&V.HO&&g.Du(I,V.HO)):(r=this.context.logger,YK(r,V.JK.Ki),r.T.sendVideoStatsEngageEvent(4,void 0),I&&V.lI&&g.Du(I,V.lI)):(r=this.context.logger,YK(r,V.JK.Ki),r.T.sendVideoStatsEngageEvent(4,void 0),I&&this.lI&&g.Du(I,this.lI))};g.T(f6,qt);f6.prototype.yk=function(){qt.prototype.yk.call(this);S$e(this)};
f6.prototype.show=function(){qt.prototype.show.call(this);var r=g.A8(),V=this.annotation.data;r&&V&&(V=V.session_data)&&g.nB(r,[g.R9(V.itct)])};
f6.prototype.hide=function(){qt.prototype.hide.call(this);var r=g.A8(),V=this.annotation.data;r&&V&&(V=V.session_data)&&g.jA(r,[g.R9(V.itct)])};g.T(eE,f6);
eE.prototype.show=function(){if(!this.isActive){f6.prototype.show.call(this);if(!this.L){g.jN(this.YN(),"iv-branding");var r=this.annotation.data;this.X=this.createElement({J:"img",Yc:["branding-img","iv-click-target"],D:{"aria-label":"Channel watermark",src:r.image_url,width:r.image_width,height:r.image_height}});g.oI(this.X,!1);var V=this.createElement({J:"button",Yc:["branding-img-container","ytp-button"]});V.appendChild(this.X);this.YN().appendChild(V);var I=this.annotation.fq();I&&P0(this,V,
I,this.annotation.id,r.session_data);this.context.T.U("disable_branding_context")||mep(this,r);this.L=!0}g.oI(this.YN(),!0);this.isActive=!0;if(this.X){try{i9$(this,this.X)}catch(d){}g.jN(this.context.T.getRootNode(),"ytp-branding-shown");this.context.T.getRootNode().style.setProperty("--branding-image-width",this.X.getAttribute("width")+"px")}}};
eE.prototype.hide=function(){this.isActive&&(f6.prototype.hide.call(this),g.oI(this.YN(),!1),this.isActive=!1,g.xS(this.context.T.getRootNode(),"ytp-branding-shown"))};
eE.prototype.destroy=function(){this.G&&(this.G.dispose(),this.G=null);g.xS(this.context.T.getRootNode(),"ytp-branding-shown");f6.prototype.destroy.call(this)};g.T(pvm,f6);g.C=pvm.prototype;g.C.show=function(){this.isActive||(f6.prototype.show.call(this),this.V||(q$f(this),this.V=!0),g.oI(this.YN(),!0),g.gS(function(){g.xS(this.YN(),"iv-promo-inactive")},100,this),this.YN().removeAttribute("aria-hidden"),this.isActive=!0,hlo(this),PT$(this),oVf(this,this.C))};
g.C.hide=function(){this.isActive&&(g.jN(this.YN(),"iv-promo-inactive"),this.isActive=!1,this.YN().setAttribute("aria-hidden","true"))};
g.C.Sy=function(r,V,I,d,a,f){return this.isCollapsed?!1:f6.prototype.Sy.call(this,r,V,I,d,a,f)};
g.C.ac=function(r){this.j=!0;vVf(this,500,r)};
g.C.EM=function(){this.j=!1;ksm(this)};
g.C.jZ=function(r){r.stopPropagation();this.hide()};
g.C.d8=function(r){r.stopPropagation();hlo(this);this.isCollapsed=!0;g.jN(this.YN(),"iv-promo-collapsed-no-delay");this.W.start()};
g.C.destroy=function(){this.W.dispose();f6.prototype.destroy.call(this)};g.T(Va$,g.zu);g.C=Va$.prototype;g.C.Ha=function(r,V){if(!zcY(this.player.N().playerStyle))return null;switch(r){case "loadCustomAnnotationsXml":return(r=g.P$(V))&&ecc(this,r),!0;case "removeCustomAnnotationById":return V&&this.G&&(AeG(this.G,V),RR(this.player)),!0}return null};
g.C.getOptions=function(){return zcY(this.player.N().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.C.Tl=function(){var r=this.player.N(),V=g.J(this.player.getVideoData()),I=r.annotationsLoadPolicy||V.annotationsLoadPolicy;return g.V_(V)||this.player.isMutedByEmbedsMutedAutoplay()?!1:I===1&&!V.QI||r.R7.get(V.videoId)||g.X8(V)||g.Bx(V)?!0:!1};
g.C.QA=function(){if(this.S){var r=this.player.gs().getVideoContentRect(!0);g.qG(this.S.element,r.width,r.height);g.mZ(this.S.element,r.left,r.top)}if(this.G){var V=this.player.gL();r=this.G;V=V.width;g.NA(r.Y,"iv-drawer-small",V<=426);g.NA(r.Y,"iv-drawer-big",V>=1280)}};
g.C.E7=function(r){d6P(this,r.state);g.v(r.state,2)&&(this.Y_()&&this.Fc()&&this.player.getPresentingPlayerType()!==2&&this.n5(!1),this.qF(!1))};
g.C.load=function(){function r(e){var n=V.loadNumber;V.W=null;V.loaded&&V.loadNumber===n&&V.player.getVideoData().videoId===d&&(e=g.C5(e)&&e.responseXML?e.responseXML:null)&&(ecc(V,e),g.jN(V.player.getRootNode(),"iv-module-loaded"))}
var V=this;g.zu.prototype.load.call(this);d6P(this,this.player.getPlayerStateObject());this.loadNumber++;var I=g.J(this.player.getVideoData()),d=I.videoId;g.fH()&&(r=Y59(this,r));var a={format:"XML",onFinish:r,onError:function(){V.W=null},
urlParams:{}};I.isPharma&&(a.urlParams.pharma="1");a.method="POST";a.withCredentials=!0;var f=this.player.N().R7.get(d);f&&noP(a,f);f=f&&(f.jD||f.HA);if(!I.M8||f)I.Ws?aSY(this,I.Ws,a):(this.L=function(){if(!V.j)V.onVideoDataChange(a);var e=g.J(V.player.getVideoData());(e==null?0:g.Zd(e))&&!V.QH&&Eom(V,e)},this.player.addEventListener("videodatachange",this.L));
g.g1(this.player,this.S.element,4);this.QA();(f=g.X8(I))&&x6_(this,f);(f=g.Bx(I))&&f.featuredChannel&&cHc(this,f.featuredChannel,f.annotationId||"branding",I.videoId||null,I.eventId||null);this.qY=g.vz("ytp-cards-button",this.player.getRootNode());g.Zd(I)&&Eom(this,I)};
g.C.onVideoDataChange=function(r){var V=g.J(this.player.getVideoData());V.Ws&&aSY(this,V.Ws,r)};
g.C.unload=function(){this.player.Zg("annotations_module");for(var r=g.H(Object.keys(this.C)),V=r.next();!V.done;V=r.next())this.C[V.value].destroy();this.V=null;this.G&&(this.G.destroy(),this.G=null,RR(this.player));this.j=!1;this.W&&(this.W.abort(),this.W=null);this.QH=!1;this.C={};this.X.hide();g.zu.prototype.unload.call(this);this.S.detach();this.L&&(this.player.removeEventListener("videodatachange",this.L),this.L=null)};
g.C.hM=function(r){r===this.player.getVideoData().videoId&&(this.loaded?jrf(this):this.load())};
g.C.Y_=function(){var r;return((r=this.G)==null?void 0:r.isAvailable())||this.QH};
g.C.Fc=function(){return!!this.G&&this.G.S};
g.C.n5=function(r,V,I){V=V===void 0?!1:V;this.Y_();this.G&&(r?I?kF(this.G,I,V):kF(this.G,"YOUTUBE_DRAWER_AUTO_OPEN",V):h9(this.G))};
g.C.qF=function(r,V){this.player.publish(r?"cardsteasershow":"cardsteaserhide",V)};
g.C.eC=function(){this.player.N().R7.unsubscribe("vast_info_card_add",this.hM,this);g.xS(this.player.getRootNode(),g.IC.IV_DRAWER_OPEN);for(var r=this.kc,V=g.Qa,I=0,d=r.length;I<d;I++)V.hR(r[I]);this.kc.length=0;g.zu.prototype.eC.call(this)};
g.C.createElement=function(r){r=new g.u(r);g.S(this,r);return r.element};g.cD("annotations_module",Va$);g.cD("creatorendscreen",P0G);})(_yt_player);
