(function(g){var window=this;'use strict';var OEP=function(r,V,I){g.L(function(d){r.G=g.yr(V,I);g.Hr(d)})},jE=function(r){r.isActive()||r.start()},WU9=function(r,V){return V?r.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},$6e=function(r){return g.VO(r)||r.U("web_enable_caption_language_preference_stickiness")},KUG=function(r,V){var I=new g.Ci;
I.languageCode=r.languageCode;I.languageName=r.languageName;I.name=r.name;I.displayName=r.displayName;I.kind=r.kind;I.isDefault=!1;I.G=r.G;I.isTranslateable=r.isTranslateable;I.vssId=r.vssId;I.url=r.url;I.translationLanguage=V;r.xtags&&(I.xtags=r.xtags);r.captionId&&(I.captionId=r.captionId);return I},Rco=function(r,V){var I,d,a;
return g.L(function(f){if(f.X==1)return I=r+"|"+V,g.G(f,g.I1(),2);if(f.X!=3){d=f.G;if(!d)throw g.KH("gct");return g.G(f,g.Zb(d),3)}a=f.G;return f.return(a.get("captions",I))})},taG=function(r,V,I){Rco(r,V).then(function(d){d&&I(d.trackData,new g.Ci(d.metadata))})},GYm=function(r){if(!yHP.test(r))throw Error("'"+r+"' is not a valid hex color");
r.length==4&&(r=r.replace(AHK,"#$1$1$2$2$3$3"));r=r.toLowerCase();r=parseInt(r.slice(1),16);return[r>>16,r>>8&255,r&255]},FUc=function(){var r=void 0;
r=r===void 0?{}:r;var V="suggest_correction"in g.VGe?g.VGe.suggest_correction:"Edit caption";V=V||"";var I={},d;for(d in r){I={Or:I.Or};I.Or=d;var a=function(f){return function(){return String(r[f.Or])}}(I);
V=V.replace(new RegExp("\\$\\{"+I.Or+"\\}","gi"),a);V=V.replace(new RegExp("\\$"+I.Or,"gi"),a)}return V},lSo=function(){return g.BJ("yt-player-caption-display-settings")},DM=function(){this.segments=[]},LUP=function(r,V){var I=g.Fe(r.segments,V);
I>=0||I<0&&(-I-1)%2===1||(I=-I-1,I>0&&V-r.segments[I-1]===1&&I<r.segments.length&&r.segments[I]-V===1?(g.T6(r.segments,I),g.T6(r.segments,I-1)):I>0&&V-r.segments[I-1]===1?r.segments[I-1]=V:I<r.segments.length&&r.segments[I]-V===1?r.segments[I]=V:(g.to(r.segments,I,0,V),g.to(r.segments,I+1,0,V)))},JHP=function(r,V,I,d,a,f){g.X.call(this);
this.policy=r;this.player=V;this.QH=I;this.j=d;this.W=a;this.V=f;this.Y=new DM;this.C=-1;this.S=this.X=this.G=null;this.kc=0;this.L=new g.hz(this.g7,1E3,this);this.events=new g.Su(this);g.S(this,this.L);g.S(this,this.events);this.events.K(V,"SEEK_COMPLETE",this.UD);this.UD();this.g7()},ZEm=function(r){return r.G&&r.G.C?r.G.C+r.player.N2()<r.player.getCurrentTime():!1},XMo=function(r,V){if(r.policy.o0&&r.player.e6()){var I=g.hX(V,r.policy,{});
I.set("pot",r.player.e6());I=I.fq()}else I=g.hX(V,r.policy,{}).fq();var d={format:"RAW",withCredentials:!0};if(r.policy.R7){d.method="POST";var a=V.Y;a&&Object.keys(a).length>0?d.postBody=g.ru(a,g.DQ):d.postBody=(0,g.Rg)([120,0])}r.W&&(d.responseType="arraybuffer");var f=++r.kc,e=(0,g.m)();r.S=g.ld(I,d,3,100).then(function(n){if(r.policy.XI&&f%100===1){var D=(0,g.m)();r.player.Hs("caprsp",{rn:f,ms:D-e,kb:(n.xhr.responseText.length/1024).toFixed()})}a:{n=n.xhr;r.h0();if(r.X){var x=!(r.W?n.response:
n.responseText)||n.status>=400;if(D=g.Q2h(n)){n=g.hX(r.X,r.policy,{});r.X.ZN(n,D);XMo(r,r.X);break a}x?r.player.Hs("capfail",{status:n.status}):(r.player.nw().zY("fcb_r"),D=r.X.iL[0].J0,r.j!=null&&r.C!==D&&(x=r.X.iL[0],r.W?r.j(n.response,(x.startTime+r.player.N2())*1E3):r.j(n.responseText,(x.startTime+r.player.N2())*1E3),r.C=D))}r.X=null;r.S=null}}).Q7(function(n){r.X=null;
r.S=null;var D;r.player.Hs("capfail",{rn:f,status:(D=n.xhr)==null?void 0:D.status})});
r.X=V;LUP(r.Y,r.X.iL[0].J0)},xK=function(r,V){g.CY.call(this,V);
this.G=r;this.T=V;this.S=null;this.C=!1;this.logger=new g.xP("caps");this.L=g.ti(this.T.N())&&!this.G.isManifestless},goe=function(r,V){var I=[],d;
for(d in r.G.G)if(r.G.G.hasOwnProperty(d)){var a=r.G.G[d];if(g.HD(a,V||null)){var f=a.info.id,e=f,n="."+f,D="",x="";if(a=a.info.captionTrack)f=a.languageCode,e=a.displayName,n=a.vssId,D=a.kind,x=a.id;else{a=f;var E=g.Wre.get(a);E==null&&(E=BZe[a]||BZe[a.replace(/-/g,"_")],g.Wre.set(a,E));a=E;e=a||e}I.push(new g.Ci({id:d,languageCode:f,languageName:e,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:n,kind:D,captionId:x}))}}return I},S5f=function(r,V){return V!=null&&V in r.G.G?r.G.G[V]:null},
iEG=function(r,V,I){var d=[],a;
for(a in r.G.G)if(r.G.G.hasOwnProperty(a)){var f=r.G.G[a];if(g.HD(f,I||null)){var e=f.info.captionTrack;e&&e.languageCode===V&&d.push(f)}}return d.length?d[0]:null},E2=function(r,V,I,d,a,f,e,n,D,x){var E=x.isInline()&&!0,N={};
Object.assign(N,V);Object.assign(N,r.params);Object.assign(N,I);var c={};Object.assign(c,V.wm);r.params.wm&&Object.assign(c,r.params.wm);Object.assign(c,I.wm);E&&(N.windowOpacity=.6,c.backgroundOpacity=0);N.wm=c;var z=N.gy===1,M=[{J:"span",Z:"captions-text",D:{style:"word-wrap: normal; display: block;"}}],w,b,W;(n=n.uL("caption_edit_on_hover")&&((w=x.getVideoData().getPlayerResponse())==null?void 0:(b=w.captions)==null?void 0:(W=b.playerCaptionsTracklistRenderer)==null?void 0:W.openTranscriptCommand))&&
M.unshift({J:"button",Z:"caption-edit",D:{tabindex:"0","aria-label":FUc()},B:[{J:"svg",D:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},B:[{J:"path",D:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.u.call(this,{J:"div",Z:"caption-window",D:{id:"caption-window-"+r.id,dir:z?"rtl":"ltr",tabindex:"0",lang:N.lang},B:M});var K=
this;this.L=[];this.n8=!1;this.X=r;this.p8=this.R7=null;this.playerWidth=f;this.playerHeight=e;this.j=null;this.maxWidth=f*.96;this.maxHeight=e*.96;this.G=N;this.Bp=I;this.kc=V;this.Y=this.Fz("captions-text");this.X_=this.Y.style.getPropertyValue("box-decoration-break")!==""||this.Y.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Ws=U6G(d,a,f,e);this.M2=D;n&&(this.C=this.Fz("caption-edit"),this.K(this.C,"click",function(){K.M2()}));
this.type=0;this.L8=this.Ws*Qre(c);this.ya=E;r=new g.BX(this.element,!0);g.S(this,r);r.subscribe("dragstart",this.AD,this);r.subscribe("dragmove",this.Bm,this);r.subscribe("dragend",this.Mi,this);this.a7=this.EE=this.DM=this.Mk=0;r="";this.G.windowOpacity&&(r=GYm(this.G.windowColor),r="rgba("+r[0]+","+r[1]+","+r[2]+","+this.G.windowOpacity+")");V={"background-color":r,display:this.G.isVisible===!1?"none":"","text-align":m6_[this.G.textAlign]};this.X_&&(V["border-radius"]=r?this.L8/8+"px":"");(this.S=
this.X.params.gy===2||this.X.params.gy===3)&&u6K(this,this.element);g.Be(this.element,V);if(E){var F;(F=this.element.parentElement)==null||F.style.setProperty("--caption-window-color",r)}switch(this.G.f_){case 0:case 1:case 2:g.jN(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.jN(this.element,"ytp-caption-window-bottom")}},u6K=function(r,V){var I="vertical-rl";
r.G.zV===1&&(I="vertical-lr");g.MA&&(I=I==="vertical-lr"?"tb-lr":"tb-rl");g.Be(V,"-o-writing-mode",I);g.Be(V,"-webkit-writing-mode",I);g.Be(V,"writing-mode",I);g.Be(V,"text-orientation","upright");g.jN(V,"ytp-vertical-caption");r.X.params.gy===3&&(g.Be(V,"text-orientation",""),g.Be(V,"transform","rotate(180deg)"))},Qre=function(r){var V=1+.25*(r.fontSizeIncrement||0);
if(r.offset===0||r.offset===2)V*=.8;return V},pM$=function(r,V){var I={},d=V.background?V.background:r.G.wm.background;
if(V.backgroundOpacity!=null||V.background){var a=V.backgroundOpacity!=null?V.backgroundOpacity:r.G.wm.backgroundOpacity;d=GYm(d);I.background="rgba("+d[0]+","+d[1]+","+d[2]+","+a+")";r.X_&&(I["box-decoration-break"]="clone",I["border-radius"]=r.L8/8+"px")}if(V.fontSizeIncrement!=null||V.offset!=null)I["font-size"]=r.Ws*Qre(V)+"px";d=1;a=V.color||r.G.wm.color;if(V.color||V.textOpacity!=null)a=GYm(a),d=V.textOpacity==null?r.G.wm.textOpacity:V.textOpacity,a="rgba("+a[0]+","+a[1]+","+a[2]+","+d+")",
I.color=a,I.fill=a;var f=V.charEdgeStyle;f===0&&(f=void 0);if(f){a="rgba(34, 34, 34, "+d+")";var e="rgba(204, 204, 204, "+d+")";V.dw&&(e=a=V.dw);var n=r.Ws/16/2,D=Math.max(n,1),x=Math.max(2*n,1),E=Math.max(3*n,1),N=Math.max(5*n,1);d=[];switch(f){case 4:for(;E<=N;E+=n)d.push(x+"px "+x+"px "+E+"px "+a);break;case 1:x=window.devicePixelRatio>=2?.5:1;for(f=D;f<=E;f+=x)d.push(f+"px "+f+"px "+a);break;case 2:d.push(D+"px "+D+"px "+e);d.push("-"+D+"px -"+D+"px "+a);break;case 3:for(E=0;E<5;E++)d.push("0 0 "+
x+"px "+a)}I["text-shadow"]=d.join(", ")}a="";switch(V.fontFamily){case 1:a='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:a='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:a='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:a='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:a='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:a=g.qL()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:a='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}a&&(I["font-family"]=a);a=V.offset;a==null&&(a=r.G.wm.offset);switch(a){case 0:I["vertical-align"]="sub";break;case 2:I["vertical-align"]="super"}V.fontFamily===7&&(I["font-variant"]="small-caps");V.bold&&(I["font-weight"]="bold");V.italic&&(I["font-style"]="italic");V.underline&&(I["text-decoration"]=
"underline");V.mkz&&(I.visibility="hidden");V.y4===1&&r.S&&(I["text-combine-upright"]="all",I["text-orientation"]="mixed",a=g.aU||g.WQ,r.X.params.gy===3?I.transform=a?"rotate(90deg)":"rotate(180deg)":a&&(I.transform="rotate(-90deg)"));if(V.textEmphasis===1||V.textEmphasis===2||V.textEmphasis===3||V.textEmphasis===4||V.textEmphasis===5)if(g.aU)I["font-weight"]="bold";else switch(I["text-emphasis-style"]="filled circle",I["text-emphasis-color"]="currentcolor",I["webkit-text-emphasis"]="filled circle",
V.textEmphasis){case 4:case 3:I["text-emphasis-position"]="under left";I["webkit-text-emphasis-position"]="under left";break;case 5:case 2:I["text-emphasis-position"]="over right",I["webkit-text-emphasis-position"]="over right"}return I},Ng=function(r){r=r.split("px");
return r.length>0?(r=Number(r[0]))?r:0:0},voc=function(r){r.j=g.rX("SPAN");
g.Be(r.j,{display:"block"});g.jN(r.j,"caption-visual-line");r.Y.appendChild(r.j)},q5m=function(r,V){var I=g.rX("SPAN");
g.Be(I,{display:"inline-block","white-space":"pre-wrap"});g.Be(I,pM$(r,V));I.classList.add("ytp-caption-segment");r.j.appendChild(I);I.previousElementSibling&&(g.Be(I.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Be(I,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return I},Pro=function(r,V,I){r.n8=r.n8||!!I;
var d={};Object.assign(d,r.G.wm);Object.assign(d,I||V.G);Object.assign(d,r.Bp.wm);(I=!r.j)&&voc(r);for(var a=r.R7&&r.p8&&g.V3(d,r.p8)?r.R7:q5m(r,d),f=typeof V.text==="string",e=f?V.text.split("\n"):[V.text],n=0;n<e.length;n++){var D=n>0||!V.append,x=e[n];D&&!I?(voc(r),a=q5m(r,d)):D&&I&&(I=!1);x&&(a.appendChild(f?g.VE(x):x),f||x.tagName!=="RUBY"||x.childElementCount!==4||g.aU||!g.SX(x.children[2],"text-emphasis")||(D=r.S?"padding-right":"padding-top",g.SX(x.children[2],"text-emphasis-position")&&(D=
r.S?"padding-left":"padding-bottom"),g.Pz?g.Be(a,D,"1em"):g.Be(a,D,"0.5em")))}r.p8=d;r.R7=a;r.L.push(V)},U6G=function(r,V,I,d){var a=V/360*16;
V>=r&&(r=640,d>I*1.3&&(r=480),a=I/r*16);return a},kYc=function(){this.S=this.time=this.mode=this.X=0;
this.Y=new oo$(this);this.W=new oo$(this);this.G=[];this.clear()},rV_=function(r,V,I){if(r===255&&V===255||!r&&!V)return{Uy:r,
jj:V,result:0};r=hc6[r];V=hc6[V];if(r&128){var d;if(d=!(V&128))d=V,d=I.IL()&&I.jj===d;if(d)return{Uy:r,jj:V,result:1}}else if(V&128&&1<=r&&r<=31)return{Uy:r,jj:V,result:2};return{Uy:r,jj:V,result:3}},IEY=function(r,V,I,d){V===255&&I===255||!V&&!I?(++r.S===45&&r.reset(),r.Y.X.clear(),r.W.X.clear()):(r.S=0,VXf(r.Y,V,I,d))},dGG=function(r,V){r.G.sort(function(a,f){var e=a.time-f.time;
return e===0?a.order-f.order:e});
for(var I=g.H(r.G),d=I.next();!d.done;d=I.next())d=d.value,r.time=d.time,d.type===0?IEY(r,d.yI,d.lX,V):d.type===1&&r.X&496&&VXf(r.W,d.yI,d.lX,V);r.G.length=0},s2=function(){this.type=0},c2=function(){this.state=this.jj=this.Uy=0},aE_=function(){this.timestamp=this.G=0},za=function(r){this.W=r;
this.S=[];this.G=this.X=this.row=0;this.style=new s2;for(r=this.Y=0;r<=15;r++){this.S[r]=[];for(var V=0;V<=32;V++)this.S[r][V]=new aE_}},Mg=function(r,V){if(r.style.type===3){for(var I=0,d=0,a=r.W.time+0,f="",e="",n=a,D=1;D<=15;++D){for(var x=!1,E=d?d:1;E<=32;++E){var N=r.S[D][E];
if(N.G!==0){I===0&&(I=D,d=E);x=String.fromCharCode(N.G);var c=N.timestamp;c<a&&(a=c);N.timestamp=n;e&&(f+=e,e="");f+=x;x=!0}if((N.G===0||E===32)&&x){e="\n";break}else if(d&&!x)break}if(I&&!x)break}f&&V.Y(I,d,a,n,f)}else for(d=I=0,f=a=r.W.time+0,e=1;e<=15;++e)for(n="",D=1;D<=32;++D)if(E=r.S[e][D],N=E.G,N!==0&&(I===0&&(I=e,d=D),x=String.fromCharCode(N),c=E.timestamp,c<=a&&(a=c),n+=x,E.reset()),D===32||N===0)n&&V.Y(I,d,a,f,n),a=f,n="",d=I=0},jIc=function(r,V){switch(r){case 0:return fEK[(V&127)-32];
case 1:return e0G[V&15];case 2:return Y6f[V&31];case 3:return nGK[V&31]}return 0},C6=function(r){return r.S[r.row][r.X]},Ta=function(r,V,I){V>=2&&r.X>1&&(--r.X,C6(r).G=0);
var d=C6(r);d.timestamp=r.W.time+0;d.G=jIc(V,I);r.X<32&&r.X++},DGK=function(r,V,I,d){for(var a=0;a<d;a++)for(var f=0;f<=32;f++){var e=r.S[V+a][f],n=r.S[I+a][f];
e.G=n.G;e.timestamp=n.timestamp}},H2=function(r,V,I){for(var d=0;d<I;d++)for(var a=0;a<=32;a++)r.S[V+d][a].reset()},xGc=function(r){r.row=r.G>0?r.G:1;
r.X=1;H2(r,0,15)},EGG=function(r){this.S=r;
this.W=0;this.style=new s2;this.C=new za(this.S);this.L=new za(this.S);this.text=new za(this.S);this.X=this.C;this.Y=this.L;this.G=this.X},N7K=function(r,V,I){var d=r.X,a=!1;
switch(r.style.get()){case 4:case 1:case 2:r.style.get()===4&&d.G>0||(Mg(d,I),xGc(r.X),xGc(r.Y),d.row=15,d.G=V,a=!0)}r.style.set(3);r.G=d;r.G.style=r.style;r.S.mode=1<<d.Y;a?d.X=1:d.G!==V&&(d.G>V?(Mg(d,I),H2(d,d.row-d.G,V)):d.row<V&&(V=d.G),d.G=V)},sIY=function(r){r.style.set(1);
r.G=r.Y;r.G.G=0;r.G.style=r.style;r.S.mode=1<<r.G.Y},cVP=function(r){r.style.set(4);
r.G=r.text;r.G.style=r.style;r.S.mode=1<<r.G.Y},oo$=function(r){this.G=r;
this.W=0;this.S=new EGG(this.G);this.C=new EGG(this.G);this.X=new c2;this.Y=this.S},VXf=function(r,V,I,d){r.X.update();
V=rV_(V,I,r.X);switch(V.result){case 0:return;case 1:case 2:return}var a=V.Uy;I=V.jj;if(32<=a||!a)r.G.mode&r.G.X&&(V=a,V&128&&(V=127),I&128&&(I=127),r=r.Y.G,V&96&&Ta(r,0,V),I&96&&Ta(r,0,I),V!==0&&I!==0&&r.style.type===3&&Mg(r,d));else if(a&16)a:if(!r.X.matches(a,I)&&(V=r.X,V.Uy=a,V.jj=I,V.state=2,V=a&8?r.C:r.S,r.Y=V,r.G.mode=1<<(r.W<<2)+(V.W<<1)+(V.style.type===4?1:0),(r.G.mode|1<<(r.W<<2)+(V.W<<1)+(V.style.type!==4?1:0))&r.G.X))if(I&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(a&7)<<1|I>>5&1];
r=I&16?((I&14)>>1)*4:0;I=V.G;switch(V.style.get()){case 4:d=I.row;break;case 3:if(d!==I.row){if(d<I.G&&(d=I.G,d===I.row))break;var f=1+I.row-I.G,e=1+d-I.G;DGK(I,e,f,I.G);V=f;a=I.G;e<f?(f=e+a-f,f>0&&(V+=f,a-=f)):(f=f+a-e,f>0&&(a-=f));H2(I,V,a)}}I.row=d;I.X=r+1}else switch(a&7){case 1:switch(I&112){case 32:Ta(V.G,0,32);break a;case 48:I===57?(d=V.G,C6(d).G=0,d.X<32&&d.X++):Ta(V.G,1,I&15)}break;case 2:I&32&&Ta(V.G,2,I&31);break;case 3:I&32&&Ta(V.G,3,I&31);break;case 4:case 5:if(32<=I&&I<=47)switch(I){case 32:sIY(V);
break;case 33:d=V.G;d.X>1&&(--d.X,C6(d).G=0);break;case 36:d=V.G;V=C6(d);for(r=0;r<=15;r++)for(I=0;I<=32;I++)if(d.S[r][I]===V){for(;I<=32;I++)d.S[r][I].reset();break}break;case 37:N7K(V,2,d);break;case 38:N7K(V,3,d);break;case 39:N7K(V,4,d);break;case 40:Ta(V.G,0,32);break;case 41:V.style.set(2);V.G=V.X;V.G.G=0;V.G.style=V.style;V.S.mode=1<<V.G.Y;break;case 42:d=V.text;d.G=15;d.style.set(4);xGc(d);cVP(V);break;case 43:cVP(V);break;case 44:r=V.X;switch(V.style.get()){case 1:case 2:case 3:Mg(r,d)}H2(r,
0,15);break;case 45:b:{r=V.G;switch(V.style.get()){default:case 2:case 1:break b;case 4:if(r.row<15){++r.row;r.X=1;break b}break;case 3:}r.G<2&&(r.G=2,r.row<r.G&&(r.row=r.G));V=r.row-r.G+1;Mg(r,d);DGK(r,V,V+1,r.G-1);H2(r,r.row,1)}break;case 46:H2(V.Y,0,15);break;case 47:Mg(V.X,d),V.Y.updateTime(V.S.time+0),d=V.Y,V.Y=V.X,V.X=d,sIY(V)}break;case 7:switch(I){case 33:case 34:case 35:d=V.G,(d.X+=I&3)>32&&(d.X=32)}}},z0m=function(){},wO=function(r,V,I,d,a,f,e){f=f===void 0?!1:f;
e=e===void 0?null:e;g.ex.call(this,r,r+V,{priority:I,namespace:"captions"});this.windowId=d;this.text=a;this.append=f;this.G=e},CgG=function(r,V,I,d,a,f,e){var n=f[0],D=e[g.J(n.getAttribute("p"))];
if(D.JT===1){var x=f[1],E=f[2];f=f[3];n.getAttribute("t");x.getAttribute("t");E.getAttribute("t");f.getAttribute("t");n.getAttribute("p");x.getAttribute("p");f.getAttribute("p");e=e[g.J(E.getAttribute("p"))];n=MXK(n.textContent,x.textContent,E.textContent,f.textContent,e);return new wO(r,V,a,I,n,d,D)}switch(D.JT){case 9:case 10:D.textEmphasis=1;break;case 11:D.textEmphasis=2;break;case 12:D.textEmphasis=3;break;case 13:D.textEmphasis=4;break;case 14:D.textEmphasis=5}return new wO(r,V,a,I,n.textContent||
"",d,D)},MXK=function(r,V,I,d,a){var f=g.qL(),e=f?g.rX("DIV"):g.rX("RUBY"),n=g.rX("SPAN");
n.textContent=r;e.appendChild(n);r=f?g.rX("DIV"):g.rX("RP");r.textContent=V;e.appendChild(r);V=f?g.rX("DIV"):g.rX("RT");V.textContent=I;e.appendChild(V);I=a.JT;if(I===10||I===11||I===12||I===13||I===14)if(g.Be(V,"text-emphasis-style","filled circle"),g.Be(V,"text-emphasis-color","currentcolor"),g.Be(V,"webkit-text-emphasis","filled circle"),a.JT===11||a.JT===13)g.Be(V,"webkit-text-emphasis-position","under left"),g.Be(V,"text-emphasis-position","under left");I=!0;if(a.JT===4||a.JT===7||a.JT===12||
a.JT===14)g.Be(e,"ruby-position","over"),g.Be(e,"-webkit-ruby-position","before");else if(a.JT===5||a.JT===6||a.JT===11||a.JT===13)g.Be(e,"ruby-position","under"),g.Be(e,"-webkit-ruby-position","after"),I=!1;a=f?g.rX("DIV"):g.rX("RP");a.textContent=d;e.appendChild(a);f&&(d=I,g.Be(e,{display:"inline-block",position:"relative"}),f=e.firstElementChild.nextElementSibling,g.Be(f,"display","none"),f=f.nextElementSibling,g.Be(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Be(e.lastElementChild,"display","none"),d?(g.Be(e,"padding-top","0.6em"),g.Be(f,"top","0")):(g.Be(e,"padding-bottom","0.6em"),g.Be(f,"bottom","0")));return e},bK=function(){g.X.apply(this,arguments)},O2=function(r,V,I,d,a){g.ex.call(this,r,r+V,{priority:I,
namespace:"captions"});this.id=d;this.params=a;this.G=[]},T76=function(r){var V="_"+W2++;
return new O2(0,0x8000000000000,0,V,r)},$K=function(r){bK.call(this);
this.S=r;this.pens={};this.L={};this.j={};this.Y="_"+W2++;this.C={};this.X=this.G=null;this.W=!0},K6=function(r,V){r=r.getAttribute(V);
if(r!=null)return Number(r)},Rk=function(r,V){r=r.getAttribute(V);
if(r!=null)return r==="1"},ty=function(r,V){r=K6(r,V);
return r!==void 0?r:null},Ay=function(r,V){r=r.getAttribute(V);
if(r!=null)return yl.test(r),r},Hjo=function(r,V){var I={},d=V.getAttribute("ws");
Object.assign(I,d?r.j[d]:r.S);r=ty(V,"mh");r!=null&&(I.WW=r);r=ty(V,"ju");r!=null&&(I.textAlign=r);r=ty(V,"pd");r!=null&&(I.gy=r);r=ty(V,"sd");r!=null&&(I.zV=r);r=Ay(V,"wfc");r!=null&&(I.windowColor=r);V=K6(V,"wfo");V!==void 0&&(I.windowOpacity=V/255);return I},wep=function(r,V){var I={},d=V.getAttribute("wp");
d&&Object.assign(I,r.L[d]);r=ty(V,"ap");r!=null&&(I.f_=r);r=K6(V,"cc");r!=null&&(I.EL=r);r=K6(V,"ah");r!=null&&(I.cO=r);r=K6(V,"rc");r!=null&&(I.QU=r);V=K6(V,"av");V!=null&&(I.v1=V);return I},bjP=function(r,V,I,d){var a={};
Object.assign(a,wep(r,V));Object.assign(a,Hjo(r,V));d?g.V3(a,r.S)?(d=r.Y,a=r.S):d="_"+W2++:d=V.getAttribute("id")||"_"+W2++;r=K6(V,"t")+I;V=K6(V,"d")||0x8000000000000;if(a.gy===2||a.gy===3)I=a.QU,a.QU=a.EL,a.EL=I;return new O2(r,V,0,d,a)},Ga=function(r){bK.call(this);
this.W=r;this.G=new Map;this.S=new Map;this.Y=new Map;this.X=new Map},FJ=function(r){r=g.yv(Math.round(r),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-r.length)+r},Ojo=function(r,V,I,d,a){d===0&&(d=0x8000000000000);
var f={};V.wpWinPosId&&Object.assign(f,g.J(r.S.get(V.wpWinPosId)));V.wsWinStyleId&&Object.assign(f,g.J(r.Y.get(V.wsWinStyleId)));r=V.rcRowCount;r!==void 0&&(f.QU=r);V=V.ccColCount;V!==void 0&&(f.EL=V);if(f.gy===2||f.gy===3)V=f.QU,f.QU=f.EL,f.EL=V;return new O2(I,d,0,a,f)},lK=function(r,V,I){g.CY.call(this,r);
this.videoData=V;this.audioTrack=I;this.W=V.k$},L6=function(r,V,I,d,a,f,e,n,D,x){E2.call(this,r,V,I,d,a,f,e,n,D,x);
this.type=1},Jy=function(r,V,I){this.trackData=r;
this.C=I;this.version=this.W=this.S=this.byteOffset=0;this.X=[];this.G=new DataView(this.trackData)},ZM=function(r){var V=r.byteOffset;
r.byteOffset+=1;return r.G.getUint8(V)},XJ=function(r){var V=r.byteOffset;
r.byteOffset+=4;return r.G.getUint32(V)},B2=function(r,V){bK.call(this);
this.X=r;this.S=V;this.track=this.S.languageName==="CC3"?4:0;this.G=new kYc;this.G.X=1<<this.track},$Gm=function(r){if(typeof r==="string")return!1;
r=new Jy(r,8,0);return WZY(r)},WZY=function(r){if(!(r.byteOffset<r.G.byteLength)||XJ(r)!==1380139777)return!1;
r.version=ZM(r);if(r.version>1)return!1;ZM(r);ZM(r);ZM(r);return!0},gO=function(r,V,I,d,a,f,e,n,D,x){E2.call(this,r,V,I,d,a,f,e,n,D,x);
var E=this;this.type=2;this.bL=[];this.QH=this.V=this.TQ=0;this.GQ=NaN;this.Qa=0;this.dH=null;this.rH=new g.hz(this.jb,433,this);this.C&&(x.createClientVe(this.C,this,167342),this.K(this.C,"click",function(){x.logClick(E.C)}),r=new g.BX(this.element,!0),g.S(this,r),r.subscribe("hoverstart",function(){x.logVisibility(E.C,!0)},this));
g.jN(this.element,"ytp-caption-window-rollup");g.S(this,this.rH);g.Be(this.element,"overflow","hidden")},KZ_=function(r,V){if(!V)return"";
r.S&&r.X.params.zV!==1&&(V*=-1);return"translate"+(r.S?"X":"Y")+"("+V+"px)"},R0m=function(r){r.bL=Array.from(r.element.getElementsByClassName("caption-visual-line"));
for(var V=r.X.params.QU,I=0,d=0,a=r.bL.length-1;I<V&&a>-1;){var f=r.bL[a];d+=r.S?f.offsetWidth:f.offsetHeight;I++;a--}r.V=d;V=Math;I=V.max;isNaN(r.GQ)&&((d=r.G.EL)?(a=g.rX("SPAN"),g.Yx(a,"\u2013".repeat(d)),g.Be(a,pM$(r,r.G.wm)),r.Y.appendChild(a),r.GQ=a.offsetWidth,r.Y.removeChild(a)):r.GQ=0);d=r.Y;r.QH=I.call(V,r.GQ,r.Qa,(r.S?d.offsetHeight:d.offsetWidth)+1)},tXp=function(r,V){R0m(r);
var I=r.bL.reduce(function(f,e){return(r.S?e.offsetWidth:e.offsetHeight)+f},0);
I=r.V-I;if(I!==r.TQ){var d=I>0&&r.TQ===0,a=I<r.TQ;V||isNaN(I)||d||!a||(g.jN(r.element,"ytp-rollup-mode"),r.K(r.element,"transitionend",r.jb));g.Be(r.Y,"transform",KZ_(r,I));r.TQ=I}R0m(r)},yVG=function(r,V,I,d){var a=this;
this.T=r;this.S=V;this.logger=I;this.Tz=d;this.Eu=[];this.lT=[];this.G=null;this.m_={DeQ:function(){return a.G},
VX:function(){return a.Eu}};
r=g.zM(this.T.N().experiments,"html5_override_micro_discontinuities_threshold_ms");this.X=r>0?r:10},FZm=function(r,V){r.G=function(I,d){if(I.info.W){var a=I;
if(r.lT.length>0){for(a=r.lT.shift();r.lT.length>0;)a=g.DA(a,r.lT.shift());a=g.DA(a,I)}if(a){I=a;try{var f=g.x$(I)*1E3}catch(x){f=I.info.startTime*1E3}try{var e=g.l$i(I)*1E3}catch(x){e=I.info.duration*1E3}if(f<0||e<0)f<0&&(f=I.info.startTime*1E3),e<0&&(e=I.info.duration*1E3);I.info.startTime=f/1E3;I.info.Y=f/1E3;I.info.duration=e/1E3;I.info.L=e/1E3;f=r.sf(a);e=f.J0;f={formatId:f.formatId,startTimeMs:f.startTimeMs,durationMs:f.durationMs,wL:e,x8:e};e=AV6(r.Eu,f.startTimeMs);var n=(I=e>=0?r.Eu[e]:null)?
I.startTimeMs+I.durationMs:0,D=f.startTimeMs+f.durationMs;!I||f.startTimeMs-n>r.X?r.Eu.splice(e+1,0,f):(I.durationMs=Math.max(n,D)-I.startTimeMs,I.x8=Math.max(I.x8,f.x8));d(r.Eu);d=a.qG();GCf(r.S,d.buffer.slice(d.byteOffset,d.byteLength+d.byteOffset),V,a.info.Y)}else r.logger.G(350058965,"Empty slice")}else r.lT.push(I)};
r.T.addEventListener("sabrCaptionsDataLoaded",r.G)},AV6=function(r,V){r=g.Fe(r,{startTimeMs:V},function(I,d){return I.startTimeMs-d.startTimeMs});
return r>=0?r:-r-2},lE6=function(r,V){g.CY.call(this,V);
this.G=r;this.T=V;this.logger=new g.xP("caps");this.S=this.C=null;this.L=new yVG(this.T,this,this.logger,this.G.Tz)},GCf=function(r,V,I,d){r.logger.debug(function(){return"SABR captions data received for "+d});
r.C?r.S==null?r.logger.G(350058965,"Null loaded track meta data at captions data received"):I.HV(V,r.S,d*1E3):r.logger.G(350058965,"Null Representation at captions data received")},LZ6=function(r,V){var I=[],d;
for(d in r.G.G)if(r.G.G.hasOwnProperty(d)){var a=r.G.G[d];if(g.HD(a,V||null)){var f=a.info.id,e=f,n="."+f,D="",x="";if(a=a.info.captionTrack)f=a.languageCode,e=a.displayName,n=a.vssId,D=a.kind,x=a.id;I.push(new g.Ci({id:d,languageCode:f,languageName:e,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:n,kind:D,captionId:x}))}}return I},JV_=function(r,V,I){var d=[],a;
for(a in r.G.G)if(r.G.G.hasOwnProperty(a)){var f=r.G.G[a];if(g.HD(f,I||null)){var e=f.info.captionTrack;e&&e.languageCode===V&&d.push(f)}}return d.length?d[0]:null},Zje=function(r,V){if(!g.C7O(r)||r.G!=null&&g.ti(V.N())&&!r.G.isManifestless&&r.G.G.rawcc!=null)return!1;
V=!!r.G&&r.G.isManifestless&&Object.values(r.G.G).some(function(I){return g.HD(I,"386")});
r=!!r.G&&!r.G.isManifestless&&g.vYZ(r.G);return V||r},SE=function(){bK.call(this)},B76=function(r){var V=Xec.length;
if(r.byteLength<V)return!1;r=new Uint8Array(r,0,V);for(var I=0;I<V;I++)if(Xec[I]!==r[I])return!1;return!0},gGP=function(r,V,I,d,a,f,e,n,D){switch(e.tagName){case "b":n.bold=!0;
break;case "i":n.italic=!0;break;case "u":n.underline=!0}for(var x=0;x<e.childNodes.length;x++){var E=e.childNodes[x];if(E.nodeType===3)E=new wO(V,I,d,a.id,E.nodeValue,f||x>0,g.ho(n)?void 0:n),D.push(E),a.G.push(E);else{var N={};Object.assign(N,n);gGP(r,V,I,d,a,!0,E,N,D)}}},S6p=function(r){var V=r.split(":");
r=0;V=g.H(V);for(var I=V.next();!I.done;I=V.next())r=r*60+Number(I.value);return r*1E3},ijG=function(r,V,I,d){d=Object.assign({WW:0},d);
return new O2(r,V,I,"_"+W2++,d)},iK=function(r,V){g.X.call(this);
this.T=r;this.yH=V;this.G=null;this.X=this.T.l7();this.logger=new g.xP("caps")},QIK=function(r,V,I){if(typeof V==="string"||$Gm(V))return[{trackData:V,
U3:I}];if(typeof V==="string"&&V.substring(0,6)==="WEBVTT"||typeof V!=="string"&&B76(V))return[{trackData:V,U3:I}];var d=new DataView(V);if(d.byteLength<=8||d.getUint32(4)!==1718909296)return[];var a=g.gdg(d);if(r.X&&a){var f=g.Gkp(a),e=g.F6j(a);a=a.Wa;f&&a&&r.X.u8(a,f,e)}r=g.xk(d,1835295092);if(!r||!r.length||!r[0].size)return[];f=[];for(e=0;e<r.length;e++)a=r[e],a=new Uint8Array(V,a.dataOffset,a.size-(a.dataOffset-a.offset)),a=g.GU(a),f.push({trackData:a,U3:I+e*1E3});UGG(d,f,I);return f=f.filter(function(n){return!!n.trackData})},
UGG=function(r,V,I){var d=g.Ii(r,0,1836476516),a=9E4;
d&&(a=g.dr(d)||9E4);d=0;for(var f=g.xk(r,1836019558),e=0;e<f.length;e++){var n=f[e];e<V.length&&(n=g.Ii(r,n.dataOffset,1953653094))&&(n=g.Ii(r,n.dataOffset,1952867444))&&(n=g.j6(n)/a*1E3,e===0&&(d=n),V[e].U3=n-d+I||I*e*1E3)}},mG9=function(r,V,I){r.G||(r.G=new SE);
r=r.G.zL(V,I);Math.random()<.01&&g.gj(Error("Deprecated subtitles format in web player: WebVTT"));return r},uY$=function(r){var V={};
if(r=g.wv(r))V.lang=r,g.l4c.test(r)&&(V.gy=1);return V},U2=function(r){g.zu.call(this,r);
var V=this;this.T=r;this.R7=[];this.bL={};this.L8={};this.j=!1;this.Y="NONE";this.G=this.V=this.QH=this.Ws=this.DM=null;this.X_={Aa:function(){V.Aa()},
HV:function(f,e,n,D){V.HV(f,e,n,D)}};
this.X=null;this.yH=this.T.N();this.videoData=g.J(this.T.getVideoData());this.ya=this.T.gs();var I;this.Mk=(I=this.T.getVideoData(1))==null?void 0:g.hI(I);this.S={wm:{}};this.C={wm:{}};g.oa(this.videoData)?this.Y="OFFLINE":Zje(this.videoData,this.T)?this.Y="SABR_LIVE":g.HdX(this.videoData,this.T)?this.Y="LIVE":this.videoData.captionTracks.length?this.Y="INNERTUBE":this.videoData.JP&&(this.Y="TTS");this.EE=this.yH.controlsType==="3";this.a7=new iK(this.T,this.yH);this.GQ=new g.Su(this);this.L=new g.u({J:"div",
Z:"ytp-caption-window-container",D:{id:"ytp-caption-window-container"}});this.kc={top:0,right:0,bottom:0,left:0,width:1,height:1};I=null;var d=g.g3("yt-html5-player-modules::subtitlesModuleData");d&&(I=new g.AO(d));this.storage=I;var a;this.Qa=!((a=r.Sx())==null||!a.nE());this.W=pep(this);this.n8=!this.W&&this.EE&&this.Qa&&(this.Y==="LIVE"||this.Y==="SABR_LIVE");g.S(this,this.a7);this.W?this.TQ=this.p8=null:(this.p8=new g.P4(this.v6,void 0,this),g.S(this,this.p8),this.TQ=new g.hz(this.mpH,2E3,this),
g.S(this,this.TQ));g.S(this,this.GQ);g.g1(this.player,this.L.element,4);g.S(this,this.L);this.W||this.GQ.K(r,"resize",this.As);(this.rH=g.XG(this.yH)&&!g.ws()&&!this.T.isFullscreen()&&!this.W&&!this.n8)&&this.GQ.K(r,"resize",this.py8);this.GQ.K(r,"onPlaybackAudioChange",this.KK8);this.GQ.K(r,g.nv("captions"),function(f){V.onCueRangeEnter(f)});
this.GQ.K(r,g.jx("captions"),function(f){V.onCueRangeExit(f)});
this.Mk&&this.GQ.K(r,"videodatachange",function(f,e){V.onVideoDataChange(f,e)});
vGp(this,lSo()||{});this.player.k5("onCaptionsModuleAvailable")},oG_=function(r){if(r.yH.q3===1||r.videoData.P4===1||g.Kk(r.videoData,"yt:cc")==="alwayson")return!0;
if(r.videoData.captionTracks.length)var V=r.getAudioTrack().X;if(r.yH.q3===2){if(g.VO(r.yH))var I=q6$(r);else if(r.storage)try{I=r.storage.get("module-enabled")}catch(a){r.storage.remove("module-enabled")}else I=null;if(I!=null)return!!I}I=WU9(r.player.getAudioTrack(),g.VO(r.yH));var d=g.Kk(r.videoData,"yt:cc");if(Pg$(r)===void 0){if(I==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return d?d==="on":!0;if(I==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return d==="on"}else return d==="on";return V==="ON"||
g.Kk(r.videoData,"yt:cc")==="on"},Ql=function(r,V){if(r.X&&(V===void 0||!V)||!r.videoData.captionTracks.length)return!1;
r=r.getAudioTrack();return!!r.G||r.X==="FORCED_ON"},Pg$=function(r){var V=void 0,I=g.uQ(g.mL(),65);
if(g.VO(r.yH)&&I!=null){if(q6$(r)!=null)return!1;V=!I}return V},uK=function(r,V){if(!r.G)return null;
if(r.V&&r.V.Y)return r.V.Y;V=kC$(r,V);V=g.dz(r.G.X,V);var I=null;if($6e(r.yH)){var d=r.T.isInline()?void 0:g.BJ("yt-player-caption-sticky-language");for(var a=[d,r.videoData.captionsLanguagePreference,r.yH.captionsLanguagePreference,g.Kk(r.videoData,"yt:cc_default_lang")],f=!1,e=0;e<a.length;e++){var n=a[e];if(n){f=!0;for(var D=0;D<V.length;D++)if(g.wv(V[D])===n)return V[D];for(D=0;D<V.length;D++)if(g.wv(V[D]).split("-")[0]===n.split("-")[0])return V[D]}}if(f&&r.G&&(a=r.G.W,a.length))for(a=g.H(a),
f=a.next();!f.done;f=a.next())if(f=f.value,f.languageCode===d){I=f;break}}else for(d=[r.videoData.captionsLanguagePreference,r.yH.captionsLanguagePreference,g.Kk(r.videoData,"yt:cc_default_lang")],a=0;a<d.length;a++)for(f=0;f<V.length;f++)if(g.wv(V[f])===d[a])return V[f];d=null;r.V&&r.V.S&&(d=r.V.S);d||(d=V.find(function(x){return x.isDefault})||null);
d||(d=V[0]||m8(r));d&&I&&g.wv(d).split("-")[0]!==I.languageCode.split("-")[0]&&(d=KUG(d,I));return d},m8=function(r){return r.V&&r.V.G},p6=function(r){var V=m8(r);
return!!V&&r.X===V},h09=function(r,V){var I=g.J(r.T.Sx().YN()).textTracks;
r=r.X.toString();for(var d=0;d<I.length;d++){var a=I[d];a.id===r&&(V?a.mode!=="showing"&&(a.mode="showing"):a.mode==="showing"&&(a.mode="disabled"))}},P2=function(r,V,I){r.loaded&&r.unload();
I!=null&&(r.j=I,r.j&&(g.VO(r.yH)?v2(r,!!V):qg(r,!!V)));rCK(r,r.X,V,r.j,!1);r.X=V;Ql(r)&&(V=m8(r),rCK(r,r.X,V,r.j,!0),r.X=V);var d;VM$(r,(d=r.X)!=null?d:void 0);r.load()},dSG=function(r,V){if(V instanceof O2){var I=r.bL[V.id];
I&&I.X!==V&&(I.dispose(),delete r.bL[V.id],I=null);I||(I=I__(r,V))&&(r.bL[V.id]=I)}else I=V.windowId,r.L8[I]||(r.L8[I]=[]),r.L8[I].push(V)},I__=function(r,V){var I=a_c(r);
if(!I)return null;var d=r.X?g.wv(r.X):null;d&&g.l4c.test(d)&&(V.params.gy=1);var a=r.ya.getPlayerSize();d=a.height*r.kc.height;a=a.width*r.kc.width;r.yH.playerStyle!=="google-live"||r.S.isDefault||Object.assign(V.params,r.S);switch(V.params.WW!=null?V.params.WW:V.G.length>1?1:0){case 1:return new L6(V,r.S,r.C,I.width,I.height,a,d,r.yH.experiments,r.YO.bind(r),r.T);case 2:return new gO(V,r.S,r.C,I.width,I.height,a,d,r.yH.experiments,r.YO.bind(r),r.T);default:return new E2(V,r.S,r.C,I.width,I.height,
a,d,r.yH.experiments,r.YO.bind(r),r.T)}},vGp=function(r,V,I){I=I===void 0?!1:I;
var d=ok.wm;r.S={};Object.assign(r.S,ok);r.S.wm={};Object.assign(r.S.wm,d);r.C={wm:{}};var a=V.backgroundOverride?r.C:r.S,f=V.background||d.background;yl.test(f);a.wm.background=f;a=V.colorOverride?r.C:r.S;f=V.color||d.color;yl.test(f);a.wm.color=f;a=V.windowColorOverride?r.C:r.S;f=V.windowColor||ok.windowColor;yl.test(f);a.windowColor=f;a=V.backgroundOpacityOverride?r.C:r.S;f=V.backgroundOpacity;f==null&&(f=d.backgroundOpacity);a.wm.backgroundOpacity=f;a=V.fontSizeIncrementOverride?r.C:r.S;f=V.fontSizeIncrement;
f==null&&(f=d.fontSizeIncrement);a.wm.fontSizeIncrement=f;f=V.fontStyleOverride?r.C:r.S;a=V.fontStyle;a==null&&(a=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.wm;switch(a){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}a=V.textOpacityOverride?r.C:r.S;f=V.textOpacity;f==null&&(f=d.textOpacity);a.wm.textOpacity=f;a=V.windowOpacityOverride?r.C:r.S;f=V.windowOpacity;f==null&&(f=ok.windowOpacity);a.windowOpacity=
f;a=V.charEdgeStyleOverride?r.C:r.S;f=V.charEdgeStyle;f==null&&(f=d.charEdgeStyle);a.wm.charEdgeStyle=f;a=V.fontFamilyOverride?r.C:r.S;f=V.fontFamily;f==null&&(f=d.fontFamily);a.wm.fontFamily=f;r.loaded&&r.As();I&&g.X2("yt-player-caption-display-settings",V,2592E3)},f_$=function(r,V){if(!r.G)return{};
if(V){g.ho(V)||r.AZ(V.vss_id,"m");if(r.W||!g.Vc(V))return;if(g.ho(V)){P2(r,null,!0);return}for(var I,d=g.dz(r.G.X,!0),a=0;a<d.length;a++){var f=d[a];f.languageCode!==V.languageCode||I&&(f.languageName!==V.languageName||(f.captionId||"")!==(V.captionId||"")||g.Tp(f)!==V.displayName)||(I=V.translationLanguage?KUG(f,V.translationLanguage):f)}r.Dx(V.position);!I||I===r.X&&r.loaded||(V=g.rV(),d=g.wv(I),V.length&&d===V[V.length-1]||(V.push(d),g.X2("yt-player-caption-language-preferences",V)),$6e(r.yH)&&
!r.T.isInline()&&g.X2("yt-player-caption-sticky-language",d,2592E3),P2(r,I,!0))}else return r.loaded&&r.X&&!p6(r)?g.Hk(r.X):{};return""},Yue=function(r,V,I){V&&!r.QH?(V=T76({gy:0,
lang:"en-GB"}),r.QH=[V,new wO(V.start,V.end-V.start,0,V.id,I!=null?I:"Captions look like this")],r.player.Dg(r.QH)):!V&&r.QH&&(esc(r,r.QH),r.QH=null)},esc=function(r,V){r.player.e$(V);
V=g.H(V);for(var I=V.next();!I.done;I=V.next())g.H9(r.R7,I.value);jE(r.p8)},VM$=function(r,V){r.yH.U("html5_modify_caption_vss_logging")&&(r.videoData.BU=V)},a_c=function(r){var V=r.ya.getVideoContentRect(!0).height,I=r.ya.getVideoContentRect(!0).width;
if(!V||!I)return null;V*=r.kc.height;I*=r.kc.width;return{width:I,height:V}},qg=function(r,V){if(r.storage)try{r.storage.set("module-enabled",V)}catch(I){}},v2=function(r,V){r.T.isInline()||g.X2("yt-player-sticky-caption",V,2592E3)},q6$=function(r){if(!r.T.isInline())return g.BJ("yt-player-sticky-caption")},pep=function(r){if(r.yH.U("safari_live_drm_captions_fix")&&r.videoData.v3()&&r.videoData.Tz()&&g.WQ)return!0;
var V,I=!((V=r.T.Sx())==null||!V.qo());return r.EE&&I&&r.Y!=="LIVE"&&r.Y!=="SABR_LIVE"},kC$=function(r,V){g.S3(r.videoData)&&(V=!0);
V||(V=r.Y==="TTS"?!1:r.Y==="INNERTUBE"?!1:!0);return V||r.yH.U("web_deprecate_always_includes_asr_setting")&&g.VO(r.yH)?!0:!!g.uQ(g.mL(),66)},rCK=function(r,V,I,d,a){a?r.OI(I,!0,"g"):d?V?r.OI(I,!!I,"m"):I&&r.OI(I,!0,"m"):!V&&I&&r.OI(I,!0,"s")};
g.CY.prototype.FS=g.ei(77,function(){return!1});
g.CY.prototype.UZ=g.ei(76,function(){});
g.Tu.prototype.UZ=g.ei(75,function(r,V,I){var d=this;this.h0();V=this.X4(r,V);var a=this.zQ.N().U("html5_report_captions_ctmp_qoe"),f=(0,g.m)();this.M$();OEP(this,V,{format:"RAW",onSuccess:function(e){d.G=null;if(a){var n=(e.responseText.length/1024).toFixed(),D=(0,g.m)();d.videoData.Hs("capresp",{ms:D-f,kb:n})}I.HV(e.responseText,r)},
onError:a?function(e){var n;e=(n=e==null?void 0:e.status)!=null?n:0;d.videoData.Hs("capfail",{status:e})}:void 0,
withCredentials:!0})});
g.wz.prototype.UZ=g.ei(74,function(r,V,I){var d=this;this.h0();V=this.X4(r,V);this.M$();this.G=g.yr(V,{format:"RAW",onSuccess:function(a){d.G=null;I.HV(a.responseText,r)},
withCredentials:!0})});
g.pS.prototype.aN=g.ei(73,function(){for(var r=g.pJ(document,"track",void 0,this.G),V=0;V<r.length;V++)g.fy(r[V])});
g.Fh.prototype.aN=g.ei(72,function(){this.mediaElement.aN()});
g.pS.prototype.nE=g.ei(71,function(){return!(!this.G.textTracks||!this.G.textTracks.addEventListener)});
g.Fh.prototype.nE=g.ei(70,function(){return this.mediaElement.nE()});
g.pS.prototype.qo=g.ei(69,function(){return!!this.G.textTracks});
g.Fh.prototype.qo=g.ei(68,function(){return this.mediaElement.qo()});
g.pS.prototype.pz=g.ei(67,function(r){for(var V=0;V<r.length;V++)this.G.appendChild(r[V])});
g.Fh.prototype.pz=g.ei(66,function(r){this.mediaElement.pz(r)});
g.Kf.prototype.u8=g.ei(65,function(r,V,I){this.j4.u8(r,V,I)});
g.Q5.prototype.u8=g.ei(64,function(r,V,I){this.X.set(r,{x$:V,Cy:I})});
g.mW.prototype.u8=g.ei(63,function(r,V,I){this.p8.u8(r,V,I)});
g.Kf.prototype.SS=g.ei(62,function(r){return this.j4.SS(r)});
g.mW.prototype.SS=g.ei(61,function(r){var V=2;this.V.has(r)?V=0:g.ebA(this,r)&&(V=1);return V});
g.Gm.prototype.LC=g.ei(49,function(r){var V=this.app.xN();return V?V.LC(r):!1});
g.u5.prototype.LC=g.ei(48,function(r){return this.lL.k9.LC(r)});
g.G_.prototype.LC=g.ei(47,function(r){return this.bz().some(function(V){return V.namespace===r})});
g.Xh.prototype.LC=g.ei(46,function(){return!1});
g.Gm.prototype.AZ=g.ei(44,function(r,V){this.app.jC().AZ(r,V)});
g.u5.prototype.AZ=g.ei(43,function(r,V){this.lL.AZ(r,V)});
g.x4.prototype.AZ=g.ei(42,function(r,V){r=[r,V];g.Dv(this,g.$U(this.provider),"cfi",r)});
g.Rb.prototype.AZ=g.ei(41,function(r,V){this.qoe&&this.qoe.AZ(r,V)});
g.dn.prototype.AZ=g.ei(40,function(r,V){this.jR().AZ(r,V)});
g.Xh.prototype.AZ=g.ei(39,function(){});
g.Gm.prototype.OI=g.ei(38,function(r,V,I){this.app.jC().OI(r,V,I)});
g.u5.prototype.OI=g.ei(37,function(r,V,I){this.lL.OI(r,V,I)});
g.x4.prototype.OI=g.ei(36,function(r,V,I){if(this.TQ!==r||this.Bp!==V)V=V==="rawcc"?"":V,I=[r,V,this.TQ,I],g.Dv(this,g.$U(this.provider),"cfs",I),this.TQ=r,this.Bp=V});
g.Rb.prototype.OI=g.ei(35,function(r,V,I){this.qoe&&this.qoe.OI(r,V,I)});
g.dn.prototype.OI=g.ei(34,function(r,V,I){this.jR().OI(r,V,I)});
g.Xh.prototype.OI=g.ei(33,function(){});
g.OF.prototype.Zc=g.ei(20,function(){return this.QH});
g.Mh.prototype.Zc=g.ei(19,function(){return this.jC().l7()});
g.Gm.prototype.l7=g.ei(18,function(){return this.app.Zc()});
g.u5.prototype.l7=g.ei(17,function(){return this.lL.l7()});
g.dn.prototype.l7=g.ei(16,function(){var r;return((r=this.loader)==null?void 0:r.Zc())||null});
g.Xh.prototype.l7=g.ei(15,function(){return null});
g.iY.prototype.Xv=g.ei(1,function(r){return(r=this.MS(r))?r.G:0});
g.c5.prototype.Xv=g.ei(0,function(){return 0});
var AHK=/#(.)(.)(.)/,yHP=/^#(?:[0-9a-f]{3}){1,2}$/i,BZe={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};DM.prototype.contains=function(r){r=g.Fe(this.segments,r);return r>=0||r<0&&(-r-1)%2===1};
DM.prototype.length=function(){return this.segments.length/2};
g.T(JHP,g.X);g.C=JHP.prototype;g.C.eC=function(){g.X.prototype.eC.call(this);this.S&&this.S.cancel()};
g.C.UD=function(){this.seekTo(this.player.getCurrentTime())};
g.C.seekTo=function(r){r-=this.player.N2();var V=this.G;this.G=g.Nm(this.QH.X6(r).iL);V!==this.G&&this.V&&this.V()};
g.C.reset=function(){this.Y=new DM;this.C=-1;this.S&&(this.S.cancel(),this.S=null)};
g.C.g7=function(){this.h0();var r;if(r=this.G!=null)r=this.G,r=r.G.zC(r);if(r&&!this.S&&!(this.G&&this.G.startTime-this.player.getCurrentTime()>30)){r=this.G;r=g.J(r.G.dZ(r));var V=r.iL[0],I;if((I=this.player.getVideoData())==null?0:I.enableServerStitchedDai)if(I=this.player.l7()){var d=V.G.info.id,a=V.J0,f=r.iL[0].Y;if(this.policy.R7){if(I=I.Sp(f,a,d,3))r.Y=I}else if(d=I.qE(f,a,d,3))if(I=I.SS(a),I===0)d&&(r.G=new g.lY(d));else if(I===2){this.L.start();ZEm(this)&&this.seekTo(this.player.getCurrentTime());
return}}V.G.index.A2(V.J0)?(this.Y.contains(r.iL[0].J0)||XMo(this,r),this.G=g.Nm(r.iL)):ZEm(this)&&this.seekTo(this.player.getCurrentTime())}this.L.start()};
g.T(xK,g.CY);g.C=xK.prototype;g.C.UZ=function(r,V,I){var d=this;this.M$();V=S5f(this,r.getId());V||(V=r.languageCode,V=this.G.isManifestless?iEG(this,V,"386"):iEG(this,V));if(V){var a=(V.index.Xv(V.index.PG())-V.index.getStartTime(V.index.PG()))*1E3,f=this.T.N(),e=new g.KDU(f),n=function(){d.S&&d.S.reset();d.C=!0};
f.U("html5_keep_caption_data_after_seek")&&(n=null);this.S=new JHP(e,this.T,V,function(D,x){I.HV(D,r,x,a)},this.L||g.I2(V.info),n)}};
g.C.FS=function(){var r=this.C;this.C=!1;return r};
g.C.A4=function(r){var V=this.T.N().U("html5_fallback_if_rawcc_missing");var I=this.G.G.rawcc!=null;if(!this.L||!I&&V)V=this.G.isManifestless?goe(this,"386"):goe(this);else{if(!I){this.logger.G(386248249,"rawcc used but unavailable");return}V=[new g.Ci({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Ci({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}V=g.H(V);
for(I=V.next();!I.done;I=V.next())g.MZ(this.X,I.value);r.Aa()};
g.C.M$=function(){this.S&&(this.S.dispose(),this.S=null)};
g.C.X4=function(){return""};
g.C.ZB=function(){this.S&&(this.S.reset(),this.T.Zg("captions"))};
var yl=/^#(?:[0-9a-f]{3}){1,2}$/i;var m6_=["left","right","center","justify"];g.T(E2,g.u);g.C=E2.prototype;g.C.AD=function(r,V){this.EE=r;this.a7=V;var I=g.ve(this.element,this.element.parentElement);this.Mk=r-I.x;this.DM=V-I.y};
g.C.Bm=function(r,V){if(r!==this.EE||V!==this.a7){g.nL(this.element,"ytp-dragging")||g.jN(this.element,"ytp-dragging");var I=g.Pe(this.element);r=r-this.Mk-.02*this.playerWidth;var d=V-this.DM-.02*this.playerHeight,a=(r+I.width/2)/this.maxWidth*3;a=Math.floor(g.yv(a,0,2));var f=(d+I.height/2)/this.maxHeight*3;f=Math.floor(g.yv(f,0,2));V=a+f*3;r=(r+a/2*I.width)/this.maxWidth;r=g.yv(r,0,1)*100;I=(d+f/2*I.height)/this.maxHeight;I=g.yv(I,0,1)*100;this.X.params.f_=V;this.X.params.v1=I;this.X.params.cO=
r;this.X.params.isDefault=!1;this.G.f_=V;this.G.v1=I;this.G.cO=r;this.G.isDefault=!1;this.kc.f_=V;this.kc.v1=I;this.kc.cO=r;this.kc.isDefault=!1;this.q1()}};
g.C.Mi=function(){g.xS(this.element,"ytp-dragging")};
g.C.q1=function(){this.sW(this.L)};
g.C.getType=function(){return this.type};
g.C.sW=function(r){var V=this.ya?0:Math.min(this.eK(),this.maxWidth),I=this.O_(),d=this.ya;if(d){var a=getComputedStyle(this.Y.parentNode);a=Ng(a.borderLeftWidth)+Ng(a.borderRightWidth)+Ng(a.paddingLeft)+Ng(a.paddingRight)}else a=0;var f=a;a="";this.X.params.gy===3&&(a="rotate(180deg)");var e=d?"calc(96% - "+f+"px)":"96%";g.Be(this.element,{top:0,left:0,right:"",bottom:"",width:V?V+"px":"",height:I?I+"px":"","max-width":e,"max-height":e,margin:"",transform:""});this.YB(r);a={transform:a,top:"",left:"",
width:V?V+"px":"",height:I?I+"px":"","max-width":"","max-height":""};var n=this.G.cO*.96+2;e=this.G.f_;switch(e){case 0:case 3:case 6:(d=this.G.wm.fontSizeIncrement)&&d>0&&this.G.gy!==2&&this.G.gy!==3&&(n=Math.max(n/(1+d*2),2));a.left=n+"%";break;case 1:case 4:case 7:a.left=n+"%";n=this.Y.offsetWidth;V||n?(V=V||n+1,a.width=V+"px",a["margin-left"]=d?V/-2-f/2+"px":V/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-n+"%"}d=this.G.v1*.96+2;switch(e){case 0:case 1:case 2:a.top=
d+"%";break;case 3:case 4:case 5:a.top=d+"%";(I=I||this.element.clientHeight)?(a.height=I+"px",a["margin-top"]=I/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-d+"%"}g.Be(this.element,a);if(this.C){I=this.Y.offsetHeight;d=1;for(V=0;V<r.length;V++)a=r[V],typeof a.text==="string"&&(d+=a.text.split("\n").length-1,a.append||V===0||d++);I/=d;this.C.style.height=I+"px";this.C.style.width=I+"px";this.element.style.paddingLeft=I+5+"px";this.element.style.paddingRight=I+
5+"px";r=Number(this.element.style.marginLeft.replace("px",""))-I-5;I=Number(this.element.style.marginRight.replace("px",""))-I-5;this.element.style.marginLeft=r+"px";this.element.style.marginRight=I+"px"}};
g.C.YB=function(r){var V;for(V=0;V<r.length&&r[V]===this.L[V];V++);if(this.n8||this.L.length>V)V=0,this.n8=!1,this.L=[],this.j=this.p8=this.R7=null,g.dX(this.Y);for(;V<r.length;V++)Pro(this,r[V])};
g.C.eK=function(){return 0};
g.C.O_=function(){return 0};
g.C.toString=function(){return g.u.prototype.toString.call(this)};kYc.prototype.clear=function(){this.S=this.time=this.mode=0;this.G=[];this.reset()};
kYc.prototype.reset=function(){this.mode=0;this.Y.reset(0);this.W.reset(1)};
var hc6=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];s2.prototype.set=function(r){this.type=r};
s2.prototype.get=function(){return this.type};
c2.prototype.clear=function(){this.state=0};
c2.prototype.update=function(){this.state=this.state===2?1:0};
c2.prototype.IL=function(){return this.state!==0};
c2.prototype.matches=function(r,V){return this.IL()&&r===this.Uy&&V===this.jj};
aE_.prototype.reset=function(){this.timestamp=this.G=0};
za.prototype.updateTime=function(r){for(var V=1;V<=15;++V)for(var I=1;I<=32;++I)this.S[V][I].timestamp=r};
za.prototype.debugString=function(){for(var r="\n",V=1;V<=15;++V){for(var I=1;I<=32;++I){var d=this.S[V][I];r=d.G===0?r+"_":r+String.fromCharCode(d.G)}r+="\n"}return r};
za.prototype.reset=function(r){for(var V=0;V<=15;V++)for(var I=0;I<=32;I++)this.S[V][I].reset();this.Y=r;this.G=0;this.X=this.row=1};
var fEK=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],e0G=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Y6f=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],nGK=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];EGG.prototype.reset=function(r,V){this.W=V;this.style.set(2);this.X=this.C;this.Y=this.L;this.G=this.X;var I=(r<<2)+(V<<1);this.C.reset(I);this.L.reset(I);this.text.reset((r<<2)+(V<<1)+1)};
oo$.prototype.reset=function(r){this.W=r;this.X.clear();this.Y=this.S;this.S.reset(r,0);this.C.reset(r,1)};z0m.prototype.Y=function(){};g.T(wO,g.ex);wO.prototype.toString=function(){return g.ex.prototype.toString.call(this)};g.T(bK,g.X);bK.prototype.zL=function(){return[]};
bK.prototype.reset=function(){};g.T(O2,g.ex);O2.prototype.toString=function(){return g.ex.prototype.toString.call(this)};
var W2=0;g.T($K,bK);$K.prototype.reset=function(){this.C={};this.X=this.G=null;this.W=!0};
$K.prototype.zL=function(r,V){r=r.firstChild;r.getAttribute("format");V=V||0;Number.isFinite(V);r=Array.from(r.childNodes);r=g.H(r);for(var I=r.next();!I.done;I=r.next())if(I=I.value,I.nodeType===1)switch(I.tagName){case "head":var d=I;break;case "body":var a=I}if(d)for(d=Array.from(d.childNodes),d=g.H(d),r=d.next();!r.done;r=d.next())if(r=r.value,r.nodeType===1)switch(r.tagName){case "pen":I=r.getAttribute("id");var f=this.pens,e={},n=r.getAttribute("p");n&&Object.assign(e,this.pens[n]);n=Rk(r,"b");
n!=null&&(e.bold=n);n=Rk(r,"i");n!=null&&(e.italic=n);n=Rk(r,"u");n!=null&&(e.underline=n);n=ty(r,"et");n!=null&&(e.charEdgeStyle=n);n=ty(r,"of");n!=null&&(e.offset=n);n=Ay(r,"bc");n!=null&&(e.background=n);n=Ay(r,"ec");n!=null&&(e.dw=n);n=Ay(r,"fc");n!=null&&(e.color=n);n=ty(r,"fs");n!=null&&n!==0&&(e.fontFamily=n);n=K6(r,"sz");n!==void 0&&(e.fontSizeIncrement=n/100-1);n=K6(r,"bo");n!==void 0&&(e.backgroundOpacity=n/255);n=K6(r,"fo");n!==void 0&&(e.textOpacity=n/255);n=ty(r,"rb");n!=null&&n!==10&&
n!==0&&(e.JT=n>10?n-1:n);r=ty(r,"hg");r!=null&&(e.y4=r);f[I]=e;break;case "ws":I=r.getAttribute("id");this.j[I]=Hjo(this,r);break;case "wp":I=r.getAttribute("id"),this.L[I]=wep(this,r)}if(a){d=[];a=Array.from(a.childNodes);a=g.H(a);for(r=a.next();!r.done;r=a.next())if(r=r.value,r.nodeType===1)switch(r.tagName){case "w":this.G=bjP(this,r,V,!1);(r=this.C[this.G.id])&&r.end>this.G.start&&(r.end=this.G.start);this.C[this.G.id]=this.G;d.push(this.G);break;case "p":var D=r;n=V;I=[];f=D.getAttribute("w")||
this.Y;e=!!Rk(D,"a");n=(K6(D,"t")||0)+n;var x=K6(D,"d")||5E3;e||(!this.W&&this.X&&this.X.windowId===f&&this.X.end>n&&(this.X.end=n),this.X&&this.X.text==="\n"&&(this.X.text=""));var E=e?6:5,N=D.getAttribute("p");N=N?this.pens[N]:null;var c=Array.from(D.childNodes);c.length&&(this.W=D.getAttribute("d")!=null);for(D=0;D<c.length;D++){var z=c[D],M=void 0;D>0&&(e=!0);var w=void 0;z.nodeType===1&&(w=z);if(w&&w.tagName==="s"){if((z=(z=w.getAttribute("p"))?this.pens[z]:null)&&z.JT&&(z.JT===1?(z=c.slice(D,
D+4),z.length===4&&(M=CgG(n,x,f,e,E,z,this.pens),D+=3)):M=CgG(n,x,f,e,E,[w],this.pens)),!M){var b=w;M=n;w=x;z=f;var W=e,K=E,F=b.textContent?b.textContent:"",l=b.getAttribute("p");l=l?this.pens[l]:null;b=K6(b,"t")||0;M=new wO(M+b,w-b,K,z,F,W,l)}}else M=new wO(n,x,E,f,z.textContent||"",e,N);I.push(M);this.X=M}if(I.length>0)for(I[0].windowId===this.Y&&(this.G=bjP(this,r,V,!0),d.push(this.G)),r=g.H(I),I=r.next();!I.done;I=r.next())I=I.value,I.windowId=this.G.id,this.G.G.push(I),d.push(I)}V=d}else V=[];
return V};var neK=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.T(Ga,bK);Ga.prototype.reset=function(){this.X.clear()};
Ga.prototype.zL=function(r,V){var I=JSON.parse(r);if(!I)return[];if(I.pens){r=0;for(var d=g.H(I.pens),a=d.next();!a.done;a=d.next()){a=a.value;var f={},e=a.pParentId;e&&Object.assign(f,g.J(this.G.get(e)));a.bAttr&&(f.bold=!0);a.iAttr&&(f.italic=!0);a.uAttr&&(f.underline=!0);e=a.ofOffset;e!=null&&(f.offset=e);a.szPenSize!==void 0&&(f.fontSizeIncrement=a.szPenSize/100-1);e=a.etEdgeType;e!=null&&(f.charEdgeStyle=e);a.ecEdgeColor!==void 0&&(f.dw=FJ(a.ecEdgeColor));e=a.fsFontStyle;e!=null&&e!==0&&(f.fontFamily=
e);a.fcForeColor!==void 0&&(f.color=FJ(a.fcForeColor));a.foForeAlpha!==void 0&&(f.textOpacity=a.foForeAlpha/255);a.bcBackColor!==void 0&&(f.background=FJ(a.bcBackColor));a.boBackAlpha!==void 0&&(f.backgroundOpacity=a.boBackAlpha/255);(e=a.rbRuby)&&e!==10&&(f.JT=e>10?e-1:e,f.textEmphasis=neK.get(f.JT));a.hgHorizGroup&&(f.y4=a.hgHorizGroup);this.G.set(r++,f)}}if(I.wsWinStyles)for(r=0,d=g.H(I.wsWinStyles),a=d.next();!a.done;a=d.next())a=a.value,f={},(e=a.wsParentId)?Object.assign(f,g.J(this.Y.get(e))):
Object.assign(f,this.W),a.mhModeHint!==void 0&&(f.WW=a.mhModeHint),a.juJustifCode!==void 0&&(f.textAlign=a.juJustifCode),a.pdPrintDir!==void 0&&(f.gy=a.pdPrintDir),a.sdScrollDir!==void 0&&(f.zV=a.sdScrollDir),a.wfcWinFillColor!==void 0&&(f.windowColor=FJ(a.wfcWinFillColor)),a.wfoWinFillAlpha!==void 0&&(f.windowOpacity=a.wfoWinFillAlpha/255),this.Y.set(r++,f);if(I.wpWinPositions)for(r=0,d=g.H(I.wpWinPositions),a=d.next();!a.done;a=d.next())a=a.value,f={},(e=a.wpParentId)&&Object.assign(f,g.J(this.S.get(e))),
a.ahHorPos!==void 0&&(f.cO=a.ahHorPos),a.apPoint!==void 0&&(f.f_=a.apPoint),a.avVerPos!==void 0&&(f.v1=a.avVerPos),a.ccCols!==void 0&&(f.EL=a.ccCols),a.rcRows!==void 0&&(f.QU=a.rcRows),this.S.set(r++,f);if(I.events){r=[];I=g.H(I.events);for(d=I.next();!d.done;d=I.next()){var n=d.value;a=(n.tStartMs||0)+V;f=n.dDurationMs||0;if(n.id)e=String(n.id),d=Ojo(this,n,a,f,e),r.push(d),this.X.set(e,d);else{n.wWinId?e=n.wWinId.toString():(e="_"+W2++,d=Ojo(this,n,a,f,e),r.push(d),this.X.set(e,d));d=r;var D=n;
f===0&&(f=5E3);n=g.J(this.X.get(e));var x=!!D.aAppend,E=x?6:5,N=D.segs,c=null;D.pPenId&&(c=g.J(this.G.get(D.pPenId)));for(D=0;D<N.length;D++){var z=N[D],M=z.utf8;if(M){var w=z.tOffsetMs||0,b=null;z.pPenId&&(b=g.J(this.G.get(z.pPenId)));if((n.params.WW!=null?n.params.WW:n.G.length>1?1:0)===2&&x&&M==="\n")continue;z=null;var W=[],K;if(K=b&&b.JT===1){K=N;var F=D;if(F+3>=K.length||!K[F+1].pPenId||!K[F+2].pPenId||!K[F+3].pPenId)K=!1;else{var l=K[F+1].pPenId;(l=this.G.get(l))&&l.JT&&l.JT===2?(l=K[F+2].pPenId,
l=this.G.get(l),!l||!l.JT||l.JT<3?K=!1:(l=K[F+3].pPenId,K=(l=this.G.get(l))&&l.JT&&l.JT===2?!0:!1)):K=!1}}if(K)w=N[D+1].utf8,z=N[D+3].utf8,K=N[D+2].utf8,F=g.J(this.G.get(N[D+2].pPenId)),M=MXK(M,w,K,z,F),z=new wO(a,f,E,e,M,x,b),D+=3;else{if(M.indexOf("<")>-1){var B=void 0;W=b;K=c;F=a;l=f;var P=w,p=E,dA=x,fg=[],rA=g.J(g.P$("<html>"+M+"</html>"));if(!rA.getElementsByTagName("parsererror").length&&((B=rA.firstChild)==null?0:B.childNodes.length))for(B=g.H(rA.firstChild.childNodes),rA=B.next();!rA.done;rA=
B.next()){rA=rA.value;var ji=void 0,k=void 0,bX=(k=(ji=rA.textContent)==null?void 0:ji.replace(/\n/g,""))!=null?k:"";if(rA.nodeType!==3||bX&&bX.match(/^ *$/)==null){ji={};Object.assign(ji,W||K);k=void 0;switch((k=rA)==null?void 0:k.tagName){case "b":ji.bold=!0;break;case "i":ji.italic=!0;break;case "u":ji.underline=!0}fg.push(new wO(F+P,l-P,p,n.id,bX,dA,ji))}}W=fg}W.length||(W=[new wO(a+w,f-w,E,n.id,M,x,b||c)])}if(W.length)for(x=g.H(W),b=x.next();!b.done;b=x.next())b=b.value,d.push(b),n.G.push(b);
else z&&(d.push(z),n.G.push(z))}x=!0}}}V=r}else V=[];return V};g.T(lK,g.CY);lK.prototype.UZ=function(r,V,I){taG(this.videoData.videoId,r.vssId,I.HV)};
lK.prototype.A4=function(r){if(this.audioTrack)for(var V=g.H(this.audioTrack.captionTracks),I=V.next();!I.done;I=V.next())g.MZ(this.X,I.value);r.Aa()};g.T(L6,E2);L6.prototype.YB=function(r){var V=this.X.G;E2.prototype.YB.call(this,r);for(r=r.length;r<V.length;r++){var I=V[r];if(f&&I.G===a)var d=f;else{d={};Object.assign(d,I.G);Object.assign(d,jme);var a=I.G;var f=d}Pro(this,I,d)}};
var jme={mkz:!0};g.T(Jy,z0m);Jy.prototype.Y=function(r,V,I,d,a){if(I<d){var f="_"+W2++;I=I/1E3-this.C;d=d/1E3-this.C;r=new O2(I,d-I,5,f,{textAlign:0,f_:0,cO:V*2.5,v1:r*5.33});a=new wO(I,d-I,5,f,a);this.X.push(r);this.X.push(a)}};
g.T(B2,bK);B2.prototype.zL=function(r){r=new Jy(r,r.byteLength,this.X);if(WZY(r)){for(;r.byteOffset<r.G.byteLength;)for(r.version===0?r.S=XJ(r)*(1E3/45):r.version===1&&(r.S=XJ(r)*4294967296+XJ(r)),r.W=ZM(r);r.W>0;r.W--){var V=ZM(r),I=ZM(r),d=ZM(r);V&4&&(V&3)===this.track&&(this.track===0||this.track===1)&&(V=this.G,V.G.push({time:r.S,type:this.track,yI:I,lX:d,order:V.G.length}))}dGG(this.G,r);return r.X}return[]};
B2.prototype.reset=function(){this.G.clear()};g.T(gO,E2);g.C=gO.prototype;g.C.q1=function(){g.Vj(this.rH)};
g.C.jb=function(){this.element.removeEventListener("transitionend",this.jb,!1);g.xS(this.element,"ytp-rollup-mode");this.sW(this.dH,!0)};
g.C.O_=function(){return this.S?this.QH:this.V};
g.C.eK=function(){return this.S?this.V:this.QH};
g.C.sW=function(r,V){this.dH=r;if(this.X.params.QU){for(var I=0,d=0;d<this.L.length&&I<r.length;d++)this.L[d]===r[I]&&I++;I>0&&I<r.length&&(r=this.L.concat(r.slice(I)));this.Qa=this.QH;this.V=this.QH=0;E2.prototype.sW.call(this,r);tXp(this,V)}E2.prototype.sW.call(this,r)};yVG.prototype.unload=function(){this.G!=null&&(this.T.removeEventListener("sabrCaptionsDataLoaded",this.G),this.G=null);this.Eu=[];this.T.publish("sabrCaptionsBufferedRangesUpdated",this.Eu)};
yVG.prototype.sf=function(r){return{formatId:g.a2(r.info.G.info,this.Tz),J0:r.info.J0+(this.Tz?0:1),startTimeMs:r.info.Y*1E3,durationMs:r.info.L*1E3}};g.T(lE6,g.CY);g.C=lE6.prototype;g.C.UZ=function(r,V,I){this.M$();V=r.getId();V=V!=null&&V in this.G.G?this.G.G[V]:null;V||(V=r.languageCode,V=this.G.isManifestless?JV_(this,V,"386"):JV_(this,V));V&&(this.S=r,this.C=V,FZm(this.L,I),this.T.publish("sabrCaptionsTrackChanged",g.a2(V.info,this.G.Tz)))};
g.C.A4=function(r){var V=this.G.isManifestless?LZ6(this,"386"):LZ6(this);V=g.H(V);for(var I=V.next();!I.done;I=V.next())g.MZ(this.X,I.value);r.Aa()};
g.C.M$=function(){this.S&&(this.S=this.C=null,this.L.unload(),this.T.publish("sabrCaptionsTrackChanged",null))};
g.C.X4=function(){return""};
g.C.ZB=function(){this.T.Zg("captions")};var Xec="WEBVTT".split("").map(function(r){return r.charCodeAt(0)});
g.T(SE,bK);
SE.prototype.zL=function(r,V){r instanceof ArrayBuffer&&(r=g.GU(new Uint8Array(r)));var I=[];r=r.split(DSm);for(var d=1;d<r.length;d++){var a=r[d],f=V;if(a!==""&&!xSp.test(a)){var e=Eeo.exec(a);if(e&&e.length>=4){var n=S6p(e[1]),D=S6p(e[2])-n;n+=f;var x=(e=e[3])?e.split(" "):[];e={};var E=null;var N="";var c=null,z="";x=g.H(x);for(var M=x.next();!M.done;M=x.next())if(M=M.value.split(":"),M.length===2){var w=M[1];switch(M[0]){case "line":M=w.split(",");M[0].endsWith("%")&&(E=M[0],e.v1=Number.parseInt(E,10),
M.length===2&&(N=M[1].trim()));break;case "position":M=w.split(",");c=M[0];e.cO=Number.parseInt(c,10);M.length===2&&(z=M[1].trim());break;case "align":switch(w){case "start":e.textAlign=0;break;case "middle":e.textAlign=2;break;case "end":e.textAlign=1}}}E||N||(N="end");if(!c)switch(e.textAlign){case 0:e.cO=0;break;case 1:e.cO=100;break;case 2:e.cO=50}if(e.textAlign!=null){E=0;switch(N){case "center":E+=3;break;case "end":E+=6;break;default:E+=0}switch(z){case "line-left":E+=0;break;case "center":E+=
1;break;case "line-right":E+=2;break;default:switch(e.textAlign){case 0:E+=0;break;case 2:E+=1;break;case 1:E+=2}}N=E<0||E>8?7:E;e.f_=N}a=a.substring(Eeo.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");z=e;e=a;a={};if(e.indexOf("<")<0&&e.indexOf("&")<0)f=ijG(n,D,5,z),D=new wO(n,D,5,f.id,e,!1,g.ho(a)?void 0:a),I.push(f),I.push(D),f.G.push(D);else for(N=e.split(N6_),N.length===1?(e=5,z=ijG(n,D,e,z)):(E=e=6,z=Object.assign({EL:32},z),z=new O2(n,D,E,"_"+W2++,z)),I.push(z),E=n,c=0;c<N.length;c++)x=N[c],
c%2===0?(M=g.J(g.P$("<html>"+x+"</html>")),M.getElementsByTagName("parsererror").length?(w=M.createElement("span"),w.appendChild(M.createTextNode(x))):w=M.firstChild,gGP(this,E,D-(E-n),e,z,c>0,w,a,I)):E=S6p(x)+f}Eeo.lastIndex=0}}return I};
var xSp=/^NOTE/,DSm=/(?:\r\n|\r|\n){2,}/,Eeo=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),N6_=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.lM.NO(SE,{zL:"wvppt"});g.T(iK,g.X);
iK.prototype.zL=function(r,V,I,d){d=d||0;I=QIK(this,r,I||0);r=[];try{for(var a=g.H(I),f=a.next();!f.done;f=a.next()){var e=f.value,n=e.trackData,D=e.U3,x=this.yH.U("safari_live_drm_captions_fix");if(typeof n!=="string"){I=r;var E=I.concat;if(x&&B76(n))var N=mG9(this,n,D);else{var c=V,z=n,M=D,w=d;if(!$Gm(z))throw Error("Invalid binary caption track data");this.G||(this.G=new B2(w,c));N=this.G.zL(z,M)}var b=E.call(I,N)}else{if(n.substring(0,6)==="WEBVTT")var W=r.concat(mG9(this,n,D));else{I=r;var K=
I.concat;a:{c=V;if(n[0]==="{")try{this.G||(this.G=new Ga(uY$(c)));var F=this.G.zL(n,D);break a}catch(fg){g.BG(fg);F=[];break a}var l=g.P$(n);if(!l||!l.firstChild){var B=Error("Invalid caption track data");B.params=n;throw B;}if(l.firstChild.tagName==="timedtext"){if(Number(l.firstChild.getAttribute("format"))===3){z=l;this.G||(this.G=new $K(uY$(c),this.yH));F=this.G.zL(z,D);break a}var P=Error("Unsupported subtitles format in web player (Format2)");P.params=n;throw P;}if(l.firstChild.tagName==="transcript"){var p=
Error("Unsupported subtitles format in web player (Format1)");p.params=n;throw p;}var dA=Error("Invalid caption track data");dA.params=n;throw dA;}W=K.call(I,F)}b=W}r=b}return r}catch(fg){return this.logger.G(187101178,"Captions parsing failed: "+fg.message+". "),this.clear(),[]}};
iK.prototype.clear=function(){this.G&&this.G.dispose();this.G=null};
iK.prototype.reset=function(){this.G&&this.G.reset()};
iK.prototype.eC=function(){g.X.prototype.eC.call(this);this.clear()};var ok={windowColor:"#080808",windowOpacity:0,textAlign:2,f_:7,cO:50,v1:100,isDefault:!0,wm:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.T(U2,g.zu);g.C=U2.prototype;g.C.eC=function(){if(this.W||this.n8){var r=this.T.Sx();r&&!r.h0()&&r.aN()}else Yue(this,!1);g.zu.prototype.eC.call(this)};
g.C.eG=function(){return this.yH.U("html5_honor_caption_availabilities_in_audio_track")&&this.Y!=="LIVE"&&this.Y!=="SABR_LIVE"};
g.C.Tl=function(){if(this.EE)return this.W||this.n8;var r=this.getAudioTrack();if(this.eG()){if(!r.captionTracks.length)return!1;if(!this.G)return!0}r=WU9(r,g.VO(this.yH));return r==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:r==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?Ql(this):Pg$(this)||Ql(this)?!0:oG_(this)};
g.C.load=function(){g.zu.prototype.load.call(this);this.V=this.getAudioTrack();if(this.G)this.X&&(this.a7.clear(),this.W?h09(this,!0):this.player.getPresentingPlayerType()!==3&&this.G.UZ(this.X,"json3",this.X_),this.W||this.n8||p6(this)||this.player.k5("captionschanged",g.Hk(this.X)));else{var r;this.Y==="OFFLINE"?r=new lK(this.player,this.videoData,this.getAudioTrack()):this.Y==="SABR_LIVE"?r=new lE6(this.videoData.G,this.player):this.Y==="LIVE"?r=new xK(this.videoData.G,this.player):this.Y==="INNERTUBE"?
r=new g.Tu(this.player,this.videoData,this.getAudioTrack()):r=new g.wz(this.player,this.videoData.JP,this.videoData.videoId,g.b3O(this.videoData),this.videoData.TE,this.videoData.eventId);this.G=r;g.S(this,this.G);this.G.A4(this.X_)}};
g.C.unload=function(){this.W&&this.X?h09(this,!1):(this.TQ&&g.Is(this.TQ),this.player.Zg("captions"),this.R7=[],this.G&&this.G.M$(),this.a7.clear(),this.QH&&this.player.Dg(this.QH),this.As());g.zu.prototype.unload.call(this);this.player.R$();this.player.k5("captionschanged",{})};
g.C.create=function(){this.Tl()&&this.load();var r;a:{var V,I,d;if(this.yH.U("web_player_nitrate_promo_tooltip")&&((V=this.videoData.getPlayerResponse())==null?0:(I=V.captions)==null?0:(d=I.playerCaptionsTracklistRenderer)==null?0:d.enableTouchCaptionsNitrate)){var a,f;if(V=(r=this.videoData.getPlayerResponse())==null?void 0:(a=r.captions)==null?void 0:(f=a.playerCaptionsTracklistRenderer)==null?void 0:f.captionTracks)for(r=g.H(V),a=r.next();!a.done;a=r.next())if(a=a.value,a.kind==="asr"&&a.languageCode===
"en"){r=!0;break a}}r=!1}r&&this.T.publish("showpromotooltip",this.L.element)};
g.C.Aa=function(){var r=WU9(this.player.getAudioTrack(),g.VO(this.yH));var V=r==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?uK(this,this.j):r==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&Ql(this)?m8(this):Pg$(this)||this.j||oG_(this)?uK(this,this.j):Ql(this)?m8(this):null;if(this.W||this.n8){var I=g.dz(this.G.X,!0);r=[];for(var d=0;d<I.length;d++){var a=I[d],f=g.rX("TRACK");f.setAttribute("kind","subtitles");f.setAttribute("label",g.Tp(a));f.setAttribute("srclang",g.wv(a));f.setAttribute("id",a.toString());
this.n8||f.setAttribute("src",this.G.X4(a,"vtt"));a===V&&f.setAttribute("default","1");r.push(f)}V=this.T.Sx();V.pz(r);r=g.J(V.YN());this.Qa&&this.GQ.K(r.textTracks,"change",this.Gy8)}else!this.X&&V&&P2(this,V),this.player.k5("onCaptionsTrackListChanged"),this.player.fJ("onApiChange")};
g.C.Gy8=function(){for(var r=g.J(this.T.Sx().YN()).textTracks,V=null,I=0;I<r.length;I++)if(r[I].mode==="showing")a:{V=g.dz(this.G.X,!0);for(var d=0;d<V.length;d++)if(V[d].toString()===r[I].id){V=V[d];break a}V=null}(this.loaded?this.X:null)!==V&&P2(this,V,!0)};
g.C.MIL=function(){!this.X&&this.W||this.unload()};
g.C.HV=function(r,V,I,d){if(r){var a;VM$(this,(a=this.X)!=null?a:void 0);this.G.FS()&&(this.R7=[],this.T.Zg("captions"),jE(this.p8),this.a7.reset());if(this.videoData.j7){var f;I=((f=I)!=null?f:0)+this.videoData.j7}r=this.a7.zL(r,V,I,d);if(this.Mk)for(V=g.H(r),I=V.next();!I.done;I=V.next())I=I.value,I.S=this.videoData.clientPlaybackNonce,I.kD=this.videoData.j7;V=!this.yH.U("html5_keep_caption_data_after_seek")&&(this.Y==="LIVE"||this.Y==="SABR_LIVE");this.player.Dg(r,void 0,V);!this.j||this.n8||p6(this)||
g.Ai(this.yH)||g.g$(this.yH)||g.ih(this.yH)||this.yH.n8==="shortspage"||this.player.isInline()||(g.Is(this.TQ),r=T76({f_:0,cO:5,v1:5,QU:2,textAlign:0,gy:0,lang:"en-GB"}),this.Ws=[r],V=["Click "," for settings"],this.DM||(I=new g.cL(g.lm()),g.S(this,I),this.DM=I.element),I=r.end-r.start,(d=g.Tp(this.X))&&this.Ws.push(new wO(r.start,I,0,r.id,d)),this.Ws.push(new wO(r.start,I,0,r.id,V[0]),new wO(r.start,I,0,r.id,this.DM,!0),new wO(r.start,I,0,r.id,V[1],!0)),this.player.Dg(this.Ws),g.r3(this.TQ));!this.j||
this.n8||p6(this)||(g.VO(this.yH)?v2(this,!0):qg(this,!0),this.V&&(this.V.Y=this.X),this.player.R$());this.j=!1}};
g.C.onCueRangeEnter=function(r){this.R7.push(r);jE(this.p8)};
g.C.onCueRangeExit=function(r){g.H9(this.R7,r);this.G instanceof xK&&this.G.L&&this.player.e$([r]);jE(this.p8)};
g.C.getCaptionWindowContainerId=function(){return this.L.element.id};
g.C.mpH=function(){esc(this,this.Ws);this.Ws=null};
g.C.v6=function(){var r=this;if(!this.rH||!this.W){this.p8.stop();g.ZgO(this.L8);this.R7.sort(g.Yj);var V=this.R7;if(this.QH){var I=g.Z_(V,function(f){return this.QH.indexOf(f)===-1},this);
I.length&&(V=I)}V=g.H(V);for(I=V.next();!I.done;I=V.next())dSG(this,I.value);V=g.H(Object.entries(this.bL));var d=V.next();for(I={};!d.done;I={vD:void 0,Xc:void 0},d=V.next()){var a=g.H(d.value);d=a.next().value;a=a.next().value;I.vD=d;I.Xc=a;this.L8[I.vD]?(I.Xc.element.parentNode||(I.Xc instanceof gO||I.Xc instanceof L6||g.mK(this.bL,function(f){return function(e,n){n!==f.vD&&e.X.params.f_===f.Xc.X.params.f_&&e.X.params.cO===f.Xc.X.params.cO&&e.X.params.v1===f.Xc.X.params.v1&&(e.dispose(),delete r.bL[n]);
return n===f.vD}}(I),this),this.L.element.appendChild(I.Xc.element)),I.Xc.sW(this.L8[I.vD])):(I.Xc.dispose(),delete this.bL[I.vD])}}};
g.C.SjC=function(){vGp(this,{},!0);this.player.k5("captionssettingschanged")};
g.C.SZ=function(){var r=ok.wm;r={background:r.background,backgroundOpacity:r.backgroundOpacity,charEdgeStyle:r.charEdgeStyle,color:r.color,fontFamily:r.fontFamily,fontSizeIncrement:r.fontSizeIncrement,fontStyle:r.bold&&r.italic?3:r.bold?1:r.italic?2:0,textOpacity:r.textOpacity,windowColor:ok.windowColor,windowOpacity:ok.windowOpacity};var V=lSo()||{};V.background!=null&&(r.background=V.background);V.backgroundOverride!=null&&(r.backgroundOverride=V.backgroundOverride);V.backgroundOpacity!=null&&(r.backgroundOpacity=
V.backgroundOpacity);V.backgroundOpacityOverride!=null&&(r.backgroundOpacityOverride=V.backgroundOpacityOverride);V.charEdgeStyle!=null&&(r.charEdgeStyle=V.charEdgeStyle);V.charEdgeStyleOverride!=null&&(r.charEdgeStyleOverride=V.charEdgeStyleOverride);V.color!=null&&(r.color=V.color);V.colorOverride!=null&&(r.colorOverride=V.colorOverride);V.fontFamily!=null&&(r.fontFamily=V.fontFamily);V.fontFamilyOverride!=null&&(r.fontFamilyOverride=V.fontFamilyOverride);V.fontSizeIncrement!=null&&(r.fontSizeIncrement=
V.fontSizeIncrement);V.fontSizeIncrementOverride!=null&&(r.fontSizeIncrementOverride=V.fontSizeIncrementOverride);V.fontStyle!=null&&(r.fontStyle=V.fontStyle);V.fontStyleOverride!=null&&(r.fontStyleOverride=V.fontStyleOverride);V.textOpacity!=null&&(r.textOpacity=V.textOpacity);V.textOpacityOverride!=null&&(r.textOpacityOverride=V.textOpacityOverride);V.windowColor!=null&&(r.windowColor=V.windowColor);V.windowColorOverride!=null&&(r.windowColorOverride=V.windowColorOverride);V.windowOpacity!=null&&
(r.windowOpacity=V.windowOpacity);V.windowOpacityOverride!=null&&(r.windowOpacityOverride=V.windowOpacityOverride);return r};
g.C.Mj=function(r,V){var I={};Object.assign(I,lSo());Object.assign(I,r);vGp(this,I,V);this.player.k5("captionssettingschanged")};
g.C.As=function(){!this.W&&this.loaded&&(g.i$(this.bL,function(r,V){r.dispose();delete this.bL[V]},this),this.v6())};
g.C.Ha=function(r,V){switch(r){case "fontSize":if(isNaN(V))break;r=g.yv(V,-2,4);this.Mj({fontSizeIncrement:r});return r;case "reload":V&&!this.W&&P2(this,this.X,!0);break;case "stickyLoading":V!==void 0&&this.yH.j&&(g.VO(this.yH)?v2(this,!!V):qg(this,!!V));break;case "track":return f_$(this,V);case "tracklist":return this.G?g.uE(g.dz(this.G.X,!(!V||!V.includeAsr)),function(I){return g.Hk(I)}):[];
case "translationLanguages":return this.G?this.G.W.map(function(I){return Object.assign({},I)}):[];
case "sampleSubtitles":this.W||V===void 0||Yue(this,!!V);break;case "sampleSubtitlesCustomized":this.W||Yue(this,!!V,V);break;case "recommendedTranslationLanguages":return g.rV();case "defaultTranslationSourceTrackIndices":return this.G?this.G.j:[]}};
g.C.getOptions=function(){var r="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.yH.j&&r.push("stickyLoading");return r};
g.C.qv=function(){var r=this.X;if(this.T.LC("captions")){if(this.yH.U("html5_modify_caption_vss_logging")){var V;return(r=(V=this.videoData.BU)!=null?V:null)?{cc:g.Bhj(r)}:{}}if(r)return V=r.vssId,r.translationLanguage&&V&&(V="t"+V+"."+g.wv(r)),{cc:V}}return{}};
g.C.UYz=function(){this.isSubtitlesOn()?(g.VO(this.yH)?v2(this,!1):qg(this,!1),VM$(this),P2(this,null,!0)):this.Yk()};
g.C.Yk=function(){var r=p6(this)||!this.X?uK(this,!0):this.X;r&&this.AZ(r.vssId,"m");this.isSubtitlesOn()||P2(this,p6(this)||!this.X?uK(this,!0):this.X,!0)};
g.C.isSubtitlesOn=function(){return!!this.loaded&&!!this.X&&!p6(this)};
g.C.KK8=function(){var r=p6(this);Ql(this,r)?P2(this,this.getAudioTrack().G,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.eG()&&(this.j=!1,this.X=null,this.G&&(this.G.dispose(),this.G=null)),this.Tl()&&(r?P2(this,uK(this,!1),!1):this.load()))};
g.C.Dx=function(r){r&&(this.kc={top:r.top,right:r.right,bottom:r.bottom,left:r.left,width:1-r.left-r.right,height:1-r.top-r.bottom},this.L.element.style.top=this.kc.top*100+"%",this.L.element.style.left=this.kc.left*100+"%",this.L.element.style.width=this.kc.width*100+"%",this.L.element.style.height=this.kc.height*100+"%",this.L.element.style.position="absolute",r=a_c(this))&&(this.L.element.style.width=r.width+"px",this.L.element.style.height=r.height+"px")};
g.C.onVideoDataChange=function(r,V){r==="newdata"&&(this.videoData=V,this.loaded&&this.unload(),this.j=!1,this.X=null,this.G&&(this.G.dispose(),this.G=null,this.player.k5("captionschanged",{})),this.Tl()&&this.load())};
g.C.getAudioTrack=function(){return this.Mk&&this.player.getPresentingPlayerType()===2?this.videoData.eA:this.player.getAudioTrack()};
g.C.py8=function(){var r=this.T.Sx();r&&!r.h0()&&r.aN();this.T.isFullscreen()?(this.W=this.EE=!0,this.loaded&&this.Aa()):(this.EE=this.yH.controlsType==="3",this.W=pep(this));P2(this,this.X)};
g.C.YO=function(){var r,V,I,d=(r=this.videoData.getPlayerResponse())==null?void 0:(V=r.captions)==null?void 0:(I=V.playerCaptionsTracklistRenderer)==null?void 0:I.openTranscriptCommand;d&&this.player.Bs("innertubeCommand",d)};
g.C.OI=function(r,V,I){var d=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,a="";r&&(a=r.vssId,a=a.replace(d,""));var f="";r&&r.getId()&&(f=r.getId()||"");r&&r.getXtags()&&(r=r.getXtags(),r=r.replace(d,""),f=f.concat(";"+r));this.T.OI(V?a:"",V?f:"",I)};
g.C.AZ=function(r,V){r=(r||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");r.length>0&&this.T.AZ(r,V)};
g.C.ZB=function(){this.G&&this.G.ZB()};
g.lM.NO(U2,{v6:"smucd"});g.cD("captions",U2);})(_yt_player);
