(function(g){var window=this;'use strict';var gee=function(r){r.publish("autonavvisibility")},Su$=function(r,V){r.Bs("onAutonavCoundownStarted",V)},i$K=function(r){var V,I,d;
return r==null?void 0:(V=r.playerOverlays)==null?void 0:(I=V.playerOverlayRenderer)==null?void 0:(d=I.autoplay)==null?void 0:d.playerOverlayAutoplayRenderer},fu=function(r,V,I){g.NA(r.element,"ytp-suggestion-set",!!V.videoId);
var d=V.playlistId;I=V.YG(I?I:"mqdefault.jpg");var a=null,f=null;V instanceof g.yO&&(V.lengthText?(a=V.lengthText||null,f=V.E4||null):V.lengthSeconds&&(a=g.tt(V.lengthSeconds),f=g.tt(V.lengthSeconds,!0)));var e=!!d;d=e&&g.RU(d).type==="RD";var n=V instanceof g.yO?V.isLivePlayback:null,D=V instanceof g.yO?V.isUpcoming:null,x=V.author,E=V.shortViewCount,N=V.publishedTimeText,c=[],z=[];x&&c.push(x);E&&(c.push(E),z.push(E));N&&z.push(N);I={title:V.title,author:x,author_and_views:c.join(" \u2022 "),aria_label:V.ariaLabel||
g.Tj("Watch $TITLE",{TITLE:V.title}),duration:a,timestamp:f,url:V.Iv(),is_live:n,is_upcoming:D,is_list:e,is_mix:d,background:I?"background-image: url("+I+")":"",views_and_publish_time:z.join(" \u2022 "),autoplayAlternativeHeader:V.KY};V instanceof g.tI&&(I.playlist_length=V.playlistLength);r.update(I)},eV=function(r){var V=r.N(),I=V.Y;
g.u.call(this,{J:"a",Z:"ytp-autonav-suggestion-card",D:{href:"{{url}}",target:I?V.V:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},B:[{J:"div",Yc:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],D:{style:"{{background}}"},B:[{J:"div",D:{"aria-label":"{{timestamp}}"},Yc:["ytp-autonav-timestamp"],OE:"{{duration}}"},{J:"div",Yc:["ytp-autonav-live-stamp"],OE:"Live"},{J:"div",
Yc:["ytp-autonav-upcoming-stamp"],OE:"Upcoming"},{J:"div",Z:"ytp-autonav-list-overlay",B:[{J:"div",Z:"ytp-autonav-mix-text",OE:"Mix"},{J:"div",Z:"ytp-autonav-mix-icon"}]}]},{J:"div",Yc:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],OE:"{{title}}"},{J:"div",Yc:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],OE:"{{author}}"},{J:"div",Yc:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],OE:"{{views_and_publish_time}}"}]});this.T=r;this.suggestion=
null;this.G=I;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},Y3=function(r,V){V=V===void 0?!1:V;
g.u.call(this,{J:"div",Z:"ytp-autonav-endscreen-countdown-overlay"});var I=this;this.L=V;this.cancelCommand=this.C=void 0;this.S=0;this.container=new g.u({J:"div",Z:"ytp-autonav-endscreen-countdown-container"});g.S(this,this.container);this.container.Xz(this.element);V=r.N();var d=V.Y;this.T=r;this.suggestion=null;this.onVideoDataChange("newdata",g.J(this.T.getVideoData()));this.K(r,"videodatachange",this.onVideoDataChange);this.G=new g.u({J:"div",Z:"ytp-autonav-endscreen-upnext-container",D:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},B:[{J:"div",Z:"ytp-autonav-endscreen-upnext-header"},{J:"div",Z:"ytp-autonav-endscreen-upnext-alternative-header",OE:"{{autoplayAlternativeHeader}}"},{J:"a",Z:"ytp-autonav-endscreen-link-container",D:{href:"{{url}}",target:d?V.V:""},B:[{J:"div",Z:"ytp-autonav-endscreen-upnext-thumbnail",D:{style:"{{background}}"},B:[{J:"div",D:{"aria-label":"{{timestamp}}"},Yc:["ytp-autonav-timestamp"],
OE:"{{duration}}"},{J:"div",Yc:["ytp-autonav-live-stamp"],OE:"Live"},{J:"div",Yc:["ytp-autonav-upcoming-stamp"],OE:"Upcoming"}]},{J:"div",Z:"ytp-autonav-endscreen-video-info",B:[{J:"div",Z:"ytp-autonav-endscreen-premium-badge"},{J:"div",Z:"ytp-autonav-endscreen-upnext-title",OE:"{{title}}"},{J:"div",Z:"ytp-autonav-endscreen-upnext-author",OE:"{{author}}"},{J:"div",Z:"ytp-autonav-view-and-date",OE:"{{views_and_publish_time}}"},{J:"div",Z:"ytp-autonav-author-and-view",OE:"{{author_and_views}}"}]}]}]});
g.S(this,this.G);this.G.Xz(this.container.element);d||this.K(this.G.Fz("ytp-autonav-endscreen-link-container"),"click",this.Rn);this.T.createClientVe(this.container.element,this,115127);this.T.createClientVe(this.G.Fz("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.u({J:"div",Z:"ytp-autonav-overlay"});g.S(this,this.overlay);this.overlay.Xz(this.container.element);this.X=new g.u({J:"div",Z:"ytp-autonav-endscreen-button-container"});g.S(this,this.X);this.X.Xz(this.container.element);
this.cancelButton=new g.u({J:"button",Yc:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",V.U("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],D:{"aria-label":"Cancel auto-play"},OE:"Cancel"});g.S(this,this.cancelButton);this.cancelButton.Xz(this.X.element);this.cancelButton.listen("click",this.Pm,this);this.T.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.u({J:"a",Yc:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
V.U("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],D:{href:"{{url}}",role:"button","aria-label":"Play next video"},OE:"Play now"});g.S(this,this.playButton);this.playButton.Xz(this.X.element);this.playButton.listen("click",this.Rn,this);this.T.createServerVe(this.playButton.element,this.playButton,!0);(V=this.T.getVideoData())&&USe(this,V);this.Y=new g.hz(function(){QmY(I)},500);
g.S(this,this.Y);this.hA();this.K(r,"autonavvisibility",this.hA);this.T.U("web_autonav_color_transition")&&(this.K(r,"autonavchange",this.Vv),this.K(r,"onAutonavCoundownStarted",this.jTM))},nu=function(r){var V=r.T.gL(!0,r.T.isFullscreen());
g.NA(r.container.element,"ytp-autonav-endscreen-small-mode",r.Qx(V));g.NA(r.container.element,"ytp-autonav-endscreen-is-premium",!!r.suggestion&&!!r.suggestion.VrM);g.NA(r.T.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!r.T.oB());g.NA(r.T.getRootNode(),"countdown-running",r.Ed());g.NA(r.container.element,"ytp-player-content",r.T.oB());g.Be(r.overlay.element,{width:V.width+"px"});if(!r.Ed()){r.T.oB()?mSm(r,Math.round(unp(r)/1E3)):mSm(r);V=!!r.suggestion&&!!r.suggestion.KY;var I=r.T.oB()||
!V;g.NA(r.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!I&&V);g.NA(r.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",I&&!V);r.X.Ok(r.T.oB());g.NA(r.element,"ytp-enable-w2w-color-transitions",pn$(r))}},QmY=function(r){var V=unp(r),I=Math,d=I.min;
var a=r.S?Date.now()-r.S:0;I=d.call(I,a,V);mSm(r,Math.ceil((V-I)/1E3));V-I<=500&&r.Ed()?r.select(!0):r.Ed()&&r.Y.start()},unp=function(r){if(r.T.isFullscreen()){var V;
r=(V=r.T.getVideoData())==null?void 0:V.qn;return r===-1||r===void 0?8E3:r}return r.T.QT()>=0?r.T.QT():g.zM(r.T.N().experiments,"autoplay_time")||1E4},USe=function(r,V){V=V.getWatchNextResponse();
var I,d;V=(I=i$K(V))==null?void 0:(d=I.nextButton)==null?void 0:d.buttonRenderer;r.C=V==null?void 0:V.navigationEndpoint;I=V==null?void 0:V.trackingParams;r.playButton&&I&&r.T.setTrackingParams(r.playButton.element,I)},pn$=function(r){var V;
return!((V=r.T.getVideoData())==null||!V.watchToWatchTransitionRenderer)},mSm=function(r,V){V=V===void 0?-1:V;
r=r.G.Fz("ytp-autonav-endscreen-upnext-header");g.dX(r);if(V>=0){V=String(V);var I="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(I);if(d>=0){r.appendChild(g.VE("Up next in $SECONDS".slice(0,d)));var a=g.rX("span");g.YS(a,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Yx(a,V);r.appendChild(a);r.appendChild(g.VE("Up next in $SECONDS".slice(d+I.length)));return}}g.Yx(r,"Up next")},jV=function(r,V){g.u.call(this,{J:"div",
Yc:["html5-endscreen","ytp-player-content",V||"base-endscreen"]});this.created=!1;this.player=r},DG=function(r){g.u.call(this,{J:"div",
Yc:["ytp-upnext","ytp-player-content"],D:{"aria-label":"{{aria_label}}"},B:[{J:"div",Z:"ytp-cued-thumbnail-overlay-image",D:{style:"{{background}}"}},{J:"span",Z:"ytp-upnext-top",B:[{J:"span",Z:"ytp-upnext-header",OE:"Up Next"},{J:"span",Z:"ytp-upnext-title",OE:"{{title}}"},{J:"span",Z:"ytp-upnext-author",OE:"{{author}}"}]},{J:"a",Z:"ytp-upnext-autoplay-icon",D:{role:"button",href:"{{url}}","aria-label":"Play next video"},B:[{J:"svg",D:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
B:[{J:"circle",Z:"ytp-svg-autoplay-circle",D:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{J:"circle",Z:"ytp-svg-autoplay-ring",D:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{J:"path",Z:"ytp-svg-fill",D:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{J:"span",Z:"ytp-upnext-bottom",B:[{J:"span",Z:"ytp-upnext-cancel"},{J:"span",Z:"ytp-upnext-paused",
OE:"Auto-play is paused"}]}]});this.api=r;this.cancelButton=null;this.C=this.Fz("ytp-svg-autoplay-ring");this.S=this.notification=this.G=this.suggestion=null;this.Y=new g.hz(this.Oh,5E3,this);this.X=0;var V=this.Fz("ytp-upnext-cancel");this.cancelButton=new g.u({J:"button",Yc:["ytp-upnext-cancel-button","ytp-button"],D:{tabindex:"0","aria-label":"Cancel auto-play"},OE:"Cancel"});g.S(this,this.cancelButton);this.cancelButton.listen("click",this.yS,this);this.cancelButton.Xz(V);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.S(this,this.Y);this.api.createClientVe(this.element,this,18788);V=this.Fz("ytp-upnext-autoplay-icon");this.K(V,"click",this.HC);this.api.createClientVe(V,this,115130);this.sA();this.K(r,"autonavvisibility",this.sA);this.K(r,"mdxnowautoplaying",this.t40);this.K(r,"mdxautoplaycanceled",this.hpM);g.NA(this.element,"ytp-upnext-mobile",this.api.N().X)},vem=function(r,V){if(V)return V;
if(r.api.isFullscreen()){var I;r=(I=r.api.getVideoData())==null?void 0:I.qn;return r===-1||r===void 0?8E3:r}return r.api.QT()>=0?r.api.QT():g.zM(r.api.N().experiments,"autoplay_time")||1E4},quc=function(r,V){V=vem(r,V);
var I=Math,d=I.min;var a=(0,g.m)()-r.X;I=d.call(I,a,V);V=V===0?1:Math.min(I/V,1);r.C.setAttribute("stroke-dashoffset",""+-211*(V+1));V>=1&&r.Ed()&&r.api.getPresentingPlayerType()!==3?r.select(!0):r.Ed()&&r.G.start()},x3=function(r){jV.call(this,r,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.u({J:"div",Z:"ytp-suggestion-panel",B:[{J:"div",Yc:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],OE:"More videos"}]});this.j=new g.u({J:"div",Z:"ytp-suggestions-container"});this.videos=[];this.S=null;this.C=this.L=!1;this.X=new Y3(this.player);g.S(this,this.X);this.X.Xz(this.element);r.getVideoData().ll?this.G=this.X:(this.G=new DG(r),g.g1(this.player,this.G.element,4),g.S(this,this.G));this.overlay=new g.u({J:"div",
Z:"ytp-autonav-overlay-cancelled-state"});g.S(this,this.overlay);this.overlay.Xz(this.element);this.Y=new g.Su(this);g.S(this,this.Y);g.S(this,this.table);this.table.Xz(this.element);this.table.show();g.S(this,this.j);this.j.Xz(this.table.element);this.hide()},EE=function(r){var V=r.oB();
V!==r.C&&(r.C=V,gee(r.player),r.C?(r.X!==r.G&&r.X.hide(),r.table.hide()):(r.X!==r.G&&r.X.show(),r.table.show()))},NV=function(r,V){g.u.call(this,{J:"button",
Yc:["ytp-watch-on-youtube-button","ytp-button"],OE:"{{content}}"});this.T=r;this.buttonType=this.buttonType=V;this.N1();this.buttonType===2&&g.jN(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.N1);this.Ok(!0)},sE=function(r,V){jV.call(this,r,"embeds-lite-endscreen");
this.T=r;this.G=V;this.T.createClientVe(this.element,this,156943);this.watchButton=new NV(r,2);g.S(this,this.watchButton);this.watchButton.Xz(this.element);this.hide()},cO=function(r){var V=r.N(),I=g.Zk||g.AK?{style:"will-change: opacity"}:void 0,d=V.Y,a=["ytp-modern-videowall-still"];
V.X&&a.push("ytp-videowall-show-text");g.u.call(this,{J:"a",Yc:a,D:{href:"{{url}}",target:d?V.V:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},B:[{J:"div",Z:"ytp-modern-videowall-still-image",D:{style:"{{background}}"},B:[{J:"span",Z:"ytp-modern-videowall-still-info-duration",OE:"{{duration}}"}]},{J:"span",Z:"ytp-modern-videowall-still-info",D:{"aria-hidden":"true"},B:[{J:"span",Z:"ytp-modern-videowall-still-info-bg",B:[{J:"span",
Z:"ytp-modern-videowall-still-info-content",D:I,B:[{J:"span",Z:"ytp-modern-videowall-still-info-title",OE:"{{title}}"},{J:"span",Z:"ytp-modern-videowall-still-info-author",OE:"{{author_and_views}}"},{J:"span",Z:"ytp-modern-videowall-still-info-live",OE:"Live"}]}]}]},{J:"span",Yc:["ytp-modern-videowall-still-listlabel-regular","ytp-modern-videowall-still-listlabel"],D:{"aria-hidden":"true"},B:[{J:"span",Z:"ytp-modern-videowall-still-listlabel-icon"},"Playlist",{J:"span",Z:"ytp-modern-videowall-still-listlabel-length",
B:[" (",{J:"span",OE:"{{playlist_length}}"},")"]}]},{J:"span",Yc:["ytp-modern-videowall-still-listlabel-mix","ytp-modern-videowall-still-listlabel"],D:{"aria-hidden":"true"},B:[{J:"span",Z:"ytp-modern-videowall-still-listlabel-mix-icon"},"Mix",{J:"span",Z:"ytp-modern-videowall-still-listlabel-length",OE:" (50+)"}]}]});this.suggestion=null;this.X=d;this.api=r;this.G=new g.Su(this);g.S(this,this.G);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.G.K(r,"videodatachange",
this.onVideoDataChange);r.createServerVe(this.element,this);this.onVideoDataChange()},PvY=function(r){jV.call(this,r,"videowall-endscreen");
var V=this;this.T=r;this.stills=[];this.S=this.videoData=null;this.Y=this.L=!1;this.j=null;g.jN(this.element,"modern-videowall-endscreen");this.X=new g.Su(this);g.S(this,this.X);this.C=new g.hz(function(){g.jN(V.element,"ytp-show-tiles")},0);
g.S(this,this.C);this.table=new g.cL({J:"div",Z:"ytp-modern-endscreen-content"});g.S(this,this.table);this.table.Xz(this.element);r.getVideoData().ll?this.G=new Y3(r,!0):this.G=new DG(r);g.S(this,this.G);g.g1(this.player,this.G.element,4);r.createClientVe(this.element,this,158789);this.hide()},zf=function(r){return g.S$(r.player)&&r.zp()&&!r.S},MV=function(r){var V=r.oB();
V!==r.L&&(r.L=V,gee(r.player))},oeG=function(r){jV.call(this,r,"subscribecard-endscreen");
this.G=new g.u({J:"div",Z:"ytp-subscribe-card",B:[{J:"img",Z:"ytp-author-image",D:{src:"{{profilePicture}}"}},{J:"div",Z:"ytp-subscribe-card-right",B:[{J:"div",Z:"ytp-author-name",OE:"{{author}}"},{J:"div",Z:"html5-subscribe-button-container"}]}]});g.S(this,this.G);this.G.Xz(this.element);var V=r.getVideoData();this.subscribeButton=new g.PD("Subscribe",null,"Unsubscribe",null,!0,!1,V.Sz,V.subscribed,"trailer-endscreen",null,r,!1);g.S(this,this.subscribeButton);this.subscribeButton.Xz(this.G.Fz("html5-subscribe-button-container"));
this.K(r,"videodatachange",this.UE);this.UE();this.hide()},Cu=function(r){var V=r.N(),I=g.Zk||g.AK?{style:"will-change: opacity"}:void 0,d=V.Y,a=["ytp-videowall-still"];
V.X&&a.push("ytp-videowall-show-text");g.u.call(this,{J:"a",Yc:a,D:{href:"{{url}}",target:d?V.V:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},B:[{J:"div",Z:"ytp-videowall-still-image",D:{style:"{{background}}"}},{J:"span",Z:"ytp-videowall-still-info",D:{"aria-hidden":"true"},B:[{J:"span",Z:"ytp-videowall-still-info-bg",B:[{J:"span",Z:"ytp-videowall-still-info-content",D:I,B:[{J:"span",Z:"ytp-videowall-still-info-title",OE:"{{title}}"},
{J:"span",Z:"ytp-videowall-still-info-author",OE:"{{author_and_views}}"},{J:"span",Z:"ytp-videowall-still-info-live",OE:"Live"},{J:"span",Z:"ytp-videowall-still-info-duration",OE:"{{duration}}"}]}]}]},{J:"span",Yc:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],D:{"aria-hidden":"true"},B:[{J:"span",Z:"ytp-videowall-still-listlabel-icon"},"Playlist",{J:"span",Z:"ytp-videowall-still-listlabel-length",B:[" (",{J:"span",OE:"{{playlist_length}}"},")"]}]},{J:"span",Yc:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],D:{"aria-hidden":"true"},B:[{J:"span",Z:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{J:"span",Z:"ytp-videowall-still-listlabel-length",OE:" (50+)"}]}]});this.suggestion=null;this.X=d;this.api=r;this.G=new g.Su(this);g.S(this,this.G);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.G.K(r,"videodatachange",this.onVideoDataChange);r.createServerVe(this.element,this);this.onVideoDataChange()},Tf=function(r){jV.call(this,r,"videowall-endscreen");
var V=this;this.T=r;this.S=0;this.stills=[];this.Y=this.videoData=null;this.C=this.j=!1;this.V=null;this.X=new g.Su(this);g.S(this,this.X);this.L=new g.hz(function(){g.jN(V.element,"ytp-show-tiles")},0);
g.S(this,this.L);var I=new g.u({J:"button",Yc:["ytp-button","ytp-endscreen-previous"],D:{"aria-label":"Previous"},B:[g.WL()]});g.S(this,I);I.Xz(this.element);I.listen("click",this.wi,this);this.table=new g.cL({J:"div",Z:"ytp-endscreen-content"});g.S(this,this.table);this.table.Xz(this.element);I=new g.u({J:"button",Yc:["ytp-button","ytp-endscreen-next"],D:{"aria-label":"Next"},B:[g.$5()]});g.S(this,I);I.Xz(this.element);I.listen("click",this.ri,this);r.getVideoData().ll?this.G=new Y3(r,!0):this.G=
new DG(r);g.S(this,this.G);g.g1(this.player,this.G.element,4);r.createClientVe(this.element,this,158789);this.hide()},HO=function(r){return g.S$(r.player)&&r.zp()&&!r.Y},wp=function(r){var V=r.oB();
V!==r.j&&(r.j=V,gee(r.player))},bu=function(r){jV.call(this,r,"watch-again-on-youtube-endscreen");
this.watchButton=new NV(r,1);g.S(this,this.watchButton);this.watchButton.Xz(this.element);g.qi$(r)&&(this.G=new g.kc(r),g.S(this,this.G),this.X=new g.u({J:"div",Yc:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],D:{tabIndex:"-1"},B:[this.G]}),g.S(this,this.X),this.G.Xz(this.X.element),this.X.Xz(this.element));r.createClientVe(this.element,this,156914);this.hide()},VwY=function(r){g.zu.call(this,r);
var V=this;this.endScreen=null;this.X=this.G=this.S=this.Y=!1;this.listeners=new g.Su(this);g.S(this,this.listeners);var I=r.N(),d=r.getVideoData();d=d&&d.limitedPlaybackDurationInSeconds!==0;g.s3(g.UL(I))&&d&&!g.J6(r)?(this.X=!0,this.endScreen=new sE(r,g.w1(r))):r.isEmbedsShortsMode()?this.endScreen=new bu(r):kqY(r)?(this.Y=!0,hs_(this),this.G?this.endScreen=new x3(r):I.U("delhi_modern_endscreen")?this.endScreen=new PvY(r):this.endScreen=new Tf(r)):I.fn?this.endScreen=new oeG(r):this.endScreen=new jV(r);
g.S(this,this.endScreen);g.g1(r,this.endScreen.element,4);rEK(this);this.listeners.K(r,"videodatachange",this.onVideoDataChange,this);this.listeners.K(r,g.nv("endscreen"),function(a){V.onCueRangeEnter(a)});
this.listeners.K(r,g.jx("endscreen"),function(a){V.onCueRangeExit(a)})},hs_=function(r){var V=r.player.getVideoData();
if(!V||r.G===V.Rk&&r.S===V.ll)return!1;r.G=V.Rk;r.S=V.ll;return!0},kqY=function(r){r=r.N();
return r.CF&&!r.fn&&!r.disableOrganicUi},rEK=function(r){r.player.Zg("endscreen");
var V=r.player.getVideoData();V=new g.ex(Math.max((V.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var I=new g.ex(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});r.player.Dg([V,I])};
g.Gm.prototype.QT=g.ei(14,function(){return this.app.QT()});
g.Mh.prototype.QT=g.ei(13,function(){return this.getVideoData().Rj});
g.Rf.prototype.bf=g.ei(12,function(r){this.El().bf(r)});
g.Dt.prototype.bf=g.ei(11,function(r){this.G!==r&&(this.G=r,this.UE())});
g.tx.prototype.bf=g.ei(10,function(r){this.overflowButton&&this.overflowButton.bf(r)});
g.Rf.prototype.m6=g.ei(9,function(r){this.El().m6(r)});
g.zx.prototype.m6=g.ei(8,function(r){this.X!==r&&(this.X=r,this.UE())});
g.tx.prototype.m6=g.ei(7,function(r){this.shareButton&&this.shareButton.m6(r)});
g.Rf.prototype.Jf=g.ei(6,function(r){this.El().Jf(r)});
g.Uk.prototype.Jf=g.ei(5,function(r){this.Vr!==r&&(this.Vr=r,this.LR())});
g.Rf.prototype.p5=g.ei(4,function(r){this.El().p5(r)});
g.tx.prototype.p5=g.ei(3,function(r){this.D_!==r&&(this.D_=r,this.zA())});g.T(eV,g.u);eV.prototype.select=function(){this.T.hO(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.kT||void 0)&&this.T.logClick(this.element)};
eV.prototype.onClick=function(r){g.xu(r,this.T,this.G,this.suggestion.sessionData||void 0)&&this.select()};
eV.prototype.onKeyPress=function(r){switch(r.keyCode){case 13:case 32:r.defaultPrevented||(this.select(),r.preventDefault())}};g.T(Y3,g.u);g.C=Y3.prototype;g.C.TJ=function(r){this.suggestion!==r&&(this.suggestion=r,fu(this.G,r),this.playButton.updateValue("url",this.suggestion.Iv()),nu(this))};
g.C.Ed=function(){return this.S>0};
g.C.fT=function(){this.Ed()||(this.S=Date.now(),QmY(this),Su$(this.T,unp(this)),g.NA(this.T.getRootNode(),"countdown-running",this.Ed()))};
g.C.QG=function(){this.N$();QmY(this);var r=this.G.Fz("ytp-autonav-endscreen-upnext-header");r&&g.Yx(r,"Up next")};
g.C.N$=function(){this.Ed()&&(this.Y.stop(),this.S=0)};
g.C.select=function(r){this.T.nextVideo(!1,r===void 0?!1:r);this.N$()};
g.C.Rn=function(r){g.xu(r,this.T)&&(r.currentTarget===this.playButton.element?this.T.logClick(this.playButton.element):r.currentTarget===this.G.Fz("ytp-autonav-endscreen-link-container")&&(r=this.G.Fz("ytp-autonav-endscreen-link-container"),this.T.logVisibility(r,!0),this.T.logClick(r)),this.C?(this.T.Bs("innertubeCommand",this.C),this.N$()):this.select())};
g.C.Pm=function(){this.T.logClick(this.cancelButton.element);g.l5(this.T,!0);this.cancelCommand&&this.T.Bs("innertubeCommand",this.cancelCommand)};
g.C.onVideoDataChange=function(r,V){USe(this,V);r=V.getWatchNextResponse();var I,d;r=(I=i$K(r))==null?void 0:(d=I.cancelButton)==null?void 0:d.buttonRenderer;this.cancelCommand=r==null?void 0:r.command};
g.C.jTM=function(r){if(pn$(this)){var V=this.T.getVideoData().watchToWatchTransitionRenderer,I=V==null?void 0:V.fromColorPaletteDark;V=V==null?void 0:V.toColorPaletteDark;if(I&&V){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.QY(I.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.QY(I.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.QY(I.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.QY(V.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.QY(V.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.QY(V.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",r+"ms")}g.NA(this.element,"ytp-w2w-animate",!0)}};
g.C.Vv=function(r){this.T.U("web_autonav_color_transition")&&r!==2&&g.NA(this.element,"ytp-w2w-animate",!1)};
g.C.hA=function(){var r=this.T.oB();this.L&&this.Hp!==r&&this.Ok(r);nu(this);this.T.logVisibility(this.container.element,r);this.T.logVisibility(this.cancelButton.element,r);this.T.logVisibility(this.G.Fz("ytp-autonav-endscreen-link-container"),r);this.T.logVisibility(this.playButton.element,r)};
g.C.Qx=function(r){return r.width<400||r.height<459};g.T(jV,g.u);g.C=jV.prototype;g.C.create=function(){this.created=!0};
g.C.destroy=function(){this.created=!1};
g.C.zp=function(){return!1};
g.C.oB=function(){return!1};
g.C.To=function(){return!1};g.T(DG,g.u);g.C=DG.prototype;g.C.Oh=function(){this.notification&&(this.Y.stop(),this.pF(this.S),this.S=null,this.notification.close(),this.notification=null)};
g.C.TJ=function(r){this.suggestion=r;fu(this,r,"hqdefault.jpg")};
g.C.sA=function(){this.Ok(this.api.oB());this.api.logVisibility(this.element,this.api.oB());this.api.logVisibility(this.Fz("ytp-upnext-autoplay-icon"),this.api.oB());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.oB())};
g.C.zp0=function(){window.focus();this.Oh()};
g.C.fT=function(r){var V=this;this.Ed()||(g.xn("a11y-announce","Up Next "+this.suggestion.title),this.X=(0,g.m)(),this.G=new g.hz(function(){quc(V,r)},25),quc(this,r),Su$(this.api,vem(this,r)));
g.xS(this.element,"ytp-upnext-autoplay-paused")};
g.C.hide=function(){g.u.prototype.hide.call(this)};
g.C.Ed=function(){return!!this.G};
g.C.QG=function(){this.N$();this.X=(0,g.m)();quc(this);g.jN(this.element,"ytp-upnext-autoplay-paused")};
g.C.N$=function(){this.Ed()&&(this.G.dispose(),this.G=null)};
g.C.select=function(r){r=r===void 0?!1:r;if(this.api.N().U("autonav_notifications")&&r&&window.Notification&&typeof document.hasFocus==="function"){var V=Notification.permission;V==="default"?Notification.requestPermission():V!=="granted"||document.hasFocus()||(this.Oh(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.YG()}),this.S=this.K(this.notification,"click",this.zp0),this.Y.start())}this.N$();this.api.nextVideo(!1,r)};
g.C.HC=function(r){!g.eG(this.cancelButton.element,r.target)&&g.xu(r,this.api)&&(this.api.oB()&&this.api.logClick(this.Fz("ytp-upnext-autoplay-icon")),this.select())};
g.C.yS=function(){this.api.oB()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.l5(this.api,!0)};
g.C.t40=function(r){this.api.getPresentingPlayerType();this.show();this.fT(r)};
g.C.hpM=function(){this.api.getPresentingPlayerType();this.N$();this.hide()};
g.C.eC=function(){this.N$();this.Oh();g.u.prototype.eC.call(this)};g.T(x3,jV);g.C=x3.prototype;g.C.create=function(){jV.prototype.create.call(this);this.Y.K(this.player,"appresize",this.s8);this.Y.K(this.player,"onVideoAreaChange",this.s8);this.Y.K(this.player,"videodatachange",this.onVideoDataChange);this.Y.K(this.player,"autonavchange",this.Tq);this.Y.K(this.player,"onAutonavCancelled",this.QS);this.onVideoDataChange()};
g.C.show=function(){jV.prototype.show.call(this);(this.L||this.S&&this.S!==this.videoData.clientPlaybackNonce)&&g.l5(this.player,!1);g.S$(this.player)&&this.zp()&&!this.S?(EE(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.G.select(!0):this.G.fT():this.videoData.autonavState===3&&this.G.QG()):(g.l5(this.player,!0),EE(this));this.s8()};
g.C.hide=function(){jV.prototype.hide.call(this);this.G.QG();EE(this)};
g.C.s8=function(){var r=this.player.gL(!0,this.player.isFullscreen());EE(this);nu(this.X);g.NA(this.element,"ytp-autonav-cancelled-small-mode",this.Qx(r));g.NA(this.element,"ytp-autonav-cancelled-tiny-mode",this.vn(r));g.NA(this.element,"ytp-autonav-cancelled-mini-mode",r.width<=400||r.height<=360);this.overlay&&g.Be(this.overlay.element,{width:r.width+"px"});if(!this.C)for(r=0;r<this.videos.length;r++)g.NA(this.videos[r].element,"ytp-suggestion-card-with-margin",r%2===1)};
g.C.onVideoDataChange=function(){var r=this.player.getVideoData();if(this.videoData!==r&&r){this.videoData=r;if((r=this.videoData.suggestions)&&r.length||this.player.U("web_player_autonav_empty_suggestions_fix")){var V=g.aa(this.videoData);V&&(this.G.TJ(V),this.G!==this.X&&this.X.TJ(V))}if(r&&r.length)for(V=0;V<InG.length;++V){var I=InG[V];if(r&&r[I]){this.videos[V]=new eV(this.player);var d=this.videos[V];I=r[I];d.suggestion!==I&&(d.suggestion=I,fu(d,I));g.S(this,this.videos[V]);this.videos[V].Xz(this.j.element)}}this.s8()}};
g.C.Tq=function(r){r===1?(this.L=!1,this.S=this.videoData.clientPlaybackNonce,this.G.N$(),this.Hp&&this.s8()):(this.L=!0,this.oB()&&(r===2?this.G.fT():r===3&&this.G.QG()))};
g.C.QS=function(r){r?this.Tq(1):(this.S=null,this.L=!1)};
g.C.zp=function(){return this.videoData.autonavState!==1};
g.C.Qx=function(r){return(r.width<910||r.height<459)&&!this.vn(r)&&!(r.width<=400||r.height<=360)};
g.C.vn=function(r){return r.width<800&&!(r.width<=400||r.height<=360)};
g.C.oB=function(){return this.Hp&&g.S$(this.player)&&this.zp()&&!this.S};
var InG=[1,3,2,4];g.T(NV,g.u);g.C=NV.prototype;g.C.N1=function(){switch(this.buttonType){case 1:var r="Watch again on YouTube";var V=156915;break;case 2:r="Continue watching on YouTube";V=156942;break;default:r="Continue watching on YouTube",V=156942}this.update({content:r});this.T.hasVe(this.element)&&this.T.destroyVe(this.element);this.T.createClientVe(this.element,this,V)};
g.C.onClick=function(r){this.T.U("web_player_log_click_before_generating_ve_conversion_params")&&this.T.logClick(this.element);g.EH(this.getVideoUrl(),this.T,r);this.T.U("web_player_log_click_before_generating_ve_conversion_params")||this.T.logClick(this.element)};
g.C.getVideoUrl=function(){var r=!0;switch(this.buttonType){case 1:r=!0;break;case 2:r=!1}r=this.T.getVideoUrl(r,!1,!1,!0);var V=this.T.N();if(g.FG(V)){var I={};g.FG(V)&&g.zm(this.T,"addEmbedsConversionTrackingParams",[I]);r=g.Ly(r,I)}return r};
g.C.logVisibility=function(){this.T.logVisibility(this.element,this.Hp&&this.W)};
g.C.show=function(){g.u.prototype.show.call(this);this.logVisibility()};
g.C.hide=function(){g.u.prototype.hide.call(this);this.logVisibility()};
g.C.IT=function(r){g.u.prototype.IT.call(this,r);this.logVisibility()};g.T(sE,jV);sE.prototype.show=function(){this.player.getPlayerState()!==3&&(jV.prototype.show.call(this),this.G.p5(!0),this.G.m6(!0),this.T.N().MG||this.G.bf(!0),this.T.logVisibility(this.element,!0),this.watchButton.IT(!0))};
sE.prototype.hide=function(){jV.prototype.hide.call(this);this.G.p5(!1);this.G.m6(!1);this.G.bf(!1);this.T.logVisibility(this.element,!1);this.watchButton.IT(!1)};g.T(cO,g.u);cO.prototype.select=function(){this.api.hO(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.kT||void 0)&&this.api.logClick(this.element)};
cO.prototype.onClick=function(r){if(g.FG(this.api.N())&&this.api.U("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var V=this.suggestion.Iv(),I={};g.ZL(this.api,I);V=g.Ly(V,I);g.EH(V,this.api,r)}else g.xu(r,this.api,this.X,this.suggestion.sessionData||void 0)&&this.select()};
cO.prototype.onKeyPress=function(r){switch(r.keyCode){case 13:case 32:r.defaultPrevented||(this.select(),r.preventDefault())}};
cO.prototype.onVideoDataChange=function(){var r=this.api.getVideoData(),V=this.api.N();this.X=r.Mm?!1:V.Y};g.T(PvY,jV);g.C=PvY.prototype;g.C.create=function(){jV.prototype.create.call(this);var r=this.player.getVideoData();r&&(this.videoData=r);this.g0();this.X.K(this.player,"appresize",this.g0);this.X.K(this.player,"onVideoAreaChange",this.g0);this.X.K(this.player,"videodatachange",this.onVideoDataChange);this.X.K(this.player,"autonavchange",this.J$);this.X.K(this.player,"onAutonavCancelled",this.kx);r=this.videoData.autonavState;r!==this.j&&this.J$(r);this.X.K(this.element,"transitionend",this.OF)};
g.C.destroy=function(){g.lQ(this.X);g.cn(this.stills);this.stills=[];jV.prototype.destroy.call(this);g.xS(this.element,"ytp-show-tiles");this.C.stop();this.j=this.videoData.autonavState};
g.C.zp=function(){return this.videoData.autonavState!==1};
g.C.show=function(){var r=this.Hp;jV.prototype.show.call(this);g.xS(this.element,"ytp-show-tiles");this.player.N().X?g.Vj(this.C):this.C.start();(this.Y||this.S&&this.S!==this.videoData.clientPlaybackNonce)&&g.l5(this.player,!1);zf(this)?(MV(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.G.select(!0):this.G.fT():this.videoData.autonavState===3&&this.G.QG()):(g.l5(this.player,!0),MV(this));r!==this.Hp&&this.player.logVisibility(this.element,!0)};
g.C.hide=function(){var r=this.Hp;jV.prototype.hide.call(this);this.G.QG();MV(this);r!==this.Hp&&this.player.logVisibility(this.element,!1)};
g.C.OF=function(r){r.target===this.element&&this.g0()};
g.C.g0=function(){var r,V,I,d;var a=((r=this.videoData)==null?0:(V=r.suggestions)==null?0:V.length)?(I=this.videoData)==null?void 0:I.suggestions:[(d=this.videoData)==null?void 0:g.aa(d)];if(a.length){V=this.T.gL(!0,this.T.isFullscreen());r=Math.floor((V.width-64+16)/(g.yv(V.width*.27,250,450)+16));V=Math.min(3,Math.floor((V.height-64)/((V.width-64-(r-1)*16)/r*.5625+70)));g.E8(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.jN(this.element,"ytp-modern-endscreen-limit-rows-"+V);g.NA(this.element,"ytp-modern-endscreen-single-item",r===1);g.NA(this.element,"ytp-modern-endscreen-row-0",V===0);r=this.table.element;r.ariaLive="polite";this.G.TJ(g.aa(this.videoData));this.G instanceof Y3&&nu(this.G);g.NA(this.element,"ytp-endscreen-takeover",zf(this));MV(this);V=0;r.ariaBusy="true";I=a.length;for(d=0;d<I;d++){var f=d%I,e=this.stills[d];e||(e=new cO(this.player),this.stills[d]=e,r.appendChild(e.element));f=a[f];if(e.suggestion!==
f){e.suggestion=f;var n=e.api.N();fu(e,f,"hqdefault.jpg");if(g.FG(n)&&!e.api.U("web_player_log_click_before_generating_ve_conversion_params")){n=f.Iv();var D={};g.zm(e.api,"addEmbedsConversionTrackingParams",[D]);n=g.Ly(n,D);e.updateValue("url",n)}(f=(f=f.sessionData)&&f.itct)&&e.api.setTrackingParams(e.element,f)}V++}this.stills.length=V}};
g.C.onVideoDataChange=function(){var r=this.player.getVideoData(1);this.videoData!==r&&(r!=null&&g.aa(r)?(this.videoData=r,this.g0()):this.player.Hs("missg",{vid:(r==null?void 0:r.videoId)||"",cpn:(r==null?void 0:r.clientPlaybackNonce)||""}))};
g.C.To=function(){return this.G.Ed()};
g.C.J$=function(r){r===1?(this.Y=!1,this.S=this.videoData.clientPlaybackNonce,this.G.N$(),this.Hp&&this.g0()):(this.Y=!0,this.Hp&&zf(this)&&(r===2?this.G.fT():r===3&&this.G.QG()))};
g.C.kx=function(r){if(r){for(r=0;r<this.stills.length;r++)this.T.logVisibility(this.stills[r].element,!0);this.J$(1)}else this.S=null,this.Y=!1;this.g0()};
g.C.oB=function(){return this.Hp&&zf(this)};g.T(oeG,jV);oeG.prototype.UE=function(){var r=this.player.getVideoData();this.G.update({profilePicture:r.profilePicture,author:r.author});this.subscribeButton.channelId=r.Sz;var V=this.subscribeButton;r.subscribed?V.G():V.X()};g.T(Cu,g.u);Cu.prototype.select=function(){this.api.hO(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.kT||void 0)&&this.api.logClick(this.element)};
Cu.prototype.onClick=function(r){if(g.FG(this.api.N())&&this.api.U("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var V=this.suggestion.Iv(),I={};g.ZL(this.api,I);V=g.Ly(V,I);g.EH(V,this.api,r)}else g.xu(r,this.api,this.X,this.suggestion.sessionData||void 0)&&this.select()};
Cu.prototype.onKeyPress=function(r){switch(r.keyCode){case 13:case 32:r.defaultPrevented||(this.select(),r.preventDefault())}};
Cu.prototype.onVideoDataChange=function(){var r=this.api.getVideoData(),V=this.api.N();this.X=r.Mm?!1:V.Y};g.T(Tf,jV);g.C=Tf.prototype;g.C.create=function(){jV.prototype.create.call(this);var r=this.player.getVideoData();r&&(this.videoData=r);this.Me();this.X.K(this.player,"appresize",this.Me);this.X.K(this.player,"onVideoAreaChange",this.Me);this.X.K(this.player,"videodatachange",this.onVideoDataChange);this.X.K(this.player,"autonavchange",this.t$);this.X.K(this.player,"onAutonavCancelled",this.eh);r=this.videoData.autonavState;r!==this.V&&this.t$(r);this.X.K(this.element,"transitionend",this.mI)};
g.C.destroy=function(){g.lQ(this.X);g.cn(this.stills);this.stills=[];jV.prototype.destroy.call(this);g.xS(this.element,"ytp-show-tiles");this.L.stop();this.V=this.videoData.autonavState};
g.C.zp=function(){return this.videoData.autonavState!==1};
g.C.show=function(){var r=this.Hp;jV.prototype.show.call(this);g.xS(this.element,"ytp-show-tiles");this.player.N().X?g.Vj(this.L):this.L.start();(this.C||this.Y&&this.Y!==this.videoData.clientPlaybackNonce)&&g.l5(this.player,!1);HO(this)?(wp(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.G.select(!0):this.G.fT():this.videoData.autonavState===3&&this.G.QG()):(g.l5(this.player,!0),wp(this));r!==this.Hp&&this.player.logVisibility(this.element,!0)};
g.C.hide=function(){var r=this.Hp;jV.prototype.hide.call(this);this.G.QG();wp(this);r!==this.Hp&&this.player.logVisibility(this.element,!1)};
g.C.mI=function(r){r.target===this.element&&this.Me()};
g.C.Me=function(){var r,V,I,d;var a=((r=this.videoData)==null?0:(V=r.suggestions)==null?0:V.length)?(I=this.videoData)==null?void 0:I.suggestions:[(d=this.videoData)==null?void 0:g.aa(d)];if(a.length){g.jN(this.element,"ytp-endscreen-paginate");var f=this.T.gL(!0,this.T.isFullscreen());if(r=g.w1(this.T))r=r.tZ()?48:32,f.width-=r*2;var e=f.width/f.height;d=96/54;V=r=2;var n=Math.max(f.width/96,2),D=Math.max(f.height/54,2);I=a.length;var x=I*4;for(x-=4;x>0&&(r<n||V<D);){var E=r/2,N=V/2,c=r<=n-2&&x>=
N*4,z=V<=D-2&&x>=E*4;if((E+1)/N*d/e>e/(E/(N+1)*d)&&z)x-=E*4,V+=2;else if(c)x-=N*4,r+=2;else if(z)x-=E*4,V+=2;else break}d=!1;x>=12&&I*4-x<=6&&(V>=4||r>=4)&&(d=!0);x=r*96;n=V*54;e=x/n<e?f.height/n:f.width/x;e=Math.min(e,2);x=Math.floor(Math.min(f.width,x*e));n=Math.floor(Math.min(f.height,n*e));f=this.table.element;f.ariaLive="polite";g.qG(f,x,n);g.Be(f,{marginLeft:x/-2+"px",marginTop:n/-2+"px"});this.G.TJ(g.aa(this.videoData));this.G instanceof Y3&&nu(this.G);g.NA(this.element,"ytp-endscreen-takeover",
HO(this));wp(this);x+=4;n+=4;e=0;f.ariaBusy="true";for(D=0;D<r;D++)for(E=0;E<V;E++)if(N=e,z=0,d&&D>=r-2&&E>=V-2?z=1:E%2===0&&D%2===0&&(E<2&&D<2?E===0&&D===0&&(z=2):z=2),N=g.AS(N+this.S,I),z!==0){c=this.stills[e];c||(c=new Cu(this.player),this.stills[e]=c,f.appendChild(c.element));var M=Math.floor(n*E/V),w=Math.floor(x*D/r),b=Math.floor(n*(E+z)/V)-M-4,W=Math.floor(x*(D+z)/r)-w-4;g.mZ(c.element,w,M);g.qG(c.element,W,b);g.Be(c.element,"transitionDelay",(E+D)/20+"s");g.NA(c.element,"ytp-videowall-still-mini",
z===1);g.NA(c.element,"ytp-videowall-still-large",z>2);z=Math.max(W,b);g.NA(c.element,"ytp-videowall-still-round-large",z>=256);g.NA(c.element,"ytp-videowall-still-round-medium",z>96&&z<256);g.NA(c.element,"ytp-videowall-still-round-small",z<=96);N=a[N];c.suggestion!==N&&(c.suggestion=N,z=c.api.N(),M=g.nL(c.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",fu(c,N,M),g.FG(z)&&!c.api.U("web_player_log_click_before_generating_ve_conversion_params")&&(z=N.Iv(),M={},g.zm(c.api,"addEmbedsConversionTrackingParams",
[M]),z=g.Ly(z,M),c.updateValue("url",z)),(N=(N=N.sessionData)&&N.itct)&&c.api.setTrackingParams(c.element,N));e++}f.ariaBusy="false";g.NA(this.element,"ytp-endscreen-paginate",e<I);for(a=this.stills.length-1;a>=e;a--)r=this.stills[a],g.fy(r.element),g.NS(r);this.stills.length=e}};
g.C.onVideoDataChange=function(){var r=this.player.getVideoData(1);this.videoData!==r&&(r!=null&&g.aa(r)?(this.S=0,this.videoData=r,this.Me()):this.player.Hs("missg",{vid:(r==null?void 0:r.videoId)||"",cpn:(r==null?void 0:r.clientPlaybackNonce)||""}))};
g.C.ri=function(){this.S+=this.stills.length;this.Me()};
g.C.wi=function(){this.S-=this.stills.length;this.Me()};
g.C.To=function(){return this.G.Ed()};
g.C.t$=function(r){r===1?(this.C=!1,this.Y=this.videoData.clientPlaybackNonce,this.G.N$(),this.Hp&&this.Me()):(this.C=!0,this.Hp&&HO(this)&&(r===2?this.G.fT():r===3&&this.G.QG()))};
g.C.eh=function(r){if(r){for(r=0;r<this.stills.length;r++)this.T.logVisibility(this.stills[r].element,!0);this.t$(1)}else this.Y=null,this.C=!1;this.Me()};
g.C.oB=function(){return this.Hp&&HO(this)};g.T(bu,jV);bu.prototype.hasSuggestions=function(){var r;return(r=this.G)==null?void 0:r.hasSuggestions()};
bu.prototype.show=function(){if(this.player.getPlayerState()!==3){jV.prototype.show.call(this);var r=this.X;if(r){var V=this.G.hasSuggestions();g.NA(this.element,"ytp-shorts-branded-ui",V);V?r.show():r.hide()}var I;(I=g.w1(this.player))==null||I.Jf(!0);this.player.logVisibility(this.element,!0);this.watchButton.IT(!0)}};
bu.prototype.hide=function(){jV.prototype.hide.call(this);var r;(r=g.w1(this.player))==null||r.Jf(!1);this.player.logVisibility(this.element,!1);this.watchButton.IT(!1)};g.T(VwY,g.zu);g.C=VwY.prototype;g.C.Tl=function(){var r=this.player.getVideoData(),V=r.mutedAutoplay&&(r.limitedPlaybackDurationInSeconds>0||r.endSeconds>0||r.mutedAutoplayDurationMode!==2);if((this.player.isEmbedsShortsMode()||this.X)&&!V)return!0;var I;var d=!!((r==null?0:g.aa(r))||(r==null?0:(I=r.suggestions)==null?0:I.length));d=!kqY(this.player)||d;r=r.k_;I=this.player.qA();return d&&!r&&!I&&!V};
g.C.oB=function(){return this.endScreen.oB()};
g.C.R0k=function(){return this.oB()?this.endScreen.To():!1};
g.C.eC=function(){this.player.Zg("endscreen");g.zu.prototype.eC.call(this)};
g.C.load=function(){var r=this.player.getVideoData();var V=r.transitionEndpointAtEndOfStream;if(V&&V.videoId){var I=this.player.Gz().Qz.get("heartbeat"),d=g.aa(r);!d||V.videoId!==d.videoId||r.YJ?(this.player.hO(V.videoId,void 0,void 0,!0,!0,V),I&&I.Oz("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),r=!0):r=!1}else r=!1;r||(g.zu.prototype.load.call(this),this.endScreen.show())};
g.C.unload=function(){g.zu.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.C.onCueRangeEnter=function(r){this.Tl()&&(this.endScreen.created||this.endScreen.create(),r.getId()==="load"&&this.load())};
g.C.onCueRangeExit=function(r){r.getId()==="load"&&this.loaded&&this.unload()};
g.C.onVideoDataChange=function(){rEK(this);this.Y&&hs_(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.G?this.endScreen=new x3(this.player):this.endScreen=new Tf(this.player),g.S(this,this.endScreen),g.g1(this.player,this.endScreen.element,4))};g.cD("endscreen",VwY);})(_yt_player);
