(function(g){var window=this;'use strict';var ZG=function(r,V){g.u.call(this,{J:"button",Yc:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],D:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},B:[{J:"svg",D:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},B:[{J:"g",D:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},B:[{J:"g",D:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
B:[{J:"path",D:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.T=r;this.listen("click",this.onClick,this);this.updateValue("title",g.A6(r,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.t6(V.lZ(),this.element))},hNG=function(r){g.u.call(this,
{J:"div",
Z:"ytp-miniplayer-ui"});this.C=!1;this.player=r;this.K(r,"minimized",this.TR);this.K(r,"onStateChange",this.mYE);this.K(r,"documentpictureinpicturechange",this.lR7)},rmY=function(r,V){g.NA(r.player.getRootNode(),"ytp-player-minimized",V)},VDY=function(r){g.zu.call(this,r);
this.X=new g.Su(this);this.G=new hNG(this.player);this.G.hide();g.g1(this.player,this.G.element,4);r.isMinimized()&&(this.load(),g.NA(r.getRootNode(),"ytp-player-minimized",!0))};
g.T(ZG,g.u);ZG.prototype.onClick=function(){this.T.Bs("onExpandMiniplayer")};g.T(hNG,g.u);g.C=hNG.prototype;
g.C.show=function(){this.G=new g.P4(this.Sh,null,this);this.G.start();if(!this.C){this.tooltip=new g.RB(this.player,this);g.S(this,this.tooltip);g.g1(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Kq=new g.uD(this.player);g.S(this,this.Kq);this.progressBar=new g.Zt(this.player,this);g.S(this,this.progressBar);g.g1(this.player,this.progressBar.element,4);this.X=new g.u({J:"div",Z:"ytp-miniplayer-scrim"});g.S(this,this.X);this.X.Xz(this.element);this.K(this.X.element,"click",this.Gb);
var r=new g.u({J:"button",Yc:["ytp-miniplayer-close-button","ytp-button"],D:{"aria-label":"Close"},B:[g.KB()]});g.S(this,r);r.Xz(this.X.element);this.K(r.element,"click",this.Wf);r=new ZG(this.player,this);g.S(this,r);r.Xz(this.X.element);this.S=new g.u({J:"div",Z:"ytp-miniplayer-controls"});g.S(this,this.S);this.S.Xz(this.X.element);this.K(this.S.element,"click",this.Gb);var V=new g.u({J:"div",Z:"ytp-miniplayer-button-container"});g.S(this,V);V.Xz(this.S.element);r=new g.u({J:"div",Z:"ytp-miniplayer-play-button-container"});
g.S(this,r);r.Xz(this.S.element);var I=new g.u({J:"div",Z:"ytp-miniplayer-button-container"});g.S(this,I);I.Xz(this.S.element);this.j=new g.Gx(this.player,this,!1);g.S(this,this.j);this.j.Xz(V.element);V=new g.Au(this.player,this);g.S(this,V);V.Xz(r.element);this.nextButton=new g.Gx(this.player,this,!0);g.S(this,this.nextButton);this.nextButton.Xz(I.element);this.L=new g.cf(this.player,this,0);g.S(this,this.L);this.L.Xz(this.X.element);this.Y=new g.u({J:"div",Z:"ytp-miniplayer-buttons"});g.S(this,
this.Y);g.g1(this.player,this.Y.element,4);r=new g.u({J:"button",Yc:["ytp-miniplayer-close-button","ytp-button"],D:{"aria-label":"Close"},B:[g.KB()]});g.S(this,r);r.Xz(this.Y.element);this.K(r.element,"click",this.Wf);r=new g.u({J:"button",Yc:["ytp-miniplayer-replay-button","ytp-button"],D:{"aria-label":"Close"},B:[g.FU()]});g.S(this,r);r.Xz(this.Y.element);this.K(r.element,"click",this.z18);r=new ZG(this.player,this);g.S(this,r);r.Xz(this.Y.element);this.K(this.player,"presentingplayerstatechange",
this.Yx);this.K(this.player,"appresize",this.yy);this.K(this.player,"fullscreentoggled",this.yy);this.yy();this.C=!0}this.player.getPlayerState()!==0&&g.u.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.C.hide=function(){this.G&&(this.G.dispose(),this.G=void 0);g.u.prototype.hide.call(this);this.player.isMinimized()||(this.C&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.C.eC=function(){this.G&&(this.G.dispose(),this.G=void 0);g.u.prototype.eC.call(this)};
g.C.Wf=function(){this.player.U("kevlar_watch_while_v2")||this.player.stopVideo();this.player.Bs("onCloseMiniplayer")};
g.C.z18=function(){this.player.playVideo()};
g.C.Gb=function(r){if(r.target===this.X.element||r.target===this.S.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.C.TR=function(){rmY(this,this.player.isMinimized())};
g.C.lR7=function(){rmY(this,this.player.uu());g.NA(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.uu())};
g.C.uI=function(){this.progressBar.Uk();this.L.Uk()};
g.C.Sh=function(){this.uI();this.G&&this.G.start()};
g.C.Yx=function(r){g.v(r.state,32)&&this.tooltip.hide()};
g.C.yy=function(){var r=this.player.gs().getPlayerSize().width;g.jkj(this.progressBar,0,r,!1);g.Xl(this.progressBar)};
g.C.mYE=function(r){this.player.isMinimized()&&(r===0?this.hide():this.show())};
g.C.lZ=function(){return this.tooltip};
g.C.RJ=function(r,V,I,d,a){var f=0,e=0,n=0,D=g.Pe(r);d=V&&(g.nL(V,"ytp-prev-button")||g.nL(V,"ytp-next-button"));if(V){I=g.nL(V,"ytp-play-button");var x=g.nL(V,"ytp-miniplayer-expand-watch-page-button");d?f=n=12:I?(V=g.ve(V,this.element),n=V.x,f=V.y-12):x&&(n=g.nL(V,"ytp-miniplayer-button-top-left"),f=g.ve(V,this.element),V=g.Pe(V),n?(n=8,f=f.y+40):(n=f.x-D.width+V.width,f=f.y-20))}else n=I-D.width/2,e=25+(a||0);V=this.player.gs().getPlayerSize();a=f+(a||0);D=g.yv(n,0,V.width-D.width-12);a?(r.style.top=
a+"px",r.style.bottom=""):(r.style.top="",r.style.bottom=e+"px");r.style.left=D+"px";e=g.nL(r,"ytp-preview");r.style.visibility=d&&e&&V.height<225?"hidden":""};g.T(VDY,g.zu);g.C=VDY.prototype;g.C.onVideoDataChange=function(){if(this.player.getVideoData()){var r=this.player.getVideoAspectRatio(),V=16/9;r=r>V+.1||r<V-.1;g.NA(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",r)}};
g.C.create=function(){g.zu.prototype.create.call(this);this.X.K(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.C.Gw=function(){return!1};
g.C.load=function(){this.player.hideControls();this.G.show()};
g.C.unload=function(){this.player.showControls();this.G.hide()};g.cD("miniplayer",VDY);})(_yt_player);
